#! /bin/bash
################################################################################
#                         CONFIDENTIAL AND PROPRIETARY
#         Copyright (C) 2007-2010 Xiotech Corporation, All Rights Reserved
################################################################################
#
# Installation script for kicking off an ise disk fw upgrade process
#
################################################################################

mkdir -p /tmp/ise
tar jxf E.tbz2 -C / ; ldconfig
cp CCBE.tbz2 /tmp/ise
cp ccbCL.ini /tmp/ise
cp ise_disk_upgrader /tmp/ise
cp ise_disk.cfg /tmp/ise
cp disk_do_many_ises /tmp/ise
cp *.ima /tmp/ise
mv /root/.ssh/known_hosts /root/.ssh/known_hosts.save || true
pushd /tmp/ise
chmod a+x disk_do_many_ises ise_disk_upgrader
tar jxvf CCBE.tbz2
mv ccbCL.ini CCBE/
/usr/bin/perl ./disk_do_many_ises production >&log.out &
popd

