#!/bin/bash -ex

FILE=ZZZ
CSV=${FILE}.csv
MID=${FILE}.mid
WAV=${FILE}.wav

./c11.pl > ${CSV}
csvmidi ${CSV} ${MID}

fluidsynth -F "${WAV}" -a coreaudio -i -n -q /Users/m4/src/GeneralUser_GS/GeneralUser_GS.sf2 -g 0.5 -K 64 "${MID}"

cp ${WAV} ~/Downloads/

exit 0
