#!/bin/bash -e
# $Id: cp-if-change 16657 2007-01-03 22:29:59Z mdr $
#
# Copyright 2005-2006 Xiotech Corporation. All rights reserved.
#
# This script copies a file only if the target does not exist or if the
# content of the source and destination files are different. This avoids
# needless rebuilds in some cases.
#
# Usage:
#	cp-if-change src dest

if [ -r $2 ]; then	# If destination exists and is readable
	if cmp $1 $2 > /dev/null; then
		echo $1 has not changed.
		exit 0
	fi
fi
mkdir -p ${2%/*} || echo mkdir -p ${2%/*} failed
if cp $1 $2; then
	echo cp $1 $2 done.
else
	echo cp $1 $2 failed
	exit 1
fi

# vi:sw=8 ts=8 noexpandtab
