#!/bin/bash -e
#
# This is a check just to see if all patches in a kernel version directory
# are used. Used manually just to double-check the condition of things.
#
# Mark D. Rustad, 1/22/2009
# Copyright 2009 Xiotech Coropation. All rights reserved.

VER=$1

cd ${VER} ||
	{ echo "Kernel version directory ${VER} not found"; exit 1; }

TMPF=../tmp.$$

MAKEFLAGS= make -f - <<EOF || { echo "Failed to get patches file."; exit 1; }
include patches
all:
	@echo \${PATCHES} > ${TMPF}
EOF

PATCHES=`cat ${TMPF}`
test "${PATCHES}x" != "x" || { echo "PATCHES is null."; exit 1; }
rm -f ${TMPF}

for p in ${PATCHES}; do
	test -f ${p} ||
		{ echo "Patch file ${p} not found."; exit 1; }
done

for f in *.patch; do
	match=0
	for p in ${PATCHES}; do
		test "${f}" != "${p}" || { match=1; break; }
	done
	test ${match} -ne 0 ||
		echo "Patch file ${f} not referenced in patches"
done

