#!/bin/csh -x
rsh dot 'mail -v -s "E-mail testing" Marshall_Midden@xiotech.com' << EOF_e_mail_message++
Hi there, this is dot4 e-mailing.
Does it get there?  Blank line follows.

The end of the file after a line with only a . on it.
.
EOF_e_mail_message++
