#!/bin/bash -ex
#-----------------------------------------------------------------------------
DISK=/dev/sdc
#-----------------------------------------------------------------------------
LOCAL_WWPN=21:00:00:24:ff:0f:b0:46
#-----------------------------------------------------------------------------
# 2694 - bottom port (cabled)
REMOTE_WWPN=21:00:00:24:ff:83:01:0b
#-----------------------------------------------------------------------------
FILE_NAME=export_to_229
LUN=1
#-----------------------------------------------------------------------------
logger 'before deleting target'
sleep 1
#-----------------------------------------------------------------------------
targetcli <<EOF_TARGETCLI
set global auto_cd_after_create=false
/qla2xxx/${LOCAL_WWPN}/acls delete ${REMOTE_WWPN}
/qla2xxx/${LOCAL_WWPN}/luns delete ${LUN}
# /qla2xxx delete ${LOCAL_WWPN}
/backstores/fileio delete ${FILE_NAME}
cd /
# ls
EOF_TARGETCLI
#-----------------------------------------------------------------------------
logger 'after deleting target'
sleep 1
/px/bin/targetcli_probe
exit 0
#-----------------------------------------------------------------------------
