#!/bin/bash -x
FEDEVS=03/01.0:03/01.1:02/03.0:02/03.1
BEDEVS=07/01.0:07/01.1:06/01.0:06/01.1
CPU_SPEED=3201
MICROMEMORY=02/01.0

export FEDEVS BEDEVS CPU_SPEED MICROMEMORY


#ulimit -c unlimited
#ulimit -d unlimited
#ulimit -f unlimited
#ulimit -l unlimited
#ulimit -m unlimited
ulimit -s unlimited	# needed for gdb
#ulimit -v unlimited

ulimit -a
#------------------------------------------------------------------------------
make de_gdb
