#!/bin/bash -x

make MODEL=3000 clean
make MODEL=7000 clean
make MODEL=4700 clean
make MODEL=7400 clean

make MODEL=3000 Debug || exit 1
make MODEL=7000 Debug || exit 1
make MODEL=4700 Debug || exit 1
make MODEL=7400 Debug || exit 1

make MODEL=3000 Perf || exit 1
make MODEL=7000 Perf || exit 1
make MODEL=4700 Perf || exit 1
make MODEL=7400 Perf || exit 1
