#!/bin/csh -x
set time = (1 '\
Wall time %E.  System CPU %S sec.  User CPU %U sec.  CPU %P%%\
Memory %M kb.  Shared %X kb.  Unshared data %D kb.  Unused stack %K kb.\
Swaps %W.  Page faults %F.  Input %I blks.  Output %O blks.\
')				# time automatically after 1 seconds.
#
# ./writecnt of=/dev/sdc bs=512
# ./writecnt of=/dev/sdc bs=1k
# ./writecnt of=/dev/sdc bs=2k
# ./writecnt of=/dev/sdc bs=4k
# ./writecnt of=/dev/sdc bs=8k
# ./writecnt of=/dev/sdc bs=16k
# ./writecnt of=/dev/sdc bs=32k
# ./writecnt of=/dev/sdc bs=64k
# ./writecnt of=/dev/sdc bs=128k
# ./writecnt of=/dev/sdc bs=256k
# ./writecnt of=/dev/sdc bs=512k
# ./writecnt of=/dev/sdc bs=1m
# ./writecnt of=/dev/sdc bs=2m
# ./writecnt of=/dev/sdc bs=4m
# ./writecnt of=/dev/sdc bs=8m
# qlogic magnitude 4000, vdisk size= 740mb.
# bs=64k	11840	0:04.60.
# bs=256k	2960	0:04.67.
# bs=16k	47360	0:04.68.
# bs=32k	23680	0:06.41.
# bs=512k	1480	0:06.60.
# bs=2m		370	0:07.12.
# bs=8k		94720	0:09.21.
# bs=1m		740	0:14.39.
# bs=4k		189440	0:17.43.
# bs=4m		185	0:17.46.
# bs=128k	5920	0:18.06.
# bs=8m		92	0:22.92.
# bs=2k		378880	8:23.20.
# bs=1k		757760	8:59.52.
# bs=512	1515520	9:10.12.
