#!/bin/csh -x
set time = (1 '\
Wall time %E.  System CPU %S sec.  User CPU %U sec.  CPU %P%%\
Memory %M kb.  Shared %X kb.  Unshared data %D kb.  Unused stack %K kb.\
Swaps %W.  Page faults %F.  Input %I blks.  Output %O blks.\
')				# time automatically after 1 seconds.
#
# ./writep2 of=/dev/sdc bs=64k
# ./readp2 if=/dev/sdc bs=64k

root ./writep2 of=/dev/sdf bs=512
root ./readp2 if=/dev/sdf bs=512
