#!/bin/bash

if [ $# -ne 3 ]; then
    echo ""
    echo "Usage:    GenRlsNotesByVers BRANCH FROM-VER TO-VER"
    echo ""
    echo "Examples: GenRlsNotesByVers CT1_BR A1E0 A1F0 > ~/MyRlsNotes.txt"
    echo "          GenRlsNotesByVers TRUNK B080 HEAD  > ~/MyRlsNotes.txt"
    echo ""
    echo "Notes:    1) Intended only for use with Wookiee releases."
    echo "          2) Must be called from within an updated 'Wookiee' directory."
    echo "          3) Output goes to STDOUT, so you must redirect to capture it."
    echo "          4) Use \"TRUNK\" as the BRANCH name to follow MAIN."
    echo "          5) Only scans: CCB Proc Shared Linux & CCBE."
    echo "          6) 'HEAD' can be specified as the 'TO-VER'"
    echo ""
    exit
fi


if [ "$1" == "TRUNK" ]; then 
  VER1=YETI_MAIN_${2}
else
  VER1=YETI_${1}_${2}
fi

if [ "$3" == "HEAD" ]; then 
  VER2=HEAD
else
  if [ "$1" == "TRUNK" ]; then 
    VER2=YETI_MAIN_${3}
  else
    VER2=YETI_${1}_${3}
  fi
fi

echo "Follow branch: $1"
echo "From Tag:      ${VER1}"
echo "To Tag:        ${VER2}"
echo "----------------------------------------------------------------------"

cvs2cl.pl --stdout \
          --follow-only $1 \
          --separate-header \
          --no-times  \
          --ignore WN.table \
          --delta ${VER1}:${VER2} \
          CCB Proc Shared Tools Linux CCBE
