#!/bin/bash -ex

mount -t cifs //172.22.12.90/m4a /mnt/z/a -o username=administrator,password='AlphaDog123!',domain=dc180

mount -t cifs //172.22.12.90/m4b /mnt/z/b -o username=administrator,password='AlphaDog123!',domain=dc180
