#!/usr/bin/perl -w
  my($AA, $BB);
  my $OUTPUT;

  $AA = `svn list --verbose  --depth empty svn://192.168.1.130/. | awk '{print \$1}'`;
  $AA = $AA + 1;
print STDERR "Starting with revision $AA\n";
  $BB = `svn list --verbose  --depth empty svn://svn.xiotech.com/. | awk '{print \$1}'`;
print STDERR "Current svn.xiotech.com revision is $BB\n";

  if ($AA > $BB) {
    die "Current backup revision greater or equal to current svn revision ($AA-$BB)\n"
  }

while ($AA <= $BB) {
    print STDERR `root rm -f /tmp/AAA.svnadmin.dump.incremental.${AA}`;

    print STDERR `ssh root\@svn.xiotech.com /usr/local/bin/svnadmin dump --quiet /usr/local/subversion_repos -r ${AA} --incremental | dd of=/tmp/AAA.svnadmin.dump.incremental.${AA}`;

    print STDERR "finished svnadmin dump ${AA}\n";

    print STDERR `dd if=/tmp/AAA.svnadmin.dump.incremental.${AA} | ssh root\@192.168.1.130 /usr/local/bin/svnadmin load --quiet /usr/local/subversion_repos`;

    print STDERR "finished svnadmin load ${AA}\n";

      $CC = `svn list --verbose  --depth empty svn://192.168.1.130/. | awk '{print \$1}'`;
    print STDERR "new ending revision for 192.168.1.130 is ${CC}\n";

    print STDERR `root rm -f /tmp/AAA.svnadmin.dump.incremental.${AA}`;
    $AA = $AA + 1;
}
