#!/bin/bash -e
echo "In $0 $* <------------------------------------------------------------"
#-----------------------------------------------------------------------------
W=`pwd`                 # Where script is being run from (i.e. home directory?).
D=`dirname $0`          # Where this script is located and being run.
f=${D:0:1}
if [ "$f" = '/' ]; then
    W=''
    D=${D:1}
    D=`echo "${D}" | sed -e 's;/\.$;;'`
fi
M=`realpath -m ${W}/${D}/..`
R=`realpath -m --relative-to ${M} ${W}/${D}`
#-----------------------------------------------------------------------------
cd "${M}"
#-----------------------------------------------------------------------------
IP="$1"					# I[]
SHARE="$2"				# NAMED
OPT="$3"				# O
V="$4"					# V[]
CIFSIP="$5"				# W[]
#-----------------------------------------------------------------------------
if [ "${IP}" = '' -o "${SHARE}" = '' -o "${V}" = '' ]; then
    echo "Need 4 or 5 arguments to script."
    exit 1
fi

if [ "${OPT}" = '-' -o "${OPT}" = '' ]; then
    OPT='ro'
else
    OPT="ro,${OPT}"
fi

if [ "${CIFSIP}" = '-' -o "${CIFSIP}" = '' ]; then
    CIFSIP=''
    USR=''
    PW=''
    DOMAIN=''
else
    DOMAIN='AD'
    USR='Parsec.Backup'
    PW='Cobra!Indigo'
fi
#-----------------------------------------------------------------------------
echo run the umount and mount scripts

${R}/umount "${IP}" "${SHARE}"
${R}/mount "${IP}" "${SHARE}" "${OPT}"

# On windows box where we will set things, up -- ready to mount drive letter.
if [ "${CIFSIP}" != '' ]; then
    # Unmount possible mounted already drive letter.
    ssh ${USR}@${CIFSIP} net use ${V} /delete || true
    # Mount SAN storage on windows machine.
    scp ${M}/scripts-2-copy/Net-use.bat ${USR}@${CIFSIP}:net-use.bat
fi
#-----------------------------------------------------------------------------
if [ "${CIFSIP}" != '' ]; then
#??    ${M}/scripts-2-copy/GET-INFO "${V}" "${SHARE}" "${IP}" "${CIFSIP}" "${DOMAIN}\\${USR}" "${PW}"
    ${M}/scripts-2-copy/GET-INFO "${V}" "${SHARE}" "${CIFSIP}" "${IP}" "${DOMAIN}"'\\'"${USR}" "${PW}"
else
    ${M}/scripts-2-copy/GET-INFO "${V}" "${SHARE}" "${IP}"
fi
#-----------------------------------------------------------------------------
${R}/umount "${IP}" "${SHARE}"
#=============================================================================
echo "Done with $0 $*"
exit 0
#-----------------------------------------------------------------------------
# End of script getinfo
