#!/bin/bash -e
echo "In $0 $* <------------------------------------------------------------"
#-----------------------------------------------------------------------------
W=`pwd`
D=`dirname $0`
f=${D:0:1}
if [ "$f" = '/' ]; then
    W=''
    D=${D:1}
    D=`echo "${D}" | sed -e 's;/\.$;;'`
fi
M=`realpath -m ${W}/${D}/..`
R=`realpath -m --relative-to ${M} ${W}/${D}`
#-----------------------------------------------------------------------------
cd "${M}"
#-----------------------------------------------------------------------------
IP="$1"
SHARE="$2"
if [ "${IP}" = '' -o "${SHARE}" = '' ]; then
    echo 'Need two arguments at least. IP and share-name.'
    exit 1
fi
OPT="$3"
if [ "${OPT}" != "" -a "${OPT}" != "-" ]; then
    OPT=",${OPT}"
else
    OPT=""
fi
# Windows server to mount and change attributes on -- if present.
WIN="$4"
# Volume on Windows server -- could be mounted.
VOL="$5"
CYGVOL=`echo "$5" | sed s/://`
#-----------------------------------------------------------------------------
USR='Parsec.Admin'
#-----------------------------------------------------------------------------
${R}/umount "${IP}" "${SHARE}"
#-----------------------------------------------------------------------------
# On windows box where we will set attributes -- ready to mount drive letter.
if [ "${WIN}" != "" -a "${WIN}" != "-" ]; then
    # Unmount possible mounted already drive letter.
    ssh ${USR}@${WIN} "net use ${VOL} /delete || true"
    # Mount SAN storage on windows machine.
    scp ${M}/scripts-2-copy/Net-use.bat ${USR}@${WIN}:net-use.bat
    ssh ${USR}@${WIN} "cmd.exe /c net-use.bat ${VOL} ${IP} ${SHARE}" \
                                  "'AD\Parsec.Backup' 'Cobra!Indigo' ;" \
                                  "cd /cygdrive/${CYGVOL} ;" \
                                  "attrib -H -S -R /s /d ;" \
				  "rm -rf link*la*;"
    ssh ${USR}@${WIN} "net use ${VOL} /delete || true"
else
    ssh ${USR}@${IP} "cd /cygdrive/${CYGVOL}/${SHARE} ;" \
                     "attrib -H -S -R /s /d ;" \
		     "rm -rf link*la*;"
fi
#-----------------------------------------------------------------------------
${R}/mount "${IP}" "${SHARE}" "${OPT}"
#-----------------------------------------------------------------------------
cd /mnt/${IP}/${SHARE}
F=`find .[a-zA-Z0-9]* *`                                || true
setfattr -n user.cifs.dosattrib -v 0x00000000 -- ${F}   || true
rm -rf ${F}                                             || true
cd ${M}
#-----------------------------------------------------------------------------
${R}/umount "${IP}" "${SHARE}"
#-----------------------------------------------------------------------------
echo "Done with $0 $*"
exit 0
#-----------------------------------------------------------------------------
