#!/bin/bash -e
echo "In $0 $* <------------------------------------------------------------"
#-----------------------------------------------------------------------------
W=`pwd`                 # Where script is being run from (i.e. home directory?).
D=`dirname $0`          # Where this script is located and being run.
f=${D:0:1}
if [ "$f" = '/' ]; then
    W=''
    D=${D:1}
    D=`echo "${D}" | sed -e 's;/\.$;;'`
fi
M=`realpath -m ${W}/${D}/..`
R=`realpath -m --relative-to ${M} ${W}/${D}`
#-----------------------------------------------------------------------------
cd "${M}"
#-----------------------------------------------------------------------------
IP="$1"
SHARE1="$2"
SHARE2="$3"
V="$4"
OPT="$5"
WIN="$6"
ADM="$7"
if [ "$7" = '' ]; then
    echo "$0 needs seven arguments."
    exit 1
fi
#-----------------------------------------------------------------------------
echo "IP=${IP} SHARE1=${SHARE1} SHARE2=${SHARE2} V=${V} OPT=${OPT} WIN=${WIN} ADM=${ADM}"
#-----------------------------------------------------------------------------
#- IP="172.22.13.100"
#- #-- NetAPP
#- SHARE1="m4_v1"
#- SHARE2="m4_v2"
#- V="N:"
#- SERVER="smb-server-2012.ad.parsec.lab"
${R}/rm-files "${IP}" "${SHARE1}" "${OPT}" "${WIN}" "${V}"
#-----------------------------------------------------------------------------
${R}/mount "${IP}" "${SHARE1}" "${OPT}"
#-----------------------------------------------------------------------------
if [ "${WIN}" = '-' ]; then
    SCPTO=${IP}
else
    SCPTO=${WIN}
fi
${M}/scripts-2-copy/SETUP.windowsserver.share "${V}" "${SHARE1}" "${IP}" "${WIN}" \
	"Parsec.Admin@${SCPTO}" "Parsec.Backup@${SCPTO}" "m4@${SCPTO}" "${ADM}+administrator@${SCPTO}"
#-----------------------------------------------------------------------------
${R}/umount "${IP}" "${SHARE1}"
#-----------------------------------------------------------------------------
#-- # Do the destination outside of this script.
#-- ${R}/rm-files "${IP}" "${SHARE2}" "${OPT}" "${WIN}" "${V}"
#=============================================================================
echo "Done with $0 $*"
exit 0
#-----------------------------------------------------------------------------
# End of script setup-files
