#!/bin/bash -e
echo "In $0 $* <------------------------------------------------------------"

IP="$1"
SHARE1="$2"
SHARE2="$3"
if [ "${IP}" = '' -o "${SHARE1}" = '' ]; then
    echo "Un-mount requires at least two arguments. IP/DNS-name and share."
    exit 1
fi
#-----------------------------------------------------------------------------
check_umount()
{
    until [ `mount | grep -c " /mnt/${IP}/$1 "` -eq 0 ]; do
	echo "umount /mnt/${IP}/$1"
	umount "/mnt/${IP}/$1" || sleep 2
    done
}
#-----------------------------------------------------------------------------
check_umount "${SHARE1}"

if [ "${SHARE2}" != '' ]; then
    check_umount "${SHARE2}"
fi
#-----------------------------------------------------------------------------
echo "Done with $0 $*"
exit 0
#-----------------------------------------------------------------------------
# End of script umount
