#!/bin/bash -uepx

(cd ~/musicomp2abc && make clean && make all && ./AAA.diff._2 && make clean)

(cd ~/Desktop/plato-stuff/music/songs && make clean && make all && ./AAA.diff._2 && make clean)
(cd ~/Desktop/saved-m4-stuff/src/b && make clean && make all && ./AAA.diff._2 && make clean)
(cd ~/Desktop/saved-m4-stuff/src/t/e && make clean && make all && ./AAA.diff._2 && make clean)

echo "ALL OKAY!"
exit 0
