#!/bin/bash -exup

rm -f /cores/*
rm -f tmp.entitlements

ulimit -c unlimited
defaults write com.apple.finder AppleShowAllFiles TRUE

INPUT='v4-4_2.abc'
OUTPUT='v4-4_2.ps'

#-- PROGRAM='abcm2ps'
PROGRAM='/Users/m4/Desktop/saved-m4-stuff/src/abcm2ps/abcm2ps'
PROGRAM_ARGS="-M -b 1 ${INPUT} -i -N 2 -j 1"

#++ /usr/libexec/PlistBuddy -c "Add :com.apple.security.get-task-allow bool true" tmp.entitlements > /dev/null 2>&1
#++ codesign -s - -f --entitlements tmp.entitlements "${PROGRAM}" > /dev/null 2>&1
/usr/libexec/PlistBuddy -c "Add :com.apple.security.get-task-allow bool true" tmp.entitlements
codesign -s - -f --entitlements tmp.entitlements "${PROGRAM}"

#-- PROGRAM='./myprogram'

(${PROGRAM} ${PROGRAM_ARGS} ; mv Out.ps ${OUTPUT}) || ls -lA /cores
#-----------------------------------------------------------------------------
#-----------------------------------------------------------------------------
#- (abcm2ps -M -b 1 v4-4_2.abc -i -N 2 -j 1 ; mv Out.ps v4-4_2_m.ps) || (rm -f v4-4_2_m.ps ; exit 1)
ps2pdf v4-4_2.ps v4-4_2.pdf || (rm -f v4-4_2.pdf ; exit 1)
open v4-4_2.pdf

exit 0
