#!/bin/bash -x
rm -f W3.fs W3.v.10.fs    W3.v.no.10.fs
rm -f       Z.3.v.10      Z.3.v.no.10

export MC_ARGS=--lines
make W3.fs > Z.3.v.10 2>&1
mv W3.fs W3.v.10.fs

make W3.v.no.10.fs > Z.3.v.no.10 2>&1

exit 0
