#!/bin/bash -x
rm -f W6.fs W6.p.10.fs   W6.p.no.10.fs
rm -f       Z.6.p.10     Z.6.p.no.10

export MC_ARGS=--lines
make W6.fs > Z.6.p.10 2>&1
mv W6.fs W6.p.10.fs

make W6.p.no.10.fs > Z.6.p.no.10 2>&1

exit 0
