#!/bin/bash

cd ~root

chkconfig -s < stdconfig.save

test ! -x /usr/bin/make || { umount -l /usr; ldconfig 2>/dev/null; }

cd /etc
cp hosts.std hosts
cp passwd.std passwd
cp shadow.std shadow
cp group.std group
cp fstab.std fstab
