#!/usr/bin/python3 -B
# ----------------------------------------------------------------------------
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
# ----------------------------------------------------------------------------
import argparse
import os
import re
import readline
import sys
# ----------------------------------------------------------------------------
global errors_happened
errors_happened = 0

# ----------------------------------------------------------------------------
def print_eoln(strg):
    print(strg, file=sys.stderr, flush=True)
    return
# End of print_eoln

# ----------------------------------------------------------------------------
def print_debug(strg):
    print_eoln(strg)
    return
# End of print_debug

# ----------------------------------------------------------------------------
def print_error_no_line(strg):
    print("ERROR - " + strg, file=sys.stderr, flush=True)
    return
# End of print_error_no_line

# ----------------------------------------------------------------------------
def print_fs(strg):
    global array_of_fs

    if len(array_of_fs) > 0:
        last = array_of_fs[-1]
        if last[0:6] == 'sleep ' and strg[0:6] == 'sleep ':
            new_time1 = float(last[6:])
            new_time2 = float(strg[6:])
            array_of_fs[-1] = f'sleep {(new_time1 + new_time2):.3f}'
            return
# Can't delete duplicates. Two notes in a row will delete one (on OR off).
#--         elif last == strg:                          # Delete duplicates.
#--             return
        # fi
    # fi
    array_of_fs.append(strg)
    return

# ----------------------------------------------------------------------------
def print_output(strg):
    print(strg.rstrip(), file=output_name, flush=True)
    return
# End of print_output

# ----------------------------------------------------------------------------
global args

# ----------------------------------------------------------------------------
def parse_args():
    global args

    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='this is the epilog')
    parser.add_argument('--lines', '-lines', action='store_true',
                        help='Print each line as it is read from file or macro or loop.')
    parser.add_argument('rest', nargs='*',
                        help='Optional input file, then optional output file.')
    args = parser.parse_args()
    return
# End of parse_args

# ----------------------------------------------------------------------------
parse_args()

# ----------------------------------------------------------------------------
global which_file_in
which_file_in = 'stdin'
global linecount
linecount = 0
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
global voices                       # Number of voices
voices = None
global voices_2_channel             # For voice #7, array of channels.
voices_2_channel = {}
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
global file_name                    # None = use tty.
global output_name                  # File to print to (default is sys.stdout).
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
global array_of_lines               # For input, have an array of lines.
array_of_lines = []
global array_of_fs                  # For fs first pass output.
array_of_fs = []

# ----------------------------------------------------------------------------
# Following does not do multiple sharps or flats, but that is crazy anyway. Neither naturals.
global key_sig
key_sig = { 'c+':7, 'f+':6, 'b':5, 'bn':5, 'e':4, 'en':4, 'a':3, 'an':3, 'd':2,
            'dn':2, 'g':1, 'gn':1, 'c':0, 'cn':0, 'f':-1, 'b-':-2, 'e-':-3,
            'a-':-4, 'd-':-5, 'g-':-6, 'c-':-7 }

global key_sig_int
key_sig_int = {}
for i in key_sig:
    if key_sig[i] not in key_sig_int:
        key_sig_int[key_sig[i]] = i
    # fi
# rof

# ----------------------------------------------------------------------------
global default_little_time
default_little_time = 0.1
# ----------------------------------------------------------------------------
def print_fluidsynth_header():
    # set audio.coreaudio.device coreaudio
    print_fs("set audio.driver coreaudio")
    print_fs("set midi.driver coremidi")
    print_fs("unload 1")
    print_fs("unload 2")
    print_fs("unload 3")
    print_fs("unload 4")
    print_fs("unload 5")
    print_fs("set synth.default-soundfont /Users/m4/src/GeneralUser_GS/GeneralUser_GS.sf2")
    print_fs("set synth.midi-channels 128")
    print_fs("set synth.verbose 0")
    print_fs("reset")
    print_fs("reset")
    print_fs("load /Users/m4/src/GeneralUser_GS/GeneralUser_GS.sf2")
    #
    print_fs('set synth.reverb.active 1')
    print_fs('set synth.reverb.room-size 0.61')
    print_fs('set synth.reverb.damp 0.23')
    print_fs('set synth.reverb.width 0.76')
    print_fs('set synth.reverb.level 0.57')
    #
    print_fs('set synth.chorus.active 1')
    print_fs('set synth.chorus.nr 3')
    print_fs('set synth.chorus.level 1.2')
    print_fs('set synth.chorus.speed 0.3')
    print_fs('set synth.chorus.depth 8')
    #
    print_fs("prog 00 000")
    #
    return
# End of print_fluidsynth_header

# ----------------------------------------------------------------------------
global fs_other_echo
fs_other_echo = ''
global this_time
this_time = []
global MIDICLICKSPERQUARTER
MIDICLICKSPERQUARTER = 480.0
# ----------------------------------------------------------------------------
# FF 58 04 nn dd cc bb Time Signature
# The time signature is expressed as four numbers. nn and dd represent the numerator
# and denominator of the time signature as it would be notated. The denominator
# is a negative power of two: 2 represents a quarter-note, 3 represents an eighth-note,
# etc. The cc parameter expresses the number of MIDI clocks in a metronome click.
# The bb parameter expresses the number of notated 32nd-notes in a MIDI quarter-note
# (24 MIDI clocks). This was added because there are already multiple programs which
# allow a user to specify that what MIDI thinks of as a quarter-note (24 clocks) is
# to be notated as, or related to in terms of, something else.
# 
# Therefore, the complete event for 6/8 time, where the metronome clicks every three
# eighth-notes, but there are 24 clocks per quarter-note, 72 to the bar, would be (in hex):
#       FF 58 04 06 03 24 08
#                nn dd cc bb
# That is, 6/8 time (8 is 2 to the 3rd power, so this is 06 03), 36 MIDI clocks per
# dotted-quarter (24 hex!), and eight notated 32nd-notes per quarter-note. 
#    i.e. 2*32=1/16, 4*32=1/8, 8*32=1/4.  And a 1/4 note is 0x24 time deltas long.
# If the 8 was changed to 16, then a 1/2 note is 0x24 long. (0x24=36)

def meter_readable(strg):
    s = strg.split()
    print_debug(f's={s}')
    numerator = int(s[0])
    denominator = 2 ** int(s[1])
#--         print_output("{}, {}, Time_signature, {}, {}, 48, 8".format(
#--                 voiceon+1, round(lthworkingmeasure), numerator, denominator))
    return f'{numerator}/{denominator}'
# End of print_out_midi1csv_ts

# ----------------------------------------------------------------------------
def process_fs_check(what, lth, min_next, vtlines, tempo_s, tempo_l):
    global this_time
    global fs_other_echo
    global key_sig_int
    global voices
    global voices_2_channel
    global MIDICLICKSPERQUARTER

    for voice, lines in vtlines.items():
        if this_time[voice] >= len(lines):
            continue
        # fi

        t = lines[this_time[voice]].split(' ', 1) # 2 elements
        t[0].strip()
        time = float(t[0])
        while time <= min_next:
            strg = t[1].rstrip()
            if strg == 'End_track':
                pass
            elif strg[0:lth] == what:
                if what != 'cc':
                    print_fs(strg)
                # fi
            elif strg[0:5] == 'echo ':           # echo "measure xxx"
                if strg[0:6] == 'echo "':
                    print_fs(f'{strg}')
                elif strg != fs_other_echo:
                    strg1 = strg.replace('"', "'")
                    if strg1[0:11] == 'echo meter ':
                        print_fs(f'echo "meter {strg1[11:]}"')
                    elif strg1[0:9] == 'echo key ':
                        x = strg1[9:]
                        y = x.split(' ', 2)          # voice number, then key number.
                        ky = y[0]
                        x = y[2]
                        y = int(y[1].replace(',', '').strip())
                        if y in key_sig_int:
                            y = key_sig_int[y].upper()
                        # fi
#--                         print_fs(f'echo "key {t[0]} {y} {x}"')
                        print_fs(f'echo "key {ky} {y} {x}"')
                    elif strg1[0:13] == 'echo Title_t ':
                        print_fs(f'echo "Title {strg1[13:]}"')
                    elif strg != fs_other_echo:
                        print_fs(f'echo "{strg1[5:]}"')
                    # fi
                    fs_other_echo = strg
                # fi
            elif strg[0:7] == 'select ':
                print_fs(f'{strg}')
            elif strg[0:4] == 'set ':
                print_fs(f'{strg}')
            elif strg[0:6] == 'reset ':
                print_fs(f'{strg}')
            elif strg[0:5] == 'load ':
                print_fs(f'{strg}')
            elif strg[0:7] == 'unload ':
                print_fs(f'{strg}')
            elif strg[0:5] == 'prog ':
                print_fs(f'{strg}')
            elif strg[0:11] == 'pitch_bend ':
                print_fs(f'{strg}')
            elif strg[0:6] == 'tempo ':
                x = strg[6:].split()
                if len(x) < 1 or len(x) > 2:
                    print_error_no_line(f"Tempo needs a speed - line='{t}'")
                elif len(x) == 1:
                    #    1/(### / (60.0 * 1000000.0)) = 60.02400 = t              for l = 4 (quarter note).
                    tempo_s = int(1/(int(x[0]) / (60.0 * 1000000.0)))
                    tempo_l = 0.25
                else:
                    tempo_s, tempo_l = strg[6:].split()
                # fi
                print_fs(f'echo "{t[0]} tempo_s={tempo_s} tempo_l={tempo_l}"')
            elif strg[0:7] == 'Header ':
                # "0, 0, Header, 1, {}, {}".format(len(volume)+1, round(10*MIDICLICKSPERQUARTER)))
                h = strg[7:].split(', ')
                voices = int(h[1])
                MIDICLICKSPERQUARTER = int(h[2])
                print_fs(f'echo "Header {voices} {MIDICLICKSPERQUARTER}"')
            elif strg[0:3] == 'cc ':
                break
            elif strg[0:8] == 'noteoff ':
#--                h = strg[8:].split(', ')
                break
            elif strg[0:7] == 'noteon ':
#--                h = strg[7:].split(', ')
                break
            else:
                print_error_no_line(f"Unrecognized - line='{t}'")
#--                error_now = error_now + 1               # DIE NOW!
#--                break
            # fi
            this_time[voice] += 1
            if this_time[voice] >= len(lines):
                break
            # fi
            t = lines[this_time[voice]].split(' ', 1) # 2 elements
            time = float(t[0])
        # elihw
    # rof
#--     print_debug(f'tempo_s={tempo_s} tempo_l={tempo_l}')
    return tempo_s, tempo_l
# End of process_fs_check

# ----------------------------------------------------------------------------
# Thinking if we get each of the tracks in csvmidi format, in array, then go
# through them and order by:
    # track, time: In array order for each track.
    #       controls
    #       noteoff
    #       noteon
    # ... is that all that is needed? (And obvious format change.)

def print_out_fluidsynth():
    global array_of_lines
    global this_time
    global default_little_time
    global voices
    global voices_2_channel

    change_name = {
        'Text_t': 'echo',
        'Title_t': 'echo Title_t',
        'Time_signature': 'echo meter',
        'Key_signature': 'echo key',
        'Instrument_name_t': 'echo Instrument_name_t',
        'Sequencer_specific': 'echo Sequencer_specific',
        'SMPTE_offset': 'echo SMPTE_offset',
        'Note_on_c': 'noteon',
        'Note_off_c': 'noteoff',
        'Tempo': 'tempo',
        'Control_c': 'cc',
        'Pitch_bend_c': 'pitch_bend',
        # Track, Time, MIDI_port, Number This meta-event specifies that subsequent events in
        # the Track should be sent to MIDI port (bus) Number, between 0 and 255. This meta-event
        # usually appears at the start of a track with Time zero, but may appear within a track
        # should the need arise to change the port while the track is being played.
    }
    ignore_these = {
        'Copyright_t',
        'Marker_t',
        'End_of_file',
        'Channel_prefix',
        'System_exclusive',
    }
    okay_these = {
        'Header',
        'MIDI_port',
    }
    midi_port = 0

    v_t_lines = { }
    tempo_s = 60
    tempo_l = 0.5

    max_midi_time = 0

    voices = 0
    for i in array_of_lines:
        # "2, 5280, Note_on_c, 0, 43, 127"
        t = i.split(', ', 3)        # 4 elements.
        if len(t) < 3:
            print_die(f'line does not have MIDI format with voice, time, command - "{i}"')
        elif len(t) < 4:
            t.append('')
        # fi
        t[0] = t[0].strip()
        thevoicenumber = int(t[0])
        if thevoicenumber not in v_t_lines:
            v_t_lines[thevoicenumber] = []
        # fi

        if 2 > len(t) or t[2] == "Start_track":
            continue
        # fi
        t[1] = t[1].strip()
        t[2] = t[2].strip()
        if t[2] in change_name:
            t[2] = change_name[t[2]]
            t[3] = t[3].strip()
            if t[2] != 'echo':
                t[3] = t[3].replace(',', '').strip()
            # fi
            if t[2] == 'echo key':
#--                 print_debug(f'#A print_out_fluidsynth - thevoicenumber={thevoicenumber} voices_2_channel={voices_2_channel}')
                if thevoicenumber == 'ALL':
                    y = 'ALL'
                elif thevoicenumber not in voices_2_channel:
                    y = 'ALL'
                    voices_2_channel[y] = '0'
                else:
                    z = len(voices_2_channel[thevoicenumber])
                    if z == 0:
                        print_error_no_line(f'echo key - with no channel specified yet.')
                        y = 'ALL'               # This means to apply to all voices (later).
                    elif z == 1:
                        y = voices_2_channel[thevoicenumber][0]
                    else:
                        print_error_no_line(f'echo key - with more than 1 channel specified yet ({voices_2_channel[thevoicenumber]}).')
                        y = voices_2_channel[thevoicenumber][0]
                    # fi
                # fi
                t.insert(3, str(y))
#--                 print_debug(f't={t} i={i} voices_2_channel={voices_2_channel}')
            # fi
            if t[2] == 'noteon':
                h = t[3].split(' ')
                if h[2] == '0':
                    t[2] = 'noteoff'
                # fi
                q = h[0].strip(',')
                if thevoicenumber not in voices_2_channel:
                    voices_2_channel[thevoicenumber] = []
                # fi
                if q not in voices_2_channel[thevoicenumber]:
                    voices_2_channel[thevoicenumber].append(q)
                # fi
            # fi
            if t[2] == 'pitch_bend' or t[2] == 'cc':
                h = t[3].split(' ')
                q = h[0].strip(',')
                if thevoicenumber not in voices_2_channel:
                    voices_2_channel[thevoicenumber] = []
                # fi
                if q not in voices_2_channel[thevoicenumber]:
                    voices_2_channel[thevoicenumber].append(q)
                # fi
            # fi
        elif t[2] in ignore_these:
            continue
        elif t[2] in okay_these:
            if t[2] == 'MIDI_port':
                midi_port = t[3]
                continue
            # fi
            pass
        elif t[2] == 'Program_c':
# select chan sfont bank prog
            t[2] = 'select'
            t[3] = t[3].strip()
            s = t[3].split(", ", 2)     # 3 elements - channel, bank, program.
            if len(s) < 3:
#--                 s += midi_port
                s.append(midi_port)
            # fi
            if s[0] != '9':
                t[3] = f'{s[0]} 1 {s[2]} {s[1]}'
            else:
#               select 9 2 128 0  Combination of bank-select and program-change
                t[3] = f'{s[0]} 1 128 0'
            # fi
            t[2] = 'select'
            if thevoicenumber not in voices_2_channel:
                voices_2_channel[thevoicenumber] = []
            # fi
            if s[0] not in voices_2_channel[thevoicenumber]:
                voices_2_channel[thevoicenumber].append(s[0])
            # fi
        elif t[2] == 'End_track':
            if max_midi_time < float(t[1]):
                max_midi_time = float(t[1])
            # fi
            t.append('')
        else:
            print_error_no_line(f"Unexpected midi command - t='{t}'")
        # fi
        if thevoicenumber == 0:
            pass
        elif voices == 0:
#--             for z in range (1, thevoicenumber + 1):
#--                 if z not in voices_2_channel:
#--                     voices_2_channel[z] = []
#--                 # fi
#--             # rof
            voices = thevoicenumber
        elif voices < thevoicenumber:
#--             for z in range (voices, thevoicenumber + 1):
#--                 if z not in voices_2_channel:
#--                     voices_2_channel[z] = []
#--                 # fi
#--             # rof
            voices = thevoicenumber
        # fi
        if t[2] == '' and t[3] == '':
            xxx = t[1]
        elif t[3] == '':
            xxx = t[1] + ' ' + t[2]
        else:
            xxx = ' '.join(t[1:])
        # fi
        v_t_lines[thevoicenumber].append(xxx)
    # rof

    # Not figure out order of printing by time.

    current_time = -1
    this_time = []
    for v in range(0, voices+1):
        this_time.append(0)
    # rof
    while current_time < max_midi_time:
        # Find smallest time difference.
        min_next = max_midi_time + 1
        for voice, lines in v_t_lines.items():
            if this_time[voice] >= len(lines):
                continue
            # fi
            t = lines[this_time[voice]].split(' ', 1) # 2 elements
            time = float(t[0])
            if min_next > time and voice > 0:
                min_next = time
            # fi
        # rof
        if current_time >= 0 and (min_next - current_time) != 0:
            ms_1000 = float(min_next - current_time)
            if ms_1000 < default_little_time:
                ms_1000 = default_little_time
            else:
                # 480 => 250
                ms_1000 = ms_1000 * 1000.0
                ms_1000 = ms_1000 / ((float(tempo_s)/60.0) * (float(tempo_l) * 4.0))
                ms_1000 = int((ms_1000 / MIDICLICKSPERQUARTER) * 1000)
                ms_1000 = float(ms_1000) / 1000.0
            # fi
            print_fs(f'sleep {ms_1000}')
        # fi
        current_time = min_next
        # Move all this_time voices forward past min_next.
        # . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
        tempo_s, tempo_l = process_fs_check('cc', 2, min_next, v_t_lines, tempo_s, tempo_l)
        tempo_s, tempo_l = process_fs_check('noteoff', 7, min_next, v_t_lines, tempo_s, tempo_l)
        tempo_s, tempo_l = process_fs_check('noteon', 6, min_next, v_t_lines, tempo_s, tempo_l)
    # elihw

    print_fs("quit")
    return
# End of print_out_fluidsynth

# ----------------------------------------------------------------------------
# Get the next line, file, or macro.
# Return:
#   line        - the line without trailing spaces.
#   None        - if End of File.

def read_next_line():
    global linecount
    global args
    global file_name
    global errors_happened

    while True:
        try:
            if args.rest and len(args.rest) >= 1:
                line = file_name.readline()
            else:
                if sys.stdin.isatty():
                    if sys.platform == 'darwin':
                        input('input> ')
                        line = readline.get_line_buffer()
                    else:
                        line = input('input> ')
                    # fi
                else:
                    line = sys.stdin.readline()
                # fi
            # fi
            if line is None or line == '':
                sys.exit(errors_happened)
            # fi
            linecount = linecount + 1
            if line:
                line = line.rstrip()                # trailing spaces gone.
                return line
            # fi
        except EOFError:
            pass            # print("Read gave EOF", file=sys.stderr, flush=True)
        except SystemExit:
            pass            # print("Read gave system exit", file=sys.stderr, flush=True)
        except KeyboardInterrupt:
            print_error_no_line("Read got keyboard interrupt")
        except:
            print_error_no_line("Read got a processing error")
            print('   ', sys.exc_info()[0], sys.exc_info(), file=sys.stderr, flush=True)
        # yrt
        break
    # elihw
    return None
# End of read_next_line

# ----------------------------------------------------------------------------
# Parse and process line.

def process_line(original_line):
    global array_of_lines

    array_of_lines.append(original_line)
    return False
# End of process_line

# ----------------------------------------------------------------------------
def readthefile():
    global linecount
    global args

    ifdone = False
    while not ifdone:                       # Read the file loop.
        line = read_next_line()
        if args.lines:
            print_eoln(f"linecount={linecount} line='{line}'")
        # fi
        if line is None:  # If end of file.
            return
        elif not line or len(line) <= 0 or line == '':
            continue
        # fi
        line = line.rstrip()
        if not line or len(line) <= 0 or line == '':
            continue
        # fi
        line = line.strip()
        if len(line) == 0:                                  # Ignore empty line.
            continue
        # fi
        ifdone = process_line(line)
    # elihw
    return
# End of readthefile

# ----------------------------------------------------------------------------
# Main program follows.
def main():
    global args
    global file_name
    global output_name
    global voices
    global which_file_in
    global array_of_fs

    output_name = sys.stdout
    if args.rest:
        if len(args.rest) >= 1:             # Input.
            file_name = open(args.rest[0], mode='r', encoding="utf-8")
            which_file_in = args.rest[0]
        # fi
        if len(args.rest) >= 2:             # Output.
            output_name = open(args.rest[1], mode='w', encoding="utf-8")
        # fi
        if len(args.rest) > 2:              # Too many.
            print_error_no_line(f"Too many arguments, input, output only.  {args.rest}")
            sys.exit(1)
        # fi
    # fi

    readthefile()

    print_fluidsynth_header()
    print_out_fluidsynth()
    for i in array_of_fs:
        print_output(i)
    # rof
    return
# End of main

# ----------------------------------------------------------------------------
if __name__ == '__main__':
    main()
# fi
# ----------------------------------------------------------------------------
sys.exit(errors_happened)
# ----------------------------------------------------------------------------
# End of program csv2fs
# ----------------------------------------------------------------------------
