#!/bin/bash -e
#-----------------------------------------------------------------------------
DISK=/dev/sdc
#-----------------------------------------------------------------------------
LOCAL_WWPN=21:00:00:24:ff:0f:b0:46
#-----------------------------------------------------------------------------
# 2694 - bottom port (cabled)
REMOTE_WWPN=21:00:00:24:ff:83:01:0b
#-----------------------------------------------------------------------------
FILE_NAME=export_to_229
LUN=1
#-----------------------------------------------------------------------------
logger 'before creating target'
sleep 1
#-----------------------------------------------------------------------------
targetcli <<EOF_TARGETCLI
set global auto_cd_after_create=false
/backstores/fileio create ${FILE_NAME} ${DISK}
/qla2xxx create ${LOCAL_WWPN}
/qla2xxx/${LOCAL_WWPN}/luns create /backstores/fileio/${FILE_NAME} ${LUN}
/qla2xxx/${LOCAL_WWPN}/acls create ${REMOTE_WWPN}
cd /
# ls
EOF_TARGETCLI
#-----------------------------------------------------------------------------
logger 'after creating target'
sleep 1
/px/bin/targetcli_probe
exit 0
#=============================================================================
