#!/bin/bash -x
./smbclient_subnet 172.22.11
./smbclient_subnet 172.22.12
./smbclient_subnet 172.22.13
./smbclient_subnet 172.22.14
./smbclient_subnet 172.22.15
./smbclient_subnet 172.22.16
./smbclient_subnet 172.22.17
./smbclient_subnet 172.22.18
./smbclient_subnet 172.22.19
./smbclient_subnet 172.22.21
./smbclient_subnet 172.22.22

./iscsiadm_subnet 172.22.11
./iscsiadm_subnet 172.22.12
./iscsiadm_subnet 172.22.13
./iscsiadm_subnet 172.22.14
./iscsiadm_subnet 172.22.15
./iscsiadm_subnet 172.22.16
./iscsiadm_subnet 172.22.17
./iscsiadm_subnet 172.22.18
./iscsiadm_subnet 172.22.19
./iscsiadm_subnet 172.22.21
./iscsiadm_subnet 172.22.22

./showmount_subnet 172.22.11
./showmount_subnet 172.22.12
./showmount_subnet 172.22.13
./showmount_subnet 172.22.14
./showmount_subnet 172.22.15
./showmount_subnet 172.22.16
./showmount_subnet 172.22.17
./showmount_subnet 172.22.18
./showmount_subnet 172.22.19
./showmount_subnet 172.22.21
./showmount_subnet 172.22.22

exit 0
