#!/bin/bash -e
#-----------------------------------------------------------------------------
#-- I="/Users/m4/Desktop/saved-m4-stuff/src/pl/devops/services/dns/updateDNS.py"
I="/Users/m4/dns/updateDNS.py show"
#-----------------------------------------------------------------------------
if [ "$1" = "" ]; then
    echo "missing first argument of ip subnet (without fourth number)."
    exit 1
fi
if [ "$2" = "" ]; then
    i=1
else
    i="$2"
fi
#-----------------------------------------------------------------------------
#-- HUH?   ping -q -i 1 -n -t 1 -c 2 $1.$i 2>&1 | grep -v '+2 error' | grep -v '^$'
#-- ${I} $1.$i 2>&1
while [ $i -lt 255 ]; do
   ${I} $1.$i
   let i=$i+1
done

exit 1
#=============================================================================
ping: option requires an argument -- h
usage: ping [-AaDdfnoQqRrv] [-c count] [-G sweepmaxsize]
            [-g sweepminsize] [-h sweepincrsize] [-i wait]
            [-l preload] [-M mask | time] [-m ttl] [-p pattern]
            [-S src_addr] [-s packetsize] [-t timeout][-W waittime]
            [-z tos] host
       ping [-AaDdfLnoQqRrv] [-c count] [-I iface] [-i wait]
            [-l preload] [-M mask | time] [-m ttl] [-p pattern] [-S src_addr]
            [-s packetsize] [-T ttl] [-t timeout] [-W waittime]
            [-z tos] mcast-group
Apple specific options (to be specified before mcast-group or host like all options)
            -b boundif           # bind the socket to the interface
            -k traffic_class     # set traffic class socket option
            -K net_service_type  # set traffic class socket options
            -apple-connect       # call connect(2) in the socket
            -apple-time          # display current time
