#!/bin/bash
#-----------------------------------------------------------------------------
if [ "$1" = "" ]; then
    echo "missing first argument of showmount_subnet - IP subnet (without 4th number)"
    exit 1
fi
IPSUBNET=$1
if [ "$2" = "" ]; then
    i=1
else
    i="$2"
fi
#-----------------------------------------------------------------------------
ISCSIADM="iscsiadm -m discovery -t st -p"
mkdir -p OUTPUT.iscsi
#-----------------------------------------------------------------------------
let o=1
while [ $i -lt 255 ]; do
    ${ISCSIADM} $1.$i 2>&1 | egrep -v 'iscsiadm: cannot make connection to|iscsiadm: connect to|iscsiadm: connection login retries|iscsiadm: Could not perform SendTargets discovery: encountered connection failure' > OUTPUT.iscsi/A.iscsi.$1.$i &
    let i=$i+1
    let o=$o+1
    if [ $o -gt 51 ] ; then
        let o=1
        wait
    fi
done
wait

exit 1
#-----------------------------------------------------------------------------

