#!/bin/bash
#-----------------------------------------------------------------------------
if [ "$1" = "" ]; then
    echo "missing first argument of showmount_subnet - IP subnet (without 4th number)"
    exit 1
fi
IPSUBNET=$1
if [ "$2" = "" ]; then
    i=1
else
    i="$2"
fi
#-----------------------------------------------------------------------------
SHOWMOUNT="showmount -e"
mkdir -p OUTPUT.ss
#-----------------------------------------------------------------------------
let o=1
while [ $i -lt 255 ]; do
    ${SHOWMOUNT} $1.$i 2>&1 | egrep -v 'RPC: Program not registered|RPC: Unable to send' > OUTPUT.ss/A.ss.$1.$i &
    let i=$i+1
    let o=$o+1
    if [ $o -gt 51 ] ; then
        let o=1
        wait
    fi
done
wait

exit 1
#-----------------------------------------------------------------------------
