#!/bin/bash -ex
# ./A.separate && make a01 && open Out.ps 
# ./A.separate && make a02 && open Out.ps 
# ./A.separate && make a03 && open Out.ps 
# ./A.separate && make a04 && open Out.ps 

# ./A.separate && make a05 && open Out.ps 

# ./A.separate && make a06 && open Out.ps 
# ./A.separate && make a07 && open Out.ps 
# ./A.separate && make a08 && open Out.ps 
# ./A.separate && make a09 && open Out.ps 
# ./A.separate && make a10 && open Out.ps 
# ./A.separate && make a11 && open Out.ps 
# ./A.separate && make a12 && open Out.ps 
