
    !! WARNING !! WARNING !! WARNING !!
    This CD will initialize disks in most cases. If that is not
    what you want, you should remove the CD now unless you really
    know what you are doing.
    !! WARNING !! WARNING !! WARNING !!

       0 - Memtest86+ [default]
       1 - New controller installation, local vga console
       2 - New controller installation, com1,115200n8 console
       3 - HD/MBR boot



