env = Environment()

warnings = '-Wall -Wcast-align -Werror -Wextra -Wformat-nonliteral -Wformat=2 ' \
           '-Winvalid-pch -Wmissing-declarations -Wmissing-format-attribute ' \
           '-Wmissing-include-dirs -Wredundant-decls -Wswitch-default ' \
		   '-Wswitch-enum '

env.Append(CXXFLAGS='-g -O')
env.Append(CXXFLAGS=warnings)

common = [ 'suid_wrapper' ]

source = [ x+'.cpp' for x in common ]

Default( env.Program(
	'suid_wrapper',
	source,
	CPPPATH=[ '#' ]
))
