#!/bin/bash -e
# $Id: cp-if-change 6125 2005-12-13 14:37:30Z RustadM $
#
# Copyright 2005 Xiotech Corporation. All rights reserved.
#
# This script copies a file only if the target does not exist or if the
# content of the source and destination files are different. This avoids
# needless rebuilds in some cases.
#
# Usage:
#	cp-if-change src dest

if [ -r $2 ]; then	# If destination exists and is readable
	if cmp $1 $2 > /dev/null; then
		echo $1 has not changed.
		exit 0
	fi
fi
mkdir -p ${2%/*}
cp $1 $2

# vi:sw=8 ts=8 noexpandtab
