#!/bin/sh
n1="$1"
n2=`expr $n1 + 1`
n3=`expr $n2 + 1`
n4=`expr $n3 + 1`
n5=`expr $n4 + 1`
n6=`expr $n5 + 1`
n7=`expr $n6 + 1`
n8=`expr $n7 + 1`
n9=`expr $n8 + 1`
n10=`expr $n9 + 1`
n11=`expr $n10 + 1`
n12=`expr $n11 + 1`
n13=`expr $n12 + 1`
n14=`expr $n13 + 1`
n15=`expr $n14 + 1`
n16=`expr $n15 + 1`
n17=`expr $n16 + 1`
n18=`expr $n17 + 1`
n19=`expr $n18 + 1`
n20=`expr $n19 + 1`
n21=`expr $n20 + 1`
sed	-e 1s/NIBBLE/$n1/  \
	-e 2s/NIBBLE/$n2/  \
	-e 3s/NIBBLE/$n3/  \
	-e 4s/NIBBLE/$n4/  \
	-e 5s/NIBBLE/$n5/  \
	-e 6s/NIBBLE/$n6/  \
	-e 7s/NIBBLE/$n7/  \
	-e 8s/NIBBLE/$n8/  \
	-e 9s/NIBBLE/$n9/  \
	-e 10s/NIBBLE/$n10/  \
	-e 11s/NIBBLE/$n11/  \
	-e 12s/NIBBLE/$n12/  \
	-e 13s/NIBBLE/$n13/  \
	-e 14s/NIBBLE/$n14/  \
	-e 15s/NIBBLE/$n15/  \
	-e 16s/NIBBLE/$n16/  \
	-e 17s/NIBBLE/$n17/  \
	-e 18s/NIBBLE/$n18/  \
	-e 19s/NIBBLE/$n19/  \
	-e 20s/NIBBLE/$n20/  \
	-e 21s/NIBBLE/$n21/  \
	DISKDRIVES >> RUN.DISKDRIVES
