#!/bin/sh

file=$1

i=0
while [ 1 = 1 ];
  do
  blkstart=`expr $i '*' 128`;
  timestart=`expr $blkstart + 1`;
  msstart=`expr $blkstart + 2`;
  nibblestart=`expr $i '*' 512 + 15`;
  blk=`dd if=$file bs=4 skip=$blkstart count=1 2>/dev/null | /usr/bin/hexdump -f ~m4/bin/TIMEDUMP`;
  if [ "$blk" == '' ]; then exit 0; fi;
  time=`dd if=$file bs=4 skip=$timestart count=1 2>/dev/null | /usr/bin/hexdump -f ~m4/bin/TIMEDUMP`;
  ms=`dd if=$file bs=4 skip=$msstart count=1 2>/dev/null | /usr/bin/hexdump -f ~m4/bin/TIMEDUMP`;
  nibble=`dd if=$file bs=1 skip=$nibblestart count=1 2>/dev/null | /usr/bin/hexdump -f ~m4/bin/TIMEDUMP`;
  nibble=`expr $nibble / 16` ;
  ctime=`/home/m4/bin/CTIME $time`;
#  echo "block=" $blk " time=" $time " ctime=" $ctime " ms=" $ms ;
  printf "block=%d  nibble=%d time=%d  ctime=%s  ms=%d\n" $blk $nibble $time "$ctime" $ms ;
  i=`expr $i + 1`;
done
