#!/bin/sh

make clean
make

# Create a sed-able script of the disk names and sizes of the disks.
rm -f DISKDRIVES
./GETDISKS ;

# Set to 100mb
limit=`expr 100 '*' 1024 '*' 1024`

# Set the nibble for different patterns.
p=1

while [ "$p" -lt 1000 ]; do
    echo -n "Pass $p " ; date;
    n=0 ;
    while [ "$n" -lt 16 ]; do
	echo -n "Pass $p nibble $n " ; date;
# Remove left over patterns.
	rm -f DISK.sd* ;
# Create script to create the patterns.
	rm -f RUN.DISKDRIVES ;
	echo "#!/bin/sh -x" >> RUN.DISKDRIVES ;
	./DISKS $n ;
	echo "wait" >> RUN.DISKDRIVES ;
	echo "echo DONE with pattern creation" >> RUN.DISKDRIVES ;
	chmod u+x RUN.DISKDRIVES ;
# Create the patterns on local disk.
	./RUN.DISKDRIVES ;
# Write the output in 2mb chunks.
	echo -n 'Writing pattern to vdisks ' ; date ;
	for i in DISK.sd* ; do
	    d=`expr substr $i 6 3` ;
	    echo "dd if=$i of=/dev/$d bs=2097152" ;
	    dd if=$i of=/dev/$d bs=2097152 &
	done ;
	wait ;
# Now compare the output with original.
	echo -n 'Comparing patterns to vdisks ' ; date ;
	for i in DISK.sd* ; do
	    d=`expr substr $i 6 3` ;
	    echo "cmp -n $limit $i /dev/$d" ;
	    (cmp -n $limit $i /dev/$d || kill -1 $$) &
	done ;
	wait ;
	n=`expr $n + 1` ;
    done ;
    p=`expr $p + 1` ;
done
