#!/bin/bash
#
# Example ./DO3 10.64.100.93 15 AAA
#
if [ -z "$1" -o -z "$2" -o -z "$3" -o \! -z "$4" ]; then
  echo 'Usage: CONTROLLER_IP PDISK FILE'
  echo 'Example: 10.64.100.93 15 AAA'
  exit 1
fi

CONTROLLER_IP=$1
PDISK=$2
FILE=$3

make

./GET.SDA ${CONTROLLER_IP} ${PDISK} ${FILE}
./FIX.SDA ${CONTROLLER_IP} ${PDISK} ${FILE}
./PUT.SDA ${CONTROLLER_IP} ${PDISK} ${FILE}

ls -l ${FILE}*

echo "Done moving and changing pdisk ${PDISK}'s boot partition."
