#!/bin/bash -x
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
#-----------------------------------------------------------------------------
d="/mnt/172.22.14.116/cifs_v2/4096-pa"
s="/mnt/SMB-Server-2019.ad.parsec.lab/m4-v1/4096-pa"
#-----------------------------------------------------------------------------
SA=`getfattr -n system.cifs_acl -e hex -- ${s} | tail -n +2 | sed -e 's/^.*=//' || true`
echo ${SA} >SA

DA=`getfattr -n system.cifs_acl -e hex -- ${d} | tail -n +2 | sed -e 's/^.*=//' || true`
echo ${DA} >DA

setfattr -n system.cifs_acl -v ${SA} -- ${d} || true

DA2=`getfattr -n system.cifs_acl -e hex -- ${d} | tail -n +2 | sed -e 's/^.*=//' || true`
echo ${DA2} >DA2
#-----------------------------------------------------------------------------
exit 0
#-----------------------------------------------------------------------------
