#!/bin/bash -x
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
#-----------------------------------------------------------------------------
TIMEFORMAT='real %R sec  user %U sec  system %S sec - %%%P CPU usage'
#-----------------------------------------------------------------------------
f=$1                        # File to copy
if [ "$f" = '' ]; then
    echo "Need a file name to copy."
    exit 1
fi
if [ "$2" != '' ]; then
    echo "Only does one file at a time."
    exit 1
fi
#-----------------------------------------------------------------------------
getfattr -n system.cifs_acl -e hex -- "${f}"
getfattr -n user.cifs.creationtime -e hex -- "${f}"
getfattr -n user.cifs.dosattrib -e hex -- "${f}"
getfattr -n user.cifs.getfsattr -e hex -- "${f}"
getfattr -d -e hex -- "${f}"
#-----------------------------------------------------------------------------
getcifsacl $f
#-----------------------------------------------------------------------------
# For smb version > 2.0
smbinfo fileallinfo $f          # FileAllInfo
smbinfo filefsfullsizeinfo $f   # FileFsFullSizeInfo
smbinfo fsctl-getobjid $f       # objectid of file and GUID
smbinfo getcompression $f       # compression setting
smbinfo list-snapshots $f       # List previous backup versions
smbinfo quota $f                # quota
smbinfo secdesc $f              # security descriptor
smbinfo keys $f                 # decryption
#-----------------------------------------------------------------------------
