#!/bin/bash -ex
#-----------------------------------------------------------------------------
export TIMEFORMAT='real %R sec  user %U sec  system %S sec - %%%P CPU usage'
#-----------------------------------------------------------------------------
export KEEP_FLAGS='-o ro,nosuid,nodev,noexec,noatime,rsize=65536,wsize=65536,namlen=255,soft,proto=tcp,timeo=600,retrans=2,sec=sys,mountproto=tcp,local_lock=none'

#-----------------------------------------------------------------------------
logger "cleanup umount"
time umount /mnt/m4_bigdst1 || true
#-----------------------------------------------------------------------------
sleep 1
mkdir -p /mnt/m4_bigdst1
logger "starting mount"

mount -t nfs ${KEEP_FLAGS} 192.168.14.186:/vol/m4_bigdst1 /mnt/m4_bigdst1
#-----------------------------------------------------------------------------
sleep 1
cp /var/log/messages /var/log/SAVE/messages.1
#-----------------------------------------------------------------------------
# Only do a subset -- i.e. not the two digit directories.
export FILES=`echo /mnt/m4_bigdst1/*_files/[0123456789]`
#-----------------------------------------------------------------------------
logger "starting finds"
date

for i in $FILES; do
   find $i -size 0 &
done

time wait
date
#-----------------------------------------------------------------------------
logger "starting unmount"
# logger "starting unmount - see if multiple make it go faster"
time umount /mnt/m4_bigdst1 &
# time umount /mnt/m4_bigdst1 &
# time umount /mnt/m4_bigdst1 &
# time umount /mnt/m4_bigdst1 &
# time umount /mnt/m4_bigdst1 &
time wait
date
#-----------------------------------------------------------------------------
logger "Done with test with 1 umount."
# logger "Done with test with 5 umount's."
#-----------------------------------------------------------------------------
cp /var/log/messages /var/log/SAVE/messages.2
#-----------------------------------------------------------------------------
exit 0
