#!/bin/bash -ex
SRC_ISCSI='172.22.14.103'
IQN='iqn.1992-08.com.netapp:sn.2014308373:vf.bd100a8b-1422-4a78-b401-0254bf0529d1'
# CONNECTIONS=2
CONNECTIONS=1
#-----------------------------------------------------------------------------
see_iscsi()
{
    iscsiadm -m discovery || true
    iscsiadm -m node || true
    iscsiadm -m session || true
}
#-----------------------------------------------------------------------------
iscsiadm -m discovery -t st -p ${SRC_ISCSI}

IQN=`iscsiadm -m node | head -n 1 | awk '{print $2}'`

iscsiadm -m node -T ${IQN} -portal ${SRC_ISCSI} --op=update --name=node.session.nr_sessions --value=${CONNECTIONS} || true

iscsiadm -m node -T ${IQN} --portal ${SRC_ISCSI} --login
see_iscsi

#-----------------------------------------------------------------------------
echo Done with $0
exit 0
#-----------------------------------------------------------------------------





iscsiadm --mode discoverydb --type sendtargets --portal 172.22.14.103 --discover

#-- iscsiadm --mode node --targetname iqn.1992-08.com.netapp:sn.2014308373:vf.c0179925-0acc-46cd-80fe-68f9ec82c743 --portal 172.22.14.103 --name=node.discovery_address

#-- iscsiadm --mode node --targetname iqn.1992-08.com.netapp:sn.2014308373:vf.c0179925-0acc-46cd-80fe-68f9ec82c743

iscsiadm --mode node --targetname iqn.1992-08.com.netapp:sn.2014308373:vf.c0179925-0acc-46cd-80fe-68f9ec82c743 --portal 172.22.14.103:3260 --login

iscsiadm --mode node --targetname iqn.1992-08.com.netapp:sn.2014308373:vf.c0179925-0acc-46cd-80fe-68f9ec82c743 --portal 172.22.14.103:3260 --logout

j
