#!/bin/bash -ex
IP_1a='172.22.14.103' IQN_1a='iqn.1992-08.com.netapp:sn.2014308373:vf.c0179925-0acc-46cd-80fe-68f9ec82c743'
IP_1b='192.168.14.103' IQN_1b='iqn.1992-08.com.netapp:sn.2014308373:vf.c0179925-0acc-46cd-80fe-68f9ec82c743'
IP_2='192.168.14.180' IQN_2='iqn.1992-08.com.netapp:sn.2014308373:vf.f8159f29-112c-4755-807a-1f6222fdd1c5'
IP_3='192.168.14.186' IQN_3='iqn.1992-08.com.netapp:sn.2014308373:vf.bd100a8b-1422-4a78-b401-0254bf0529d1'

# CONNECTIONS=2
CONNECTIONS=1
#-----------------------------------------------------------------------------
see_iscsi()
{
    iscsiadm -m discovery || true
    iscsiadm -m node || true
    iscsiadm -m session || true
}
#-----------------------------------------------------------------------------
attach_iscsi()
{
    iscsiadm -m discovery -t st -p $1 || true
    if [ "${CONNECTIONS}" != '1' ]; then
	iscsiadm -m node -T $2 -portal $1 --op=update --name=node.session.nr_sessions --value=${CONNECTIONS} || true
    fi
    iscsiadm -m node -T $2 --portal $1 --login || true
}

#-----------------------------------------------------------------------------
attach_iscsi ${IP_1a} ${IQN_1a}
attach_iscsi ${IP_1b} ${IQN_1b}
attach_iscsi ${IP_2} ${IQN_2}
attach_iscsi ${IP_3} ${IQN_3}
#-----------------------------------------------------------------------------
see_iscsi
#-----------------------------------------------------------------------------
echo Done with $0
exit 0
#-----------------------------------------------------------------------------



IP_1a='172.22.14.103' IQN_1a='iqn.1992-08.com.netapp:sn.2014308373:vf.c0179925-0acc-46cd-80fe-68f9ec82c743'
IP_1b='192.168.14.103' IQN_1b='iqn.1992-08.com.netapp:sn.2014308373:vf.c0179925-0acc-46cd-80fe-68f9ec82c743'
IP_2='192.168.14.180' IQN_2='iqn.1992-08.com.netapp:sn.2014308373:vf.f8159f29-112c-4755-807a-1f6222fdd1c5'
IP_3='192.168.14.186' IQN_3='iqn.1992-08.com.netapp:sn.2014308373:vf.bd100a8b-1422-4a78-b401-0254bf0529d1'

