#!/bin/bash -x

mkdir -p /mnt/m4_bigdst1
mount -t nfs 192.168.15.186:/vol/m4_bigdst1/ /mnt/m4_bigdst1

mkdir -p /mnt/m4_bigdst2
mount -t nfs 192.168.15.186:/vol/m4_bigdst2/ /mnt/m4_bigdst2

mkdir -p /mnt/m4_bigdst3
mount -t nfs 192.168.15.186:/vol/m4_bigdst3/ /mnt/m4_bigdst3

mkdir -p /mnt/m4_bigdst4
mount -t nfs 192.168.15.186:/vol/m4_bigdst4/ /mnt/m4_bigdst4

mkdir -p /mnt/m4_nfs_v1
mount -t nfs 192.168.15.186:/vol/m4_nfs_v1/ /mnt/m4_nfs_v1

mkdir -p /mnt/m4_nfs_v2
mount -t nfs 192.168.15.186:/vol/m4_nfs_v2/ /mnt/m4_nfs_v2
