#!/bin/bash
O=`vmstat -f | awk '{print $1}'`
S=`date +%s`
#--    slabtop -o | head -n 9 | tail -n 2
while true; do
    date
    E=`date +%s`
    free -m | egrep 'Mem|Swap'
    numactl --hardware | grep free
    slabtop -o -s c | sed -n -e '4p' -e '8,9p'
    N=`vmstat -f | awk '{print $1}'`
    let T=$E-$S
    if [ $T -le 0 ]; then let T=1; fi
    let F=($N-$O)/$T
    S=$E
    O=$N
    echo "forks/sec $F"
    smem -wk
#--    smem -s swap -r -p 2>/dev/null | head -n 6
    echo "----------------------------------------------"
    sleep 5
done
#-----------------------------------------------------------------------------
