#!/bin/bash -ex
M=../musicomp2abc
rm -f [0123456789]*.v

# Reference of what it should look like.
${M} --vertical KEYS.gcs 001-k-c-major-0.v

# Check errors are found everywhere.
#- ${M} --vertical KEYS.gcs 000-k-c-major-xpose.v --xpose 'error'			|| true
#- ${M} --vertical KEYS.gcs 000-k-c-major-xpose.v --xpose '1 error'			|| true
#- ${M} --vertical KEYS.gcs 000-k-c-major-xpose.v --xpose 'error c'			|| true
#- ${M} --vertical KEYS.gcs 000-k-c-major-xpose.v --xpose 'error 0 c'			|| true
#- ${M} --vertical KEYS.gcs 000-k-c-major-xpose.v --xpose '1 error c'			|| true
#- ${M} --vertical KEYS.gcs 000-k-c-major-xpose.v --xpose '1 0 error'			|| true
#- ${M} --vertical KEYS.gcs 000-k-c-major-xpose.v --xpose '1 0 error major'		|| true
#- ${M} --vertical KEYS.gcs 000-k-c-major-xpose.v --xpose '1 0 c error'		|| true

# Manually check all formats.
${M} --vertical KEYS.gcs 002-k-c-major-xpose.v --xpose 'c'
${M} --vertical KEYS.gcs 003-k-c-major-xpose.v --xpose '0'
${M} --vertical KEYS.gcs 004-k-c-major-xpose.v --xpose '1..8 c'
${M} --vertical KEYS.gcs 005-k-c-major-xpose.v --xpose '1..8 0'
${M} --vertical KEYS.gcs 006-k-c-major-xpose.v --xpose '1..8 0 c'
${M} --vertical KEYS.gcs 007-k-c-major-xpose.v --xpose '1..8 0 c major'

let c=100	|| true

run_vert()
{
    K="$*"
    ${M} --vertical KEYS.gcs ${c}-k-${K}-major-1.v --xpose "${K}"
    let c=$c+1
    ${M} --vertical KEYS.gcs ${c}-k-${K}-major-2.v --xpose "1..8 ${K}"
    let c=$c+1
    ${M} --vertical KEYS.gcs ${c}-k-${K}-major-3.v --xpose "1..8 0 ${K}"
    let c=$c+1
    ${M} --vertical KEYS.gcs ${c}-k-${K}-major-4.v --xpose "1..8 0 ${K} major"
    # Align at 10s digits.
    let c=$c+9
}

# The 4 xpose for 'c', which should look sort of like 01-k-c-major-0.v.
run_vert 'c'
# The 4 xpose for 'cn', which should look sort of like 01-k-c-major-0.v. (Do sharps, not flats.)
run_vert 'cn'

# Flats (1 through 7)
run_vert 'f'
run_vert 'b-'
run_vert 'e-'
run_vert 'a-'
run_vert 'd-'
run_vert 'g-'
run_vert 'c-'

# Sharps (1 through 7)
run_vert 'g'
run_vert 'd'
run_vert 'a'
run_vert 'e'
run_vert 'b'
run_vert 'f+'
run_vert 'c+'

exit 0
