#!/bin/bash -ex
M=~/musicomp2abc/musicomp2abc
FILE=p

rm -f [0-9]*.v
rm -f [0-9]*.csv

# Reference of what it should look like.
${M} --vertical ${FILE}.gcs 0001-k_b-_major.v
${M} --midi1csv ${FILE}.gcs 0001-k_b-_major.csv

# Manually check all formats.
${M} --vertical ${FILE}.gcs 0002-k_b-_major-xpose.v --xpose 'b-'
${M} --vertical ${FILE}.gcs 0003-k_b-_major-xpose.v --xpose '0'
${M} --vertical ${FILE}.gcs 0004-k_b-_major-xpose.v --xpose '1..8 b-'
${M} --vertical ${FILE}.gcs 0005-k_b-_major-xpose.v --xpose '1..8 0'
${M} --vertical ${FILE}.gcs 0006-k_b-_major-xpose.v --xpose '1..8 0 b-'
${M} --vertical ${FILE}.gcs 0007-k_b-_major-xpose.v --xpose '1..8 0 b- major'

${M} --midi1csv ${FILE}.gcs 0002-k_b-_major-xpose.csv --xpose 'b-'
${M} --midi1csv ${FILE}.gcs 0003-k_b-_major-xpose.csv --xpose '0'
${M} --midi1csv ${FILE}.gcs 0004-k_b-_major-xpose.csv --xpose '1..8 b-'
${M} --midi1csv ${FILE}.gcs 0005-k_b-_major-xpose.csv --xpose '1..8 0'
${M} --midi1csv ${FILE}.gcs 0006-k_b-_major-xpose.csv --xpose '1..8 0 b-'
${M} --midi1csv ${FILE}.gcs 0007-k_b-_major-xpose.csv --xpose '1..8 0 b- major'

let c=1000	|| true

run_vert()
{
    K="$*"
    ${M} --vertical ${FILE}.gcs ${c}-k-${K}-major-1.v --xpose "${K}"
    ${M} --midi1csv ${FILE}.gcs ${c}-k-${K}-major-1.csv --xpose "${K}"
    let c=$c+1 	|| true
    ${M} --vertical ${FILE}.gcs ${c}-k-${K}-major-2.v --xpose "1..8 ${K}"
    ${M} --midi1csv ${FILE}.gcs ${c}-k-${K}-major-2.csv --xpose "1..8 ${K}"
    let c=$c+1 	|| true
    ${M} --vertical ${FILE}.gcs ${c}-k-${K}-major-3.v --xpose "1..8 0 ${K}"
    ${M} --midi1csv ${FILE}.gcs ${c}-k-${K}-major-3.csv --xpose "1..8 0 ${K}"
    let c=$c+1 	|| true
    ${M} --vertical ${FILE}.gcs ${c}-k-${K}-major-4.v --xpose "1..8 0 ${K} major"
    ${M} --midi1csv ${FILE}.gcs ${c}-k-${K}-major-4.csv --xpose "1..8 0 ${K} major"
    # Align at 10s digits.
    let c=$c+7 	|| true
}

# The 4 xpose for 'c', which should have b- for all of those b-'s from key..
run_vert 'c'
# The 4 xpose for 'cn', which should should have a+ for all of those b-'s from key.
run_vert 'cn'

# Flats (1 through 7)
run_vert 'f'
run_vert 'b-'
run_vert 'e-'
run_vert 'a-'
run_vert 'd-'
run_vert 'g-'
run_vert 'c-'

# Sharps (1 through 7)
run_vert 'g'
run_vert 'd'
run_vert 'a'
run_vert 'e'
run_vert 'b'
run_vert 'f+'
run_vert 'c+'

exit 0
