#!/bin/bash -ex
cd ../rhel-kernel/

rpm --force -Uvh RPMS/x86_64/kernel-headers-4.9.91-2018.04.03.lightspeed.x86_64.rpm

rpm --force -Uvh RPMS/x86_64/kernel-4.9.91-2018.04.03.lightspeed.x86_64.rpm
rpm --force -Uvh RPMS/x86_64/kernel-devel-4.9.91-2018.04.03.lightspeed.x86_64.rpm

# rpm --force -Uvh  RPMS/x86_64/kernel-tools-3.10.0-693.11.1.el7.lightspeed.x86_64.rpm
# rpm --force -Uvh  RPMS/x86_64/kernel-tools-libs-3.10.0-693.11.1.el7.lightspeed.x86_64.rpm
# rpm --force -Uvh  RPMS/x86_64/kernel-tools-libs-devel-3.10.0-693.11.1.el7.lightspeed.x86_64.rpm

# Probably should build and install the debuginfo and debug rpm's for kdump. Just "don't know for sure" yet.
