#!/bin/sh
# \
exec tclsh "$0" ${1+"$@"}
package require Expect

#
#
# Script to configure 1 or more ISEs. Tailored for use with
# Nitrogen.
#
# Usage: ise_add_datapac [-D] [-C] [-l] [-d <dsc>] [-v <n>] [-r <x>] [-s <s>] [-p <com port>] [-i <ip address>]
#
# Where:
#  -D  Debug
#    Show the dialog with the ISE.
#
#  -C  Clean
#    Remove all volumes and hosts from ISE (can be combined
#    with options to subsequenetly create new volumes/hosts.)
#
#  -l  List the available storage space on the ISE for
#    each disk pack and raid type.
#
#  -d <dsc>
#    Create a host entry that accurately reflects
#    the set of all possible back-end WWNs required
#    to communicate with the specified DSC number.
#
#  -v <n>  
#    Create <n> volumes per ISE. May not handle odd
#    numbers optimally. Given an even number, will
#    create n/2 volumes per data pack; attempting to
#    equally divide the available capacity between
#    the volumes. The last volume on each data pack
#    may be upto (n-1) GB larger than the others, due
#    to the remainder when dividing total capacity by n.
#
#    If both -v and -d options are specified, the volumes
#    are presented to the specified DSC.
#
#  -r <x>  
#    Specify the RAID type of all volumes created/listed by
#    this command. Default is 5. Only other reasonable
#    option is 1.
#
#  -s <s>  
#    Limit the size of created volumes to <s> GB instead
#    of (capacity/n).
#
#  -p <com port>  
#    Specify the com port used to communicate to ISE.
#    By default, the script will use com port 1.
#
#  -i <ip address>     
#    Specify the IP address for the ISE.
#
# Typical command line to freshly initialise an ISE with 4 RAID5
# volumes per data pack for use with DSC 10234 would be:
#
#  ise_add_datapac -d 10234 -C -v 8 -p 2 -i 10.64.102.150 
#
#
# This script was tested using the Windows version of Expect  
# (ActiveTCL version 8.4.17.0 see www.activestate.com).
#

set raid 5
set cache "back"
log_user 0

set format "%a %b %d %X %Z %Y"
#set vol_prefix "Volume_"
#set host_prefix "DSC_"
set vol_prefix "V"
set host_prefix "D"
set com_port 1
set netmask "255.255.0.0"
set ip_address_1 "172.16.1.2"
set ip_address_2 "172.16.1.3"
set datapac_1_vols 0
set datapac_2_vols 0  
set datapac_1_pool 0 
set datapac_2_pool 0 
set pool_id 0
# regular expression representing the ISE prompt.  Either "seaSH> " or "root:> "
set ise_prompt "(seaSH|root:|root|oem:)> "


proc usage {} {
  puts "Usage: ise_add_datapac \[-D] \[-C] \[-l] \[-d <dsc>] \[-v <n>] \[-r <x>] \[-s <s>] \[-p <com port>] \[-i <ip address>]"
  exit 1
}

source "getopts"

#
# Given a dsc #, return a list of all the BE WWNs used.
#
proc dsc2wwn { dsc } {
  set hex [format "%02X%02X%01X" [expr [expr $dsc >> 12] & 0xff] [expr [expr $dsc >> 4] & 0xff] [expr $dsc & 0xf]]
  foreach dcn {0 1} {
    foreach port {0 1 2 3} {
      lappend wwn [format "21A%d00D0B2$hex%d" $port $dcn]
    }
  }

  return $wwn
}


#
# Log into an ISE and start seash.
#
proc login {} {
  global com_port
  global ise_prompt

  set serial [open com$com_port: w+]

  fconfigure $serial -mode "115200,n,8,1" -buffering none -blocking 0

  spawn -open $serial

  send "\r"

  expect {
    "ise login: "  {
      send "root\r"
    }
  }
  sleep 15
  expect {
    "\# "  {
      # send "echo '6 6 6 6' > /proc/sys/kernel/printk\r"
	  # sleep 2
	  # send "cat /proc/sys/kernel/printk\r"
      sleep 2
      send "nseash\r"
    }
  }

  expect {
    -re $ise_prompt  {
      return $spawn_id
    }
    timeout {
      exit 1
    }
    eof {
      exit 1
    }
  }
}

#
# Log out of an ISE.
#
proc logout { spawn_id } {

  #
  # log out of an ISE.
  #
 
  send "exit\r"
  sleep 5
  expect {
    "\# "  {
     # send "echo '4 2 1 1' > /proc/sys/kernel/printk\r"
	 # sleep 2
	 # send "cat /proc/sys/kernel/printk\r"
	 sleep 2
	 send "exit\r"
    }
    timeout {
      exit 1
    }
    eof {
      exit 1
    }
  }
}

#
# config_network -  Configure network settings.
#
proc config_network { spawn_id } {
  global netmask 
  global ip_address_1 
  global ip_address_2 
  global ise_prompt

  #
  # Disables DHCP
  #

  send "configure --dhcp=Disable\r"

  expect {
    -re $ise_prompt {}
    timeout { exit 1 }
    eof  { exit 1}
  }

  #
  # Set netmask 
  #

  send "configure --netmask1=$netmask\r"

  expect {
    -re $ise_prompt {}
    timeout { exit 1 }
    eof  { exit 1}
  }

  send "configure --netmask2=$netmask\r"

  expect {
    -re $ise_prompt {}
    timeout { exit 1 }
    eof  { exit 1}
  }

  #
  # Set ip addresses 
  #

  send "configure --ipaddress1=$ip_address_1\r"

  expect {
    -re $ise_prompt {}
    timeout { exit 1 }
    eof  { exit 1}
  }

  send "configure --ipaddress2=$ip_address_2\r"

  expect {
    -re $ise_prompt {}
    timeout { exit 1 }
    eof  { exit 1}
  }
}

#
# list_space -  fill in the $space($pool,$raid) member with the
#    available space on the ISE.
#
proc list_space { spawn_id } {
  global space
  global pools
  global datapac_id
  global ise_prompt

  send "show pool\r"
  expect {
    -re "Pool (\[12]) " {
          set pool $expect_out(1,string)
            lappend pools $expect_out(1,string)
          exp_continue
        }
    -re "(DataPac-1)" {
            set datapac_id 1
          exp_continue
        }
    -re "(DataPac-2)" {
            set datapac_id 2
          exp_continue
        }
    -re "Raid (\[0156]) : (\[0123456789]+) +GB    " {
          set raid_type $expect_out(1,string)
          set size $expect_out(2,string)
          set space($pool,$raid_type) $size
          exp_continue
        }
    -re $ise_prompt {
          return
        }
    timeout    { exit 1 }
    eof    { exit 1}
  }
}

#
# used_check -  Check which DataPac has volumes on it already.
#    available space on the ISE.
#
proc used_check { spawn_id } {
  global datapac_id
  global pool
  global datapac_1_vols
  global datapac_2_vols
  global datapac_1_pool
  global datapac_2_pool
  global pool_id 
  global ise_prompt

  send "show pool\r"
  expect {
    -re "Pool 1" {
          set pool_id 1
          exp_continue
        }
    -re "Pool 2" {
          set pool_id 2
          exp_continue
        }
    -re "(DataPac-1)" {
            set datapac_id 1
          exp_continue
        }
    -re "(DataPac-2)" {
            set datapac_id 2
          exp_continue
        }
    -re "(of Volumes : 4)" {
            if {$datapac_id == 1} then {
              set datapac_1_vols $datapac_id
               set datapac_1_pool $pool_id
            } elseif {$datapac_id == 2} then {
              set datapac_2_vols $datapac_id
               set datapac_2_pool $pool_id
          } 
          exp_continue
        }
    -re $ise_prompt {
          return
        }
    timeout    { exit 1 }
    eof    { exit 1}
  }
}

#
# datapac_add -  Send the add --datapac# command to the ISE.
#                    Then continue to check the add status until we see everything is online
#                Wait for no longer than 50 minutes before timing out
#
proc datapac_add { spawn_id } {
  global ise_prompt
 
  set x 0
  # Send the command to both datapacs.  Doesn't matter if already configured it will show on-line.
  puts "                   \n\n*****************************************************************\n"
  puts "                   ** Please Wait.... Paused for 50 seconds to allow add to start **\n"
  puts "                   *****************************************************************\n\n\r"

  send "\r"
  send "add --datapac1\r"
  send "add --datapac2\r"
  puts "\n ********************************************************************************************************************\n"
  puts " ******** Please wait..  Datapac add has started.  This could take 20-40 minutes depending on the drives size *******\n"
  puts " ********************************************************************************************************************\n\n\r"
  expect *
  send "show datapac\r"
  expect *
    expect {
        -re "datapac 2" {
        sleep 10
        }
        }

  for {set j 1} {$j <= 301} { incr j} {
    expect *
    send "add --status\r"
    expect {
       -exact "\online" {
             set j 302
			 puts "\n\n                   *************************************************************\n"
                         puts "                   ***** OK, Datapacs are Done..  Continue configuration *****\n"
			 puts "                   *************************************************************\n"

                exp_continue
           }
       -ex $ise_prompt {
           }
    }
    if {$j == 50} {
      puts "\n\n                   *******************************************************************************************\n"
      puts "                   ******** There is a problem.  Add Datapac did not complete within a reasonable time *******\n"
      puts "                   *******************************************************************************************\n"
      exit 3
    }
    puts "\n                   ***********************************************************************\n"
    puts "                   ******** Please continue to wait ....  DO NOT STOP THIS PROCESS *******\n"
    puts "                   *** NOTE:  This may take from 20-40 minutes.  Timeout at 50 Minutes ***\n"
    puts "                   ***********************************************************************\n"
    expect *
  }
  send "\r"
  sleep 50
  expect {
     -re $ise_prompt {
          return spawn_id
         }
  }
}

#
# create_vol -  Create a volume of the specified size on the specified
#    pool/data pack. Name will be "$vol_prefix$index".
#    Does not present it to anyone.
#
proc create_vol { spawn_id index size pool } {
  global vol_prefix
  global raid
  global cache
  global env
  global format
  global ise_prompt

  set resend 1

  set vol_size $size

  while { $resend > 0 } {

    set resend 0

    send "create --volume=$vol_prefix$index --size=$vol_size --raid$raid --pool$pool --write-$cache\r"
	sleep 30
    expect {
      "Creation started successfully" {
              expect {
                -re $ise_prompt {}
                timeout { set resend 1 }
                eof  { set resend 1}
              }
            }
      "Creation ERROR: Error code = 35" {
        set resend 1
      }
      timeout { set resend 1 }
      eof  { set resend 1 }
    }

    if { $resend > 0 } {
      set vol_size [expr $vol_size - 1]
      puts "\nError detected, retrying with volume size $vol_size\n"
    } else {
      if { $vol_size > 1460 } {
        #
        # Pause here because a volume could
        # take up to 18 seconds to become real enough to present.
        #
        puts "\nWaiting 20 seconds for volume to become real.\n"
        sleep 20
      }
    }
  }
}

#
# create_host -  Create q host with 8 WWNS that match the gamut of possible
#    WWNs used by the specified DSC. Does not present any volumes
#    to this host.
#
# Note: over serial connection, the one create command with all WWN caused
#       an overflow.  The workaround was to create for one WWN the modify.
#
proc create_host { spawn_id dsc } {
  global host_prefix
  global env
  global format
  global ise_prompt

  set created 0

  set wwn_list [dsc2wwn $dsc]
  
  foreach wwn $wwn_list {

    if {$created < 1} then {

      send "create --host=$host_prefix$dsc --linux $wwn\r"

      expect {
        "Host created" {
              expect {
                -re $ise_prompt {}
                timeout { exit 1 }
                eof  { exit 1}
              }
            }
        timeout { exit 1 }
        eof  { exit 1}
      }

      set created 1

    } else {

      send "modify --host=$host_prefix$dsc --add=$wwn\r"

      expect {
        "Adding hba $wwn" {
              expect {
                -re $ise_prompt {}
                timeout { exit 1 }
                eof  { exit 1}
              }
            }
        timeout { exit 1 }
        eof  { exit 1}
      }
    }
  }
}

#
# list_hosts -  Return a list of all hosts configured on this ISE.
#    A precursor to removing them.
#
proc list_hosts { spawn_id } {
  global ise_prompt

  set host_list {}

  send "show hosts\r"

  expect {
    -re "(\[A-Za-z0-9_\\-]\[A-Za-z0-9_\\- ]*): \\(\[A-Za-z]+\\)" {
          lappend host_list $expect_out(1,string)
          exp_continue
      }

    -re $ise_prompt { return $host_list }
    timeout { exit 1 }
    eof  { exit 1}
  }
}

#
# list_vols -  Return a list of all volumes configured on this ISE.
#    A precursor to removing them.
#
proc list_vols { spawn_id } {
  global vol_list
  global ise_prompt

  set vol_list {}

  send "show volumes\r"

  expect {
    -re "(\[A-Za-z0-9_\\-]\[A-Za-z0-9_\\- ]*): \\(Pool" {
        lappend vol_list $expect_out(1,string)
        exp_continue
      }

    -re $ise_prompt { return $vol_list }
    timeout { exit 1 }
    eof  { exit 1}
  }
}

#
# unpresent -  Unpresent all volumes from a list of hosts or
#    hosts from a list of volumes.
#
#    $type must be one of "host" or "volume", and
#    the list must match appropriately.
#
proc unpresent { spawn_id type list } {
  global timeout
  global ise_prompt

  set saved_timeout $timeout
  set timeout 30
  foreach item $list {
    send "unpresent --$type=$item --all\r"

    expect {
      -re $ise_prompt { continue }
      timeout { exit 1 }
      eof  { exit 1}
    }
  }
  set timeout $saved_timeout
}

#
# present -  Present the specified volume to the specified host
#    using the specified LUN.
#
proc present { spawn_id host volume lun } {
  global ise_prompt

  send "present --volume=$volume $host:$lun\r"

  expect {
    -re $ise_prompt { return }
    timeout { exit 1 }
    eof  { exit 1}
  }
}

#
# delete -  Delete a list of either hosts or volumes,
#    depending on $type. $type must be one of "host"
#    or "volume".
#
proc delete { spawn_id type list } {
  global ise_prompt

  foreach item $list {
    send "delete --$type=$item\r"

    expect {
      "\\(y/N\\): " {
        send "y"
        exp_continue
      }
      -re $ise_prompt { continue }
      timeout { exit 1 }
      eof  { exit 1}
    }
  }
}

#
# Prompt - Create the user prompt when an existing configuration is detected.
#
proc Prompt {msg} {
  global mode widgets
  set mode CMDLINE
  switch $mode {
    CMDLINE {
      puts -nonewline "$msg (continue/no): "
      set answ [gets stdin]
    }
  }
  return $answ
}



#
# session -  Open a connection to the ISE, and do our
#    business.
#
proc session {} {
  global options
  global space
  global raid
  global ip_address_1 
  global ip_address_2
  global pools
  global datapac_id 
  global datapac_1_vols
  global datapac_2_vols
  global datapac_1_pool
  global datapac_2_pool
  global pool
  global datapac_to_use
  global vol_type 
  global vol_list
  global pool_id

  set spawn_id [login]

  #
  # Give the user a warning message before proceeding.
  #
  set answ [Prompt "\n\n\n\n***********************************************************\n\n\n******************* Add NEW Datapac *******************\n\n\n***********************************************************\n\n\n\nYou are about to add a NEW DataPac to the system.\n\n\n\nAre you sure you want to continue ?"]
  switch $answ {
    continue {# continue configuration}
    no {exit 1}
  }
  # Verify the correct responce was given, otherwise exit.
  if {$answ ne "continue"} {
    exit 1
  }

  #
  # Add the new ISE and check initalization status until complete.
  #

  datapac_add $spawn_id
  sleep 15
  

  #
  # Check for an existing configuration.  Use the volumes list to determine what already exists. 
  #
  # add second run
  set vols [list_vols $spawn_id]

  puts "\nVolumes = $vols\n"
  
  if {$vols eq "V1 V3 V5 V7"} then {
    set vol_type "even"
  } elseif {$vols eq "V2 V4 V6 V8"} then {
    set vol_type "odd" 
  } else {
    set vol_type "error"
  }

  # 
  # Get the volumes and find out what Datapac it is on before we continue.
  #
  used_check $spawn_id

  puts "\nVolumes on Datapac 1 = $datapac_1_vols\n"
  puts "\nVolumes on Datapac 2 = $datapac_2_vols\n"
  puts "\nVolumes type to use = $vol_type\n"
  puts "\nPool ID = $pool_id\n"
  puts "\nDatapac pool = $datapac_1_pool\n"
  puts "\nDatapac pool = $datapac_2_pool\n"

  if {$datapac_1_vols != 0 && $datapac_2_vols != 0 } then {
    # Volumes exist on both datapacs error with message
    exit 2
  }

  #
  # Check for what pool and datapac to use.  
  #
  if {$datapac_1_vols == 0} then {
    set pool $pool_id
    set datapac_to_use 1
  } elseif {$datapac_2_vols == 0}     {
    set pool $pool_id
    set datapac_to_use 2
  }


  # Take these out
  puts "\nVolumes on Datapac 1 = $datapac_1_vols\n"
  puts "\nVolumes on Datapac 2 = $datapac_2_vols\n"
  puts "\nVolumes type to use = $vol_type\n"
  puts "\nDataPac vols to be created on = $datapac_to_use\n"
  puts "\nPool that will be used = $pool\n"

  if {$pool == 0} then {
    puts "\n\n\n\n\n\n\n\n\n\ You don't have a NEW Datapac installed\n\n\n"
    exit
  }

  #
  # This should already be done, but does not hurt to run it again.
  #
  if {[info exists options(i)]} then {
    config_network $spawn_id
  }

  list_space $spawn_id

  #
  # Optionally create n volumes on an ISE
  #
  # Work out the size of each volume per data pack, for
  # the specified raid type.
  # Note we will make the last volume slightly larger
  # to take care of rounding errors.
  # Volumes are created as follows:
  #
  #  Name    Pool (datapack)
  #  $vol_prefix_1  1
  #  $vol_prefix_2  2
  #  $vol_prefix_3  1
  #  $vol_prefix_4  2
  #  ....
  #
  if {[info exists options(v)]} then {
    global vol_prefix
    global host_prefix
    set vol_count $options(v)
    global pools
    global datapac_id

    foreach pool $pool {
      set quanta($pool) [expr $space($pool,$raid) / [expr [expr $vol_count + 1] / 2]]
      if {[info exists options(s)]} then {
        set size $options(s)
        if {$quanta($pool) > $size} then {
          set quanta($pool) $size
        }
      }
      set resid($pool) $space($pool,$raid)
    }

    for {set i 1} {$i <= $vol_count} { incr i} {
      # Set the vol_count to 4 and set the odd/even pairs for the new datapac
      # Fix the volume naming
      set vol_count 4
      if {$vol_type eq "odd"} then {
        if {$i == 1} then {
          set vol_nam 1
        }
        if {$i == 2} then {
          set vol_nam 3
        }
        if {$i == 3} then {
          set vol_nam 5
        }
        if {$i == 4} then {
          set vol_nam 7
        }
      } elseif {$vol_type eq "even"} then {
        if {$i == 1} then {
          set vol_nam 2
        }
        if {$i == 2} then {
          set vol_nam 4
        }
        if {$i == 3} then {
          set vol_nam 6
        }
        if {$i == 4} then {
          set vol_nam 8
        }
      }
        
      if {$resid($pool) < [expr $quanta($pool) * 2]} then {
        set size $resid($pool)
      } else {
        set size $quanta($pool)
      }
      create_vol $spawn_id $vol_nam $size $pool
      incr resid($pool) -$size
    }

    if {[info exists options(d)]} then {

      sleep 1

      # Present the volumes 
      for {set j 1} {$j <= $vol_count} { incr j} {
        if {$vol_type eq "odd"} then {
          if {$j == 1} then {
            set vol_nam 1
          }
          if {$j == 2} then {
            set vol_nam 3
          }
          if {$j == 3} then {
            set vol_nam 5
          }
          if {$j == 4} then {
            set vol_nam 7
          }
        } elseif {$vol_type eq "even"} then {
          if {$j == 1} then {
            set vol_nam 2
          }
          if {$j == 2} then {
            set vol_nam 4
          }
          if {$j == 3} then {
            set vol_nam 6
          }
          if {$j == 4} then {
            set vol_nam 8
          }
        }
        present $spawn_id $host_prefix$options(d) $vol_prefix$vol_nam $vol_nam
      }
    }
  }

  logout $spawn_id

  close

  wait
}

set timeout 10

if {[getopts "Dd:lCcr:s:v:p:i:" argv options] > 0} usage

if {[info exists options(r)]} then {
  set raid $options(r)
}

if {[info exists options(p)]} then {
  set com_port $options(p)
}

if {[info exists options(i)]} then {

  #
  # mrc-1 will get the ip address passed in.
  # mrc-2 will get the ip address but the last digit incremented by one.
  # For example:  -i 172.16.1.2
  # mrc-1 = 172.16.1.2
  # mrc-2 - 172.16.1.3
  #
  set ip_address_1 $options(i)

  set ip_nums [split $ip_address_1 "."]

  set last_num [lindex $ip_nums 3]

  set new_num [expr $last_num + 1]

  set ip_address_2 "[lindex $ip_nums 0].[lindex $ip_nums 1].[lindex $ip_nums 2].$new_num" 
}

if {[info exists options(D)]} then {
  log_user 1
}

session

