#!/bin/bash -e

#-----------------------------------------------------------------------------
# ./RM 4 seconds.
#-----------------------------------------------------------------------------
# Tar /mnt/v1 to /mnt/v2.
#  87 seconds	- Default NFS mount options.
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .-
# BAD!		NFS_FLAGS="${NFS_FLAGS},noac"		# ??		++
# 279 seconds
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .-
#. NFS_FLAGS=",soft"
#. NFS_FLAGS="${NFS_FLAGS},timeo=600"
#. NFS_FLAGS="${NFS_FLAGS},retrans=2"
#. NFS_FLAGS="${NFS_FLAGS},rsize=1048576"
#. NFS_FLAGS="${NFS_FLAGS},wsize=1048576"
#. NFS_FLAGS="${NFS_FLAGS},sec=sys"
#. NFS_FLAGS="${NFS_FLAGS},sharecache"
#. NFS_FLAGS="${NFS_FLAGS},lookupcache=none"
#. NFS_FLAGS="${NFS_FLAGS},nofsc"
#. NFS_FLAGS="${NFS_FLAGS},proto=tcp"
#. NFS_FLAGS="${NFS_FLAGS},cto"
#  88 seconds
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .-
# add following...
#. NFS_FLAGS="${NFS_FLAGS},nodev,noexec,nodiratime,noiversion,nomand,norelatime,nostrictatime,nosuid,nouser"
#  86 seconds
#-----------------------------------------------------------------------------
# Export list for 192.168.15.186:
# /vol/m4_nfs_v1   192.168.15.0/24
# /vol/m4_nfs_v2   192.168.15.0/24
#-----------------------------------------------------------------------------
IP="192.168.15.186"
NFS_READ_FLAGS='-o ro'
NFS_WRITE_FLAGS='-o rw'
#-----------------------------------------------------------------------------
NFS_FLAGS=",soft"
NFS_FLAGS="${NFS_FLAGS},timeo=600"
NFS_FLAGS="${NFS_FLAGS},retrans=2"
NFS_FLAGS="${NFS_FLAGS},rsize=1048576"
NFS_FLAGS="${NFS_FLAGS},wsize=1048576"
NFS_FLAGS="${NFS_FLAGS},sec=sys"
NFS_FLAGS="${NFS_FLAGS},sharecache"
NFS_FLAGS="${NFS_FLAGS},lookupcache=none"
NFS_FLAGS="${NFS_FLAGS},nofsc"
NFS_FLAGS="${NFS_FLAGS},proto=tcp"
NFS_FLAGS="${NFS_FLAGS},cto"
#VERYSLOW	 NFS_FLAGS="${NFS_FLAGS},noac"		# ??	VERY SLOW!
#-----------------------------------------------------------------------------
NFS_FLAGS="${NFS_FLAGS},nodev,noexec,nodiratime,noiversion,nomand,norelatime,nostrictatime,nosuid,nouser"
#-----------------------------------------------------------------------------
NFS_READ_FLAGS="${NFS_READ_FLAGS}${NFS_FLAGS}"
NFS_WRITE_FLAGS="${NFS_WRITE_FLAGS}${NFS_FLAGS}"

#-----------------------------------------------------------------------------
mkdir -p /mnt/v1 /mnt/v2
set -x
mount -t nfs ${NFS_READ_FLAGS} ${IP}:/vol/m4_nfs_v1 /mnt/v1
mount -t nfs ${NFS_WRITE_FLAGS} ${IP}:/vol/m4_nfs_v2 /mnt/v2

exit 0
