--blank-lines-after-declarations
--blank-lines-after-procedures
--blank-lines-before-block-comments
--break-after-boolean-operator
--braces-after-if-line
--braces-after-struct-decl-line
--brace-indent0
--blank-lines-after-commas
--comment-indentation49
--declaration-comment-column49
--no-comment-delimiters-on-blank-lines
--cuddle-do-while
--dont-cuddle-else
--continuation-indentation4
--case-indentation4
--else-endif-column8
--no-space-after-casts
--line-comments-indentation0
--declaration-indentation16
--dont-format-first-column-comments
--indent-level4
--no-parameter-indentation
--line-length93
--comment-line-length93
--continue-at-parentheses
-nlps
--no-space-after-function-call-names
--dont-break-procedure-type
--start-left-side-of-comments
--space-after-for
--space-after-if
--space-after-while
--leave-optional-blank-lines
--space-special-semicolon
--tab-size8
--no-space-after-parentheses
--dont-break-function-decl-args
--honour-newlines
--no-tabs
-T int8_t
-T int16_t
-T int32_t
-T int64_t
-T uint8_t
-T uint16_t
-T uint32_t
-T uint64_t
-T u_char
-T u_short
-T u_int
-T u_long
-T unchar
-T ushort
-T uint
-T ulong
-T u_int8_t
-T u_int16_t
-T u_int32_t
-T u_int64_t
-T xthread_lock_data
-T xthread_data
-T xm_data
-T xqueue_queue
-T xqueue
-T xlist_node
-T xlist
-T ic_code
-T ic_flag
-T ic_node
-T ic_task
-T ic_who
-T ic_node_entry
-T ic_task_entry
-T ic_header
-T lcsm_state_function
-T led_control_submodule_driver
-T log_event_connect_t
-T log_event_template_t
-T pi_packet_header
-T pi_packet
-T pi_devinfo_req
-T pi_connect_req
-T pi_connect_rsp
-T pi_debugaddr_req
-T pi_debugaddr_rsp
-T pi_xprintflevel_req
-T pi_xprintflevel_rsp
-T pi_memrdwr_req
-T pi_memrdwr_rsp
-T pi_memreport_rsp_entry
-T pi_memreport_rsp
-T FILE
