#!/bin/bash
#
# get_next_build where
#

get_next_build() {
    local tag1
    local tag2
    local num1
    local num2
    local num
    local tagfile=".svntags-$$"
    local build="${1}"
    local build_char="${build:0:1}"

    svn list "${svn_tags}" > "${tagfile}"
    tag1=`grep "^BUILD_.*${build}.*-${build_char}[0-9]\{3\}" "${tagfile}" |
        tail -1`
    tag2=`grep "^BUILD_.*trunk-${build_char}[0-9]\{3\}" "${tagfile}" |
        tail -1`
    rm -f "${tagfile}"
    tag1="${tag1%/}"
    tag2="${tag2%/}"

    if [[ "${tag1}" != "" ]]; then
        num1=$((1${tag1:0-3:3}-1000))
    fi
    if [[ "${tag2}" != "" ]]; then
        num2=$((1${tag2:0-3:3}-1000))
    fi
    if [[ "${num1}" != "" && "${num2}" != "" ]]; then
        num="$((num1 > num2 ? num1 + 1 : num2 + 1))"
    elif [[ "${num1}" != "" ]]; then
        num="$((num1 + 1))"
    elif [[ "${num2}" != "" ]]; then
        num="$((num2 + 1))"
    fi
    if [[ "${num}" != "" ]]; then
        echo "${build_char}`printf %03d ${num}`"
    fi
}

# vi:sw=4 ts=4 expandtab
