#! /bin/bash
# $Id: make-cd,v 1.1 2006/12/13 20:06:02 RustadM Exp $
#
# make-cd - script to make an install CD
#
# Must be run on a controller.
#
# Copyright 2006 Xiotech Corporation. All rights reserved.
#
# make-cd [-h] [-b branch] [-t tag] [-v version] [-w where] [-m model]

usage() {
    echo "$0 [-h] [-b branch] [-t tag] [-v version] [-w where] [-m model]"
    echo ""
    echo "-h display help"
    echo "-b branch to build code from, ie. HEAD"
    echo "-t use tag for build"
    echo "-v version of code to build, ie. F100"
    echo "-w where to put results of build"
    echo "-m model to build (or ALL)"
}

test "$#" -eq 0 && { echo "Parameters required"; usage; exit 1; }
models="750 3000"
branch=
tag=
ver=
where=
model=ALL

while getopts "b:ht:m:v:w:" option; do
    case "${option}" in
        b) branch="${OPTARG}";;
        h) usage;;
        t) tag="${OPTARG}";;
        m) model="${OPTARG}";;
        v) ver="${OPTARG}";;
        w) where="${OPTARG}";;
        :) echo "Required parameter for option ${OPTARG} missing.";
            usage; exit 1;;
        \?) usage; exit 1;;
        *) echo "Unknown option '${option}'"; usage; exit 1;;
    esac
done

shift $((OPTIND - 1))

test "${branch}" = "" && branch=trunk
test "`echo ${branch}|tr [:lower:] [:upper:]`" = "MAIN" &&
    branch=trunk

test "${ver}" = "" && ver=ENGR
uver="`echo ${ver}|tr [:lower:] [:upper:]`"

where="`echo "${where}"|tr [:lower:] [:upper:]`"
test "${where}" = "" && where=Engr

test "${tag}" = "" && tag="${branch}_${uver}"

test "${model}" = "ALL" && model="${models}"

echo "Make install CD"
echo ""
echo "----------"
echo "About to build install CD:"
echo "    ver=${ver} where=${where}, model=${model}"
echo ""

while { echo -n "Ready [Y/N]? "; read input; } do
    test "${input}" = "Y" && break
    test "${input}" = "n" -o "${input}" = "N" &&
        { echo "build cancelled."; exit 1; }
done
echo "*** Beginning CD build ***"

blddir="${branch}-${uver}"

cd ${blddir} || { echo "${blddir} not found"; exit 1; }

echo "** Entering ${blddir} **"

cd Wookiee || { echo "Wookiee directory not found"; exit 1; }

for mod in ${model}; do
    echo "** Beginning install CD build for model ${mod} **"
    make MODEL=${mod} VER=${ver} PERF=PERF HEADER=${where} clean cd ||
        { echo "MODEL=${mod} VER=${ver} cd failed!"; exit 1; }
    make MODEL=${mod} VER=${ver} PERF=PERF HEADER=${where} cd-save-k ||
        { echo "MODEL=${mod} VER=${ver} cd-save-k failed!"; exit 1; }
done

echo "*** Install CD build completed successfully! ***"

# vi:sw=4 ts=4 expandtab
