#!/bin/bash
# $Id$
# send-build-mail
#
# Copyright 2007 Xiotech Corporation, All rights reserved.
#
# Mark D. Rustad, 10/24/2007

. ${SDIR}/build-mail-list

mail -s "$* succeeded" "${build_mail_list[@]}" <<EOF
The build of "$*"
has completed successfully.
EOF

