#!/bin/bash -x
# --fs
# --platochars
# --lines
#
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
#
CPP='gcc -E -x c -nostdinc -C -CC -Wno-error -Wno-extra -traditional-cpp -Wno-invalid-pp-token'
IMS='../imscomp --fs --platochars --lines'
#
unalias doit 2>>/dev/null >>/dev/null
doit()
{
    FILE="$1"
    BASE="`basename ${FILE} .gcs`"
    CPPE="${BASE}.E"
    FS="${BASE}.fs"
    ${CPP} "${FILE}" -o "${CPPE}"
    ${IMS} "${CPPE}" "${FS}" 2>&1
}
#-----------------------------------------------------------------------------
doit 18notes.gcs                > AAA.00 2>&1
doit 1963.gcs                   > AAA.01 2>&1
doit Djokja.gcs                 > AAA.03 2>&1
doit Chromatic.gcs              > AAA.02 2>&1
doit Entroid.gcs                > AAA.04 2>&1
doit Entroid_.gcs               > AAA.05 2>&1
doit Horizons.gcs               > AAA.06 2>&1
doit Joy.gcs                    > AAA.07 2>&1
doit Kanon.gcs                  > AAA.08 2>&1
doit Miditest.gcs               > AAA.09 2>&1
doit Phantasm.gcs               > AAA.10 2>&1
doit Poppers.gcs                > AAA.11 2>&1
doit Roundoff.gcs               > AAA.12 2>&1
doit changes-idea.gcs           > AAA.13 2>&1
doit char-print.gcs             > AAA.14 2>&1
doit clock-tower.gcs            > AAA.15 2>&1
#-- doit e-minor.gcs                > AAA.16 2>&1 &     macros, no music/notes.
doit etude-1-chopin.gcs         > AAA.17 2>&1
doit fru-uhlingserwachen.gcs    > AAA.18 2>&1
doit idea.gcs                   > AAA.19 2>&1
doit invention-4.gcs            > AAA.20 2>&1
doit joy-piano-part.gcs         > AAA.21 2>&1
doit ma-solitude.gcs            > AAA.22 2>&1
#-- macro-arpeggiate.include
#-- macro-compile.include
doit maple-leaf-rag.gcs         > AAA.25 2>&1
doit miscellaneous-ideas.gcs    > AAA.26 2>&1
doit mozart.gcs                 > AAA.27 2>&1
doit oh-lady-be-good.gcs        > AAA.28 2>&1
doit opus10-chopin.gcs          > AAA.29 2>&1
doit opus8-scriabin.gcs         > AAA.30 2>&1
doit poj-prelude.gcs            > AAA.31 2>&1
#-- process-invert.include
#-- process-samenote.include
#-- process-slide.include
#-- process-tremelo.include
#-- process-xinfo.include
doit random-chords.gcs          > AAA.37 2>&1
doit replot.gcs                 > AAA.38 2>&1
doit revolution-midi.gcs        > AAA.39 2>&1
doit song-without-words.gcs     > AAA.40 2>&1
#-- split.include
#-- standard-print-stuff.include
doit theme.gcs                  > AAA.43 2>&1
doit true-faith.gcs             > AAA.44 2>&1
doit what-a-fool-believes.gcs   > AAA.45 2>&1
# ----------------------------------------------------------------------------
