#!/usr/bin/python
import os
import sys
import time
import datetime
import string

try:
	f = open(sys.argv[1], 'a+')
except:
	print("usage: {} <fully specified file name>".format(sys.argv[0]))
	sys.exit(1)
i=0
while i < 1296000:
   line="This is a workload Test -- line {0}".format(i)
   i=i+1
   f.write(line+'\n')
   f.flush()
   print(line)
   time.sleep(2)

f.close()
