.\" Copyright (c) 1986 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)nslookup.1	1.2 (Berkeley) 11/21/87
.\"
.TH INET 1 "August 8, 1988"
.SH NAME
inet \- ask the domain name system for a host name or address
.SH SYNOPSIS
.B inet
[ -d ]
[ -v ]
[ -h ]
[ -s nameserver[:port] ]
.I hostname\ |\ host-IP-address
\|...
.SH DESCRIPTION
.IR Inet
queries DARPA Internet domain name servers. 
Given a (list of) host names, it uses
.IR gethostbyname (3)
to find the canonical host name and all listed interfaces;
given host addresses, it calls
.IR gethostbyaddr (3)
to find the canonical host name.
It uses the domain resolver library to do this, bypassing any /etc/hosts
or Sun Yellow Pages tables.
.sp
Since it is linked with the BIND 4.8 domain resolver library, it
applies the sliding-match host name lookup described in resolver(3).
As described there, a trailing ``.'' on a host name suppresses the
sliding match search, forcing a lookup on just the specified name.
.sp
The -d option enables debugging (setting the RES_DEBUG flag mentioned in
.IR resolver (3)
); details of all domain requests sent and responses received are printed.
.sp
The -v option selects using a virtual circuit (TCP stream) rather than
UDP datagrams for sending queries.  It is worth using when asking about
many hosts at a time.
.sp
The -h option forces a name to be looked up as a host name even if
it appears to be a numeric IP address.
.sp
The -n option prints out only the DNS name of the given address(es) or name(s).
.sp
The -i option prints out only the IP address(es) of the given name(s) or address(es).
.sp
The -s option selects the name server(s) to query rather than the ones
listed in /etc/resolv.conf.  Multiple -s options are allowed; they are
queried in the order given until a response is received.
Suffixing ``:'' and a decimal port number to a name server name/IP-address
directs queries to that port rather than the standard 53.
.sp
.SH DIAGNOSTICS
.in +4
.ti -4
HOST_NOT_FOUND -- inet received an authoritative indication that the
host or IP address is not known anywhere in the domain system
.sp
.ti -4
TRY_AGAIN -- either no response was recieved or the response was not
authoritative.  Another try might yield a definite answer.
This error can also appear if the server(s) are not working correctly.
.sp
.ti -4
NO_DATA -- the host exists but no IP address is known; there may be
other information such as MX mail-forwarding records.
.sp
.ti -4
NO_RECOVERY -- a server complained that inet had sent an invalid request;
should not happen.
.in -4
.sp
.SH FILES
/etc/resolv.conf	default domain name and name server addresses
.SH SEE ALSO
nslookup(1), nstest(1), resolver(3), resolver(5)
