#!/bin/bash

cd ~root
chkconfig -s < epconfig.save
rcsshd start

test -d /mnt/res/sles9 || {
   rcportmap start
   mount -t nfs -o ro,udp,rsize=8192,wsize=8192 10.64.99.254:/home /mnt/res
}

cd /etc
cp /mnt/res/sles9/ep/hosts.ep hosts
cp /mnt/res/sles9/ep/passwd.ep passwd
cp /mnt/res/sles9/ep/shadow.ep shadow
cp /mnt/res/sles9/ep/group.ep group
cp /mnt/res/sles9/ep/fstab.ep fstab
sync; sync
umount /mnt/res || umount -l /mnt/res

sleep 2

rcportmap stop
