#!/bin/bash -ex
#-----------------------------------------------------------------------------
echo "Starting $0"
#-----------------------------------------------------------------------------
. 00-package-definitions
#-----------------------------------------------------------------------------
F="audit-libs-devel
   binutils-devel
   bzip2-devel
   dbus-devel
   elfutils-devel
   elfutils-libelf-devel
   ima-evm-utils-devel
   libacl-devel
   libcap-devel
   libdb-devel
   libselinux-devel
   libzstd-devel
   ncurses-devel
   openssl-devel
   popt-devel
   readline-devel
   xz-devel
   zlib-devel"

#--   file-devel
#--   libarchive-devel
#--   lua-devel
#--   python3-devel
#-----------------------------------------------------------------------------
#-- yum install -y popt-devel-1.13-16.el7.x86_64
#-- yum install -y lua.x86_64
#-----------------------------------------------------------------------------
for f in ${F}; do
    # echo f=${f}
    yum install $f
done
#-----------------------------------------------------------------------------
#-- exit 123
#-----------------------------------------------------------------------------
if [ ! -d ${VERSION_RPM} ]; then
    if [ ! -f ${VERSION_RPM}.tar.gz ]; then
	wget -N ${WHERE_RPM}/${VERSION_RPM}.tar.bz2
    fi
    tar xf ${VERSION_RPM}.tar.bz2
    patch -p0 < RPM.configure.patch
fi
#-----------------------------------------------------------------------------
if [ ! -d ${VERSION_DB} ]; then
    if [ ! -f ${VERSION_DB}.tar.gz ]; then
	wget -N ${WHERE_DB}/${VERSION_DB}.tar.gz
    fi
    tar xf ${VERSION_DB}.tar.gz
fi
( cd ${VERSION_RPM}/ && ln -sf ../${VERSION_DB} db )
#-----------------------------------------------------------------------------
#-----------------------------------------------------------------------------
cd ${VERSION_RPM}/
#-----------------------------------------------------------------------------
#-- ./configure --prefix=${BINARIES} CFLAGS='-fPIE -fPIC' LUA_LIBS=/usr/local/lib/liblua.a LIBS=-lm 1>&2
#-- ./configure --prefix=${BINARIES} CFLAGS='-fPIE -fPIC' LUA_LIBS=${BINARIES}/lib/liblua.a LIBS=-lm 1>&2
./configure --prefix=${BINARIES} CFLAGS='-fPIE -fPIC -DAUDIT_SOFTWARE_UPDATE=1138' LUA_LIBS=${BINARIES}/lib/liblua.a LIBS=-lm 1>&2
#-----------------------------------------------------------------------------
make ${J}
#-----------------------------------------------------------------------------
make install
#-----------------------------------------------------------------------------
make clean || true
make distclean || true
#-----------------------------------------------------------------------------
echo "Finishing $0"
exit 0
#-----------------------------------------------------------------------------
