#!/bin/bash -ex
NEWGCC_WHERE=/new-gcc-11.1
prepath () {
    case ":$PATH:" in
      *":$1:"*) :;;         # in the middle
      "$1:"*) :;;           # at the end
      *":$1") :;;           # at the beginning
      "$1") :;;             # if only one
      *) PATH=$1:$PATH;;
    esac
}
prepath ${NEWGCC_WHERE}/bin
ldconfig ${NEWGCC_WHERE}/lib	# Need the new shared libraries.
which -a gcc			# should be /root/new-a/bin/gcc
gcc --version     
which -a rpmbuild
which -a rpm

export PATH

export CC=${NEWGCC_WHERE}/bin/gcc
export LD=${NEWGCC_WHERE}/bin/ld
export AR=${NEWGCC_WHERE}/bin/ar
export AS=${NEWGCC_WHERE}/bin/as
export CXX=${NEWGCC_WHERE}/bin/g++

NEWSTUFF="CC=${NEWGCC_WHERE}/bin/gcc LD=${NEWGCC_WHERE}/bin/ld AR=${NEWGCC_WHERE}/bin/ar AS=${NEWGCC_WHERE}/bin/as CXX=${NEWGCC_WHERE}/bin/g++"

date
pwd

make ${NEWSTUFF} -j 255 all

#-----------------------------------------------------------------------------
ldconfig                        # Put it back to original.
#-----------------------------------------------------------------------------
echo DONE
date
