#!/bin/bash -ex
NEWGCC_WHERE='/new-gcc-11.1'
#-----------------------------------------------------------------------------
date

make kb-clean
rm -rf "${NEWGCC_WHERE}"

(cd build-rpm && ./01.new-gcc+rpm+etc)
#-----------------------------------------------------------------------------
ldconfig	# Put back to normal.
#-----------------------------------------------------------------------------
prepath () {
    case ":$PATH:" in
      *":$1:"*) :;;         # in the middle
      "$1:"*) :;;           # at the end
      *":$1") :;;           # at the beginning
      "$1") :;;             # if only one
      *) PATH=$1:$PATH;;
    esac
}
prepath "${NEWGCC_WHERE}/bin"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#--	# MUST NOT HAVE libgpg-error.so* in the new library.
#--	mkdir -p ${NEWGCC_WHERE}/lib/SAVE
#--	(cd ${NEWGCC_WHERE}/lib && mv libgpg* SAVE/) || true
#-- ldconfig ${NEWGCC_WHERE}/lib	# Need the new shared libraries.

export LD_LIBRARY_PATH="${NEWGCC_WHERE}/lib"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
which -a gcc			# should be /root/new-a/bin/gcc
gcc --version     
which -a rpmbuild
which -a rpm

export PATH

export CC=${NEWGCC_WHERE}/bin/gcc
export LD=${NEWGCC_WHERE}/bin/ld
export AR=${NEWGCC_WHERE}/bin/ar
export AS=${NEWGCC_WHERE}/bin/as
export CXX=${NEWGCC_WHERE}/bin/g++

NEWSTUFF="CC=${NEWGCC_WHERE}/bin/gcc "
NEWSTUFF+="LD=${NEWGCC_WHERE}/bin/ld "
NEWSTUFF+="AR=${NEWGCC_WHERE}/bin/ar "
NEWSTUFF+="AS=${NEWGCC_WHERE}/bin/as "
NEWSTUFF+="CXX=${NEWGCC_WHERE}/bin/g++ "

export MAKE="make ${NEWSTUFF}"
#-----------------------------------------------------------------------------

# No existing builds (done above too, this is just in case...).
${MAKE} -j 255 kb-clean

# Get ready to compile.
${MAKE} -j 255 prep

# Compile, but not with rpmbuild.
${MAKE} -j 255 all

#-----------------------------------------------------------------------------
echo "DONE with $0"
date
