#!/bin/bash

cd ~root
chkconfig -s < epdbgconfig.save
rcsshd start
rcportmap start
rcnfslock start
rcxntpd start

test -d /home/sles9 ||
	mount -t nfs -o rw,udp,rsize=8192,wsize=8192 10.64.99.243:/home /home

cd /etc
cp /home/sles9/ep/hosts.ep hosts
cp /home/sles9/ep/passwd.ep passwd
cp /home/sles9/ep/shadow.ep shadow
cp /home/sles9/ep/group.ep group
cp /home/sles9/ep/fstab.epdbg fstab
sync; sync

test -x /usr/bin/make || {
	mount /usr
	ldconfig -X 2>/dev/null
}

test -d /u/local || mount /u

# vi:sw=8 ts=8 noexpandtab
