#!/bin/bash -x
DEV=$1
if [ "$DEV" = '' ]; then
    echo "Need argument of the device to zero (sda)"
    exit 1
fi
#-----------------------------------------------------------------------------
rm -f A.0[1-9]
BN=`basename ${DEV}`
if [ "$BN" = '' ]; then
    echo "Need argument of device that has a basename that isn't blank."
    exit 1
fi
rm -rf ${BN}
#-----------------------------------------------------------------------------
time ./01.Test-normal-dd-sync ${DEV} > A.01 2>&1
time ./02.drop_caches ${DEV} > A.02 2>&1
time ./03.direct ${DEV} > A.03 2>&1
time ./04.sync ${DEV} > A.04 2>&1
time ./05.direct+sync ${DEV} > A.05 2>&1
#-----------------------------------------------------------------------------
mkdir ${BN}
mv A.0[1-9] ./${BN}/
#-----------------------------------------------------------------------------
