#!/bin/bash
A="${M4_FILE}"

#-- (/bin/date '+%Y-%m-%d_%H-%M-%S-%N' ; /bin/echo -e "$*" ; echo '++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++' ; printenv | egrep -v 'M4_|PWD=|SEQNUM="|USEC_INITIALIZED=|SHLVL=|_=' | sort;  echo '------------------------------------------------------------------------------' ) >> ${A}

(/usr/bin/echo "$A $*" ; printenv | egrep -v 'M4_|PWD=|SEQNUM="|USEC_INITIALIZED=|SHLVL=|_=' | sort ) >> /dev/kmsg

exit 0
