#!/bin/bash
event="$1"
md="$2"
dev="$3"
all="$*"
date=`/bin/date '+%Y-%m-%d_%H-%M-%S.%N'`
mdstat=`cat /proc/mdstat | sed -e '/Personalities/d' -e '/bitmap/d' -e '/blocks/d' -e 's/  *$//' -e '/^$/d' -e 's/^/  /' `
devmd=`/usr/bin/echo /dev/md/*`

/usr/bin/echo "1st='$event' 2nd='${md} 3rd='${dev}' all='${all}' devmd=${devmd} ${mdstat}" > /dev/kmsg

exit 0
