#!/bin/bash -ex
#-- abc2midi m4test.abc
midicsv A-v6-1.mid >A.csv
midi2abc A-v6-1.mid >A.ABC
#-- midi2ly m4test1.mid
make mcomp
# ./mcomp A-v6-1.mid HORIZONTAL >A.stdout 2>A.stderr
./mcomp A-v6-1.mid >A.stdout 2>A.stderr
# ./mcomp A-v6-1.mid
#-----------------------------------------------------------------------------
