#!/bin/bash -ex

#-- DOT.fluidsynth

#--sound fornt--	/Users/m4/src/GeneralUser_GS/GeneralUser_GS.sf2
play ()
{
    FILE="$1";
    cat DOT.fluidsynth ${FILE} | \
       fluidsynth -a coreaudio -n -q -g 0.5 -K 64
}

play t.cc

exit 0
