#!/bin/bash -x
#-----------------------------------------------------------------------------
sysctl -w dev.raid.speed_limit_min=500000000
sysctl -w dev.raid.speed_limit_max=500000000
#-----------------------------------------------------------------------------
mdadm -I /dev/nvme1n1p1 --run
#-----------------------------------------------------------------------------
# If it will not go via above, try:
#   mdadm --manage /dev/md12X --add /dev/nvme1n1p1
