#!/bin/bash -x
#-----------------------------------------------------------------------------
sysctl -w dev.raid.speed_limit_min=500000000
sysctl -w dev.raid.speed_limit_max=500000000
#-----------------------------------------------------------------------------
# NOTE: Swap usually doesn't need to be incrementally added, as it never is written to. :)
mdadm -I /dev/sda2 --run
mdadm -I /dev/sda3 --run
mdadm -I /dev/sda4 --run
mdadm -I /dev/sda5 --run
mdadm -I /dev/sda6 --run
mdadm -I /dev/sda7 --run
mdadm -I /dev/sda8 --run
#-----------------------------------------------------------------------------
# If it will not go via above, try:
#   mdadm --manage /dev/md12X --add /dev/sdaY
