#!/bin/bash -x
#-----------------------------------------------------------------------------
sysctl -w dev.raid.speed_limit_min=500000000
sysctl -w dev.raid.speed_limit_max=500000000
#-----------------------------------------------------------------------------
# NOTE: Swap usually doesn't need to be incrementally added, as it never is written to. :)
mdadm -I /dev/nvme0n1p1 --run
#-----------------------------------------------------------------------------
# If it will not go via above, try:
#   mdadm --manage /dev/md123 --add /dev/sda2
