#!/bin/bash -x
#-----------------------------------------------------------------------------
diff -u {/,}etc/dracut.conf
diff -u {/,}etc/mdadm.conf

diff -u {/,}etc/multipath.conf
diff -u {/,}etc/systemd/journald.conf

diff -u {/,}etc/udev/rules.d/00-debug.rules
diff -u {/,}etc/udev/rules.d/99-zzz-debug-last.rules
#-----------------------------------------------------------------------------
diff -ur {/,}m4debug/
#-----------------------------------------------------------------------------
diff -u {/,}usr/lib/dracut/modules.d/90mdraid/59-persistent-storage-md.rules
diff -u {/,}usr/lib/dracut/modules.d/90mdraid/65-md-incremental-imsm.rules
diff -u {/,}usr/lib/dracut/modules.d/90mdraid/mdraid_start.sh
diff -u {/,}usr/lib/dracut/modules.d/90mdraid/parse-md.sh

diff -u {/,}usr/lib/dracut/modules.d/95nvmf/parse-nvmf-boot-connections.sh
diff -u {/,}usr/lib/dracut/modules.d/95resume/parse-resume.sh
diff -u {/,}usr/lib/dracut/modules.d/95rootfs-block/block-genrules.sh
diff -u {/,}usr/lib/dracut/modules.d/95rootfs-block/parse-block.sh

diff -u {/,}usr/lib/dracut/modules.d/98dracut-systemd/dracut-cmdline.sh
diff -u {/,}usr/lib/dracut/modules.d/98dracut-systemd/dracut-initqueue.sh
diff -u {/,}usr/lib/dracut/modules.d/98dracut-systemd/rootfs-generator.sh

diff -u {/,}usr/lib/dracut/modules.d/99base/dracut-lib.sh
diff -u {/,}usr/lib/dracut/modules.d/99base/init.sh
diff -u {/,}usr/lib/dracut/modules.d/99base/module-setup.sh
#-----------------------------------------------------------------------------
diff -u {/,}usr/lib/systemd/system/mdmonitor.service
diff -u {/,}usr/lib/systemd/system/mdadm-last-resort@.service
diff -u {/,}usr/lib/systemd/system/mdadm-last-resort@.timer
diff -u {/,}usr/lib/systemd/system/mdmonitor-oneshot.service
diff -u {/,}usr/lib/systemd/system/systemd-udev-settle.service
#-----------------------------------------------------------------------------
diff -u {/,}usr/lib/udev/rules.d/01-md-raid-creating.rules
diff -u {/,}usr/lib/udev/rules.d/63-md-raid-arrays.rules
diff -u {/,}usr/lib/udev/rules.d/64-md-raid-assembly.rules
diff -u {/,}usr/lib/udev/rules.d/65-md-incremental.rules
diff -u {/,}usr/lib/udev/rules.d/69-md-clustered-confirm-device.rules
#-----------------------------------------------------------------------------
exit 0
