#!/bin/bash -ex
powershell.exe -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -Command '$ws = New-Object -ComObject WScript.Shell; $S = $ws.CreateShortcut('"'$2'"'); $S.TargetPath = '"'$1'"'; $S.Save()'
