#!/usr/local/bin/bash -x

ulimit -c unlimited
defaults write com.apple.finder AppleShowAllFiles TRUE

# ABCM2PS      = abcm2ps
# ABCM2PS_ARGS = -M -b 1 $< -i -N 2 -j 1
# (${ABCM2PS} ${ABCM2PS_ARGS} ; mv Out.ps $@) \
/usr/local/bin/abcm2ps -M -b 1 e.abc -i -N 2 -j 1

F=`/bin/ls -1t /cores/ | head -n 1`

lldb /usr/local/bin/abcm2ps -c /cores/${F}

exit 0
