#!/bin/bash -e
sysctl -w kernel.softlockup_panic=1
#-----------------------------------------------------------------------------
DISK=/home/m4/file/lio/file0
SIZE=16777216
#-----------------------------------------------------------------------------
#-- REMOTE_WWPN=iqn.1994-05.com.redhat:78c8376ef72a
#-iSCSI- REMOTE_WWPN='iqn.2016-12.com.parseclabs:hyperqtg.f67ef4c2865f'
REMOTE_WWPN=21:00:00:24:ff:83:01:0b
#-----------------------------------------------------------------------------
#-iSCSI- IQN=iqn.2016-12.com.parseclabs:hyperqtg.f67ef4c2865f
LOCAL_NAA=naa.21000024ff0fb046
#-----------------------------------------------------------------------------
TYPE=fileio
FILE_NAME=file0
LUN=6
#-----------------------------------------------------------------------------
logger 'before creating target'
sleep 1
#-----------------------------------------------------------------------------
#-- targetcli <<EOF_TARGETCLI
#-- set global auto_cd_after_create=false
#-- /backstores/${TYPE} create ${FILE_NAME} ${DISK} ${SIZE}
#-- /iscsi/${IQN}/tpg1/luns/ create /backstores/${TYPE}/${FILE_NAME} ${LUN}
#-- /iscsi/${IQN}/tpg1/acls create ${REMOTE_WWPN}
#-- cd /
#-- EOF_TARGETCLI

targetcli <<EOF_TARGETCLI || true
set global auto_cd_after_create=false
/qla2xxx/ create wwn=${LOCAL_NAA}
/backstores/${TYPE} create ${FILE_NAME} ${DISK} ${SIZE}
/qla2xxx/${LOCAL_NAA}/luns create /backstores/${TYPE}/${FILE_NAME} ${LUN}
/qla2xxx/${LOCAL_NAA}/acls create ${REMOTE_WWPN}
cd /
EOF_TARGETCLI
#-----------------------------------------------------------------------------
logger 'after creating target'
sleep 1
/px/bin/targetcli_probe
exit 0
#=============================================================================
