#!/bin/bash -e
#? sysctl -w kernel.softlockup_panic=1
#-----------------------------------------------------------------------------
DISK=/home/m4/file/lilo/file0
SIZE=16777216
TYPE=fileio
FILE_NAME=file0
LUN=6
#-----------------------------------------------------------------------------
REMOTE_WWPN1=21:00:00:24:ff:0f:b0:46
REMOTE_WWPN2=21:00:00:24:ff:0f:b0:47
#-----------------------------------------------------------------------------
#?--	LOCAL_NAA1=naa.21000024ff301f68
#?--	LOCAL_NAA2=naa.21000024ff301f69
LOCAL_NAA3=naa.21000024ff8302b8
#?--	LOCAL_NAA4=naa.21000024ff8302b9
#?--	LOCAL_NAA5=naa.21000024ff8302ba
#?--	LOCAL_NAA6=naa.21000024ff8302bb
#?--	LOCAL_NAA7=naa.21000024ff4e47ec
#?--	LOCAL_NAA8=naa.21000024ff4e47ed
#?--	LOCAL_NAA9=naa.21000024ff830108
#?--	LOCAL_NAA10=naa.21000024ff830109
#?--	LOCAL_NAA11=naa.21000024ff83010a
#?--	LOCAL_NAA12=naa.21000024ff83010b
#-----------------------------------------------------------------------------
#-----------------------------------------------------------------------------
logger 'before creating target'
sleep 1
#-----------------------------------------------------------------------------
targetcli <<EOF_TARGETCLI || true
set global auto_cd_after_create=false
/backstores/${TYPE} create ${FILE_NAME} ${DISK} ${SIZE}
/qla2xxx/ create wwn=${LOCAL_NAA3}
/qla2xxx/${LOCAL_NAA3}/luns create /backstores/${TYPE}/${FILE_NAME} ${LUN}
/qla2xxx/${LOCAL_NAA3}/acls create ${REMOTE_WWPN1}
/qla2xxx/${LOCAL_NAA3}/acls create ${REMOTE_WWPN2}
cd /
EOF_TARGETCLI
#-----------------------------------------------------------------------------
logger 'after creating target'
sleep 1
/px/bin/targetcli_probe
exit 0
#=============================================================================
targets:
  21:00:00:24:ff:30:1f:68
  21:00:00:24:ff:30:1f:69
  21:00:00:24:ff:83:02:b8
  21:00:00:24:ff:83:02:b9
  21:00:00:24:ff:83:02:ba
  21:00:00:24:ff:83:02:bb
------------------------------------------------------------------------------
/qla2xxx/ create wwn=${LOCAL_NAA}
/qla2xxx/${LOCAL_NAA}/luns create /backstores/${TYPE}/${FILE_NAME} ${LUN}
/qla2xxx/${LOCAL_NAA}/acls create ${REMOTE_WWPN}
cd /
EOF_TARGETCLI
#-----------------------------------------------------------------------------
/px/bin/targetcli_probe
exit 0
#=============================================================================
