#!/bin/bash -e
sysctl -w kernel.softlockup_panic=1
#-----------------------------------------------------------------------------
targetcli <<EOF_TARGETCLI || true
set global auto_cd_after_create=false
/qla2xxx/naa.21000024ff301f68/luns create /backstores/block/io 1
/qla2xxx/naa.21000024ff301f68/acls create naa.21000024ff0fb047

/qla2xxx/naa.21000024ff301f69/luns create /backstores/block/io 1
/qla2xxx/naa.21000024ff301f69/acls create naa.21000024ff0fb047

/qla2xxx/naa.21000024ff8302b9/luns create /backstores/block/io 1
/qla2xxx/naa.21000024ff8302b9/acls create naa.21000024ff0fb047

/qla2xxx/naa.21000024ff8302ba/luns create /backstores/block/io 1
/qla2xxx/naa.21000024ff8302ba/acls create naa.21000024ff0fb047

/qla2xxx/naa.21000024ff8302bb/luns create /backstores/block/io 1
/qla2xxx/naa.21000024ff8302bb/acls create naa.21000024ff0fb047

/px/bin/targetcli_probe
exit 0




#-----------------------------------------------------------------------------
REMOTE_WWPN=21:00:00:24:ff:0f:b0:47
#-----------------------------------------------------------------------------
#-- LOCAL_WWPN=21:00:00:24:ff:0f:b0:46
#-- LOCAL_WWPN=21:00:00:24:ff:0f:b0:47
LOCAL_WWPN=naa.21000024ff8302b8
#-- LOCAL_WWPN=21:00:00:24:ff:83:01:0b
#-----------------------------------------------------------------------------
TYPE=block
FILE_NAME=io
LUN=1
#-----------------------------------------------------------------------------
logger 'before creating target'
sleep 1
#-----------------------------------------------------------------------------
targetcli <<EOF_TARGETCLI || true
set global auto_cd_after_create=false
/backstores/${TYPE} create ${FILE_NAME} ${DISK}
/qla2xxx/${LOCAL_WWPN}/luns create /backstores/${TYPE}/${FILE_NAME} ${LUN}
/qla2xxx/${LOCAL_WWPN}/acls create ${REMOTE_WWPN}
cd /
EOF_TARGETCLI
#-----------------------------------------------------------------------------
logger 'after creating target'
sleep 1
/px/bin/targetcli_probe
exit 0
#=============================================================================
