#
set solib-absolute-prefix /env/sles9-32-Wookiee/
core-file  Front.t.core
#
source .gdbinit
#
directory SRCS/Proc/src
directory SRCS/Proc/inc
directory SRCS/Shared/Inc
directory SRCS/Shared/Src
directory SRCS/Proc/obj_MODELDEBUGPERF
#
#	Print current process name.
echo \n
forkname
#
# 	Print "c" backtrace.
echo \n
bt 18
#
#	Print registers at time of fe errtrapping.
echo \n
errtrapf
#
#	print backtrace of process in errtrapf.
echo \n
ebt
#
echo Possible: dump_CA_OpRetryQue allfequeues femmfree vcdList, etc.\n
echo \          last mrp flight pcbstate btpcbs dumpdevqueues\n
echo \          memlistscount memlists feorcs fe{3,7}000countopsoutstanding\n
echo \          p *K_ii\n
#
#-----------------------------------------------------------------------------
# Other things that you might want to do.
#
# g	-- if errtrapf, worthless
# r	-- if errtrapf, worthless
#
# Following only if CT_HISTORY is on.
#	tracelog 90
#	tracelogreg 10
