#!/bin/bash -epux
unset LANG
unset __CF_USER_TEXT_ENCODING
# ----------------------------------------------------------------------------
MIDICSV=midicsv
CSV2FS=../../csv2fs
FS2GCS=../../../fs2gcs/fs2gcs
# ----------------------------------------------------------------------------
#+ MID=(`echo *.mid`)
#+ MID=("beetho.mid" "lvbsym33.mid" "sym3_3.mid" "symphony.mid")
#FS2GCS FAIL - MID=("sym3_3.mid")
MID=("symphony.mid")
# ----------------------------------------------------------------------------
#DEBUG for m in ${MID[@]}; do
#DEBUG     echo "m = ${m}"
#DEBUG done
#DEBUG exit 1
# ----------------------------------------------------------------------------
for m in ${MID[@]}; do
    n=`basename ${m} .mid`
    ${MIDICSV} ${m} | sed -f SED-csv > ${n}.csv || true
    ${CSV2FS} --lines ${n}.csv ${n}.fs || true
    ${FS2GCS} --lines ${n}.fs ${n}.gcs ${n}.hints || true
done
# ----------------------------------------------------------------------------
exit 0
# ----------------------------------------------------------------------------

LANG=en_US.UTF-8
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
