#!/bin/bash -ex
M=../musicomp2abc
rm -f nested-[0123456789]*.v

let c=100	|| true

# The 4 xpose for 'c', which should look sort of like 01-k-c-major-0.v.
# What to do:

let d=$c+1	|| true
${M} --vertical ${c}-k-c-major-1.v nested-${d}-f.v    --xpose "1..8 0 f"

let c=$d	|| true
let d=$c+1	|| true
${M} --vertical nested-${c}-f.v    nested-${d}-b-.v   --xpose "1..8 0 b-"
let c=$d
let d=$c+1	|| true
${M} --vertical nested-${c}-b-.v   nested-${d}-e-.v   --xpose "1..8 0 e-"
let c=$d
let d=$c+1	|| true
${M} --vertical nested-${c}-e-.v   nested-${d}-a-.v   --xpose "1..8 0 a-"
let c=$d
let d=$c+1	|| true
${M} --vertical nested-${c}-a-.v   nested-${d}-d-.v   --xpose "1..8 0 d-"
let c=$d
let d=$c+1	|| true
${M} --vertical nested-${c}-d-.v   nested-${d}-g-.v   --xpose "1..8 0 g-"
let c=$d
let d=$c+1	|| true
${M} --vertical nested-${c}-g-.v   nested-${d}-c-.v   --xpose "1..8 0 c-"
let c=$d
let d=$c+1	|| true

${M} --vertical nested-${c}-c-.v   nested-${d}-c+.v   --xpose "1..8 0 c+"
let c=$d
let d=$c+1	|| true
${M} --vertical nested-${c}-c+.v   nested-${d}-f+.v   --xpose "1..8 0 f+"
let c=$d
let d=$c+1	|| true
${M} --vertical nested-${c}-f+.v   nested-${d}-b.v    --xpose "1..8 0 b"
let c=$d
let d=$c+1	|| true
${M} --vertical nested-${c}-b.v    nested-${d}-e.v    --xpose "1..8 0 e"
let c=$d
let d=$c+1	|| true
${M} --vertical nested-${c}-e.v    nested-${d}-a.v    --xpose "1..8 0 a"
let c=$d
let d=$c+1	|| true
${M} --vertical nested-${c}-a.v    nested-${d}-d.v    --xpose "1..8 0 d"
let c=$d
let d=$c+1	|| true
${M} --vertical nested-${c}-d.v    nested-${d}-g.v    --xpose "1..8 0 g"
let c=$d
let d=$c+1	|| true

${M} --vertical nested-${c}-g.v    nested-${d}-c.v    --xpose "1..8 0 c"

exit 0
