#!/usr/bin/perl -w
#====================================================================
#
# FILE NAME:    debugconsole 
#
# AUTHOR:       Randy Rysavy
#
# DATE:         6/3/2004
#
# DESCRIPTION:  Modifies DebugConsole.pl to work on Linux, then exec's to it.
#               This program is intended to be run only on Linux.
#
#====================================================================

use strict;

sub GetModTime
{
    my ($fname) = @_;
    my @times = (0,0);
    
    if (-r "$fname")
    {
        my @st = stat("$fname");
        @times = ($st[8], $st[9]);
    }

    return @times;
}

my $curName = "./DebugConsole.pl";
my $linuxName = "./DebugConsole.pl-linux";

my @curTime = GetModTime "$curName";
my @linuxTime = GetModTime "$linuxName";

if ($curTime[1] != $linuxTime[1])
{
    print "=== Modifying DebugConsole.pl to run on Linux ===\n";

    unlink "$linuxName";

    open IN, "$curName" or die;
    open OUT, "> $linuxName" or die;

    while(<IN>)
    {
        $_  = "#$_" if /^use Win32::Console;/;
        $_  = "#$_" if /^use Archive::Tar;/;
        $_  = "#$_" if /Win32::Console/;
        print OUT;
    }

    close IN;
    close OUT;

    chmod 0777, "$linuxName";

    utime @curTime, "$linuxName";
}

# Arguments must not be re-parsed by /bin/sh.  Quote them with single quotes.
my $args = '';
while (@ARGV) {
  $args .= " '" . shift(@ARGV) . "'";
}

exec "$linuxName$args";

