#!/bin/bash -e
CMD="$*"
#-----------------------------------------------------------------------------
let C=10
#-----------------------------------------------------------------------------
while [ "$C" -gt 0 ]; do
    STARTTIME=`taskset 1 date '+%s'`
    # . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
    CPU="000001"	# 1
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="000002"	# 2
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="000004"	# 3
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="000008"	# 4
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    # . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
    CPU="000010"	# 5
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="000020"	# 6
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="000040"	# 7
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="000080"	# 8
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    # . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
    CPU="000100"	# 9
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="000200"	# 10
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="000400"	# 11
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="000800"	# 12
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    # . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
    CPU="001000"	# 13
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="002000"	# 14
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="004000"	# 15
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="008000"	# 16
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    # . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
    CPU="010000"	# 17
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="020000"	# 18
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="040000"	# 19
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="080000"	# 20
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    # . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
    CPU="100000"	# 21
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="200000"	# 22
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="400000"	# 23
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    CPU="800000"	# 24
    taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    # . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#+     CPU="1000000"	# 25
#+     taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
#+     CPU="2000000"	# 26
#+     taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
#+     CPU="4000000"	# 27
#+     taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
#+     CPU="8000000"	# 28
#+     taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
#+     # . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#+     CPU="10000000"	# 29
#+     taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
#+     CPU="20000000"	# 30
#+     taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
#+     CPU="40000000"	# 31
#+     taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
#+     CPU="80000000"	# 32
#+     taskset 0x${CPU} ./check1 0x${CPU} "${CMD}" >/tmp/AAA.0x${CPU} 2>&1 &
    # . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
    wait
    ENDTIME=`taskset 1 date '+%s'`
    let REALTIME=${ENDTIME}-${STARTTIME} || true
    echo "REALTIME=${REALTIME} seconds"
    if [ "${REALTIME}" -gt 3 ]; then
	ls -lgatr /tmp/AAA* | tail -n 1
	exit 1
    fi
    let C=$C-1 || true
done
#-----------------------------------------------------------------------------
