#!/bin/bash -x
FILE=v2-1.E

make ${FILE}

sed -e 's/^  xpose/xpose/' -e '/^[ *]/d' -e 's/  *\$\$ .*$//' ${FILE} >X
( ../../../musicomp2abc/musicomp2abc --vert X X.v ; diff -U 30 -wb X X.v) 2>&1 | less
