#!/bin/bash -ex
V='b-6'
MUSICOMP2ABC=../../musicomp2abc/musicomp2abc
#-----------------------------------------------------------------------------
make "${V}.E"
#-----------------------------------------------------------------------------
${MUSICOMP2ABC} --two --fluidsynth --page 3 ${V}.E page3.fs
${MUSICOMP2ABC} --two --fluidsynth --page 4 ${V}.E page4.fs
${MUSICOMP2ABC} --two --fluidsynth --page 5 ${V}.E page5.fs
${MUSICOMP2ABC} --two --fluidsynth --page 6 ${V}.E page6.fs
${MUSICOMP2ABC} --two --fluidsynth --page 7 ${V}.E page7.fs
${MUSICOMP2ABC} --two --fluidsynth --page 8 ${V}.E page8.fs
${MUSICOMP2ABC} --two --fluidsynth --page 9 ${V}.E page9.fs
${MUSICOMP2ABC} --two --fluidsynth --page 10 ${V}.E page10.fs
${MUSICOMP2ABC} --two --fluidsynth --page 11 ${V}.E page11.fs
${MUSICOMP2ABC} --two --fluidsynth --page 12 ${V}.E page12.fs
${MUSICOMP2ABC} --two --fluidsynth --page 13 ${V}.E page13.fs
${MUSICOMP2ABC} --two --fluidsynth --page 14 ${V}.E page14.fs
${MUSICOMP2ABC} --two --fluidsynth --page 15 ${V}.E page15.fs
${MUSICOMP2ABC} --two --fluidsynth --page 16 ${V}.E page16.fs
${MUSICOMP2ABC} --two --fluidsynth --page 17 ${V}.E page17.fs
${MUSICOMP2ABC} --two --fluidsynth --page 18 ${V}.E page18.fs
${MUSICOMP2ABC} --two --fluidsynth --page 19 ${V}.E page19.fs
${MUSICOMP2ABC} --two --fluidsynth --page 20 ${V}.E page20.fs
${MUSICOMP2ABC} --two --fluidsynth --page 21 ${V}.E page21.fs
${MUSICOMP2ABC} --two --fluidsynth --page 22 ${V}.E page22.fs
${MUSICOMP2ABC} --two --fluidsynth --page 23 ${V}.E page23.fs
${MUSICOMP2ABC} --two --fluidsynth --page 24 ${V}.E page24.fs
${MUSICOMP2ABC} --two --fluidsynth --page 25 ${V}.E page25.fs
#-----------------------------------------------------------------------------
exit 0
#-----------------------------------------------------------------------------
