# $OpenBSD: Makefile,v 1.4 2002/10/28 01:38:46 naddy Exp $

PROG=ttcp

# do-install:
# 	${INSTALL_DATA_DIR} ${PREFIX}/share/doc/ttcp
# 	${INSTALL_PROGRAM} ${WRKBUILD}/ttcp ${PREFIX}/bin
# 	${INSTALL_MAN} ${WRKSRC}/ttcp.1 ${PREFIX}/man/man1
# 	${INSTALL_DATA} ${WRKSRC}/README ${PREFIX}/share/doc/ttcp

.include <bsd.prog.mk>
