#! /bin/bash
################################################################################
#                                 CONFIDENTIAL AND PROPRIETARY
#                  Copyright (C) 2007 Xiotech Corporation, All Rights Reserved
################################################################################
#
# \file     Install
# \author   Kevin Utecht
#
# Installation script for running a CCB script on an ICON appliance.
#
################################################################################


#Usage "Install -d dscId"
dscId=$2

#
# Get the current directory (temp directory created by IWS) This directory
# must hold the OpErrors.txt and OpStatus.txt files, so we must pass this
# directory into the other scripts
#

base_dir=`pwd` 


#
# Move all of the necessary files (CCBCL, etc) into temp folders
#

gzip -d CCBE.tar.gz
tar xvf CCBE.tar
gzip -d TestLibs.tar.gz
tar xvf TestLibs.tar
mv *.cmd CCBE
mv TestLibs CCBE/TestLibs
mv *.me CCBE
mv *.pl CCBE
mv *.ima CCBE
mv SystemStatusChecker CCBE/
cp -f CCBE/ccbCL.pl-linux CCBE/ccbCL.pl 
mkdir /tmp/bay
cp -fr CCBE /tmp/bay
pushd /tmp/bay/CCBE

# Make sure the health-checker is executable
chmod a+x SystemStatusChecker

#
# Execute the script
#

/bin/bash /tmp/bay/CCBE/shell.me $base_dir $dscId
popd

