#! /bin/bash
################################################################################
#                         CONFIDENTIAL AND PROPRIETARY
#         Copyright (C) 2007-2010 Xiotech Corporation, All Rights Reserved
################################################################################
#
# Installation script for kicking off an ise disk fw upgrade process
#
################################################################################

#
# process options
#
# -d        DSC Identifier.
# -p        Back-end Switch Admin Password
# -s        List of ISE to skip (comma-seperated, no spaces): 172.17.1.4,172.17.1.3,etc
#

while getopts "d:p:s:" opt; do
  case $opt in
    d  )  DSC_ID="${OPTARG}";;
    p  )  SW_PASSWORD="${OPTARG}";;
    s  )  SKIP_ISE="${OPTARG}";;
  esac
done
shift $(($OPTIND - 1))

if [[ ${DSC_ID} == "" ]]
then
  OPT_ERR=1
fi

if [[ ${SKIP_ISE} == "" ]]
then
  SKIP_ISE = "NONE"
fi


#
# check parameters
#

if [[ ${OPT_ERR} == "1" ]]
then
  echo "Install script."
  echo "Usage: $(basename $0) -d <DSC ID>"
  exit 1
fi



#
# Get the current directory (temp directory created by IWS) This directory
# must hold the OpErrors.txt and OpStatus.txt files, so we must pass this
# directory into the other scripts
#

base_dir=`pwd` 


#
# Move all of the necessary files (CCBCL, etc) into temp folders
#
mkdir -p /tmp/ise
# Remove any ima files leftover from a previous upgrade operation
rm /tmp/ise/*.ima
tar jxf E.tbz2 -C / ; ldconfig
cp CCBE.tbz2 /tmp/ise
cp ccbCL.ini /tmp/ise
cp ise_disk_upgrader /tmp/ise
cp ise_disk.cfg /tmp/ise
cp disk_do_many_ises /tmp/ise
cp SystemStatusChecker /tmp/ise
cp check_warm_booted_sw /tmp/ise
cp *.ima /tmp/ise
mv /root/.ssh/known_hosts /root/.ssh/known_hosts.save || true
pushd /tmp/ise
chmod a+x disk_do_many_ises ise_disk_upgrader SystemStatusChecker check_warm_booted_sw
tar jxvf CCBE.tbz2
mv ccbCL.ini CCBE/


#
# Execute the script
#
# Note: Output is no longer redirected. Instead, it will simply insert
#       itself into the /var/log/XioWebService.xiolog file. The benefit
#       here is that the "log" is not lost after the script completes
#


if [[ ${SW_PASSWORD} == "" ]]
then
  echo "Executing /usr/bin/perl ./disk_do_many_ises -c production -b $base_dir -d ${DSC_ID} -s {$SKIP_ISE}"
  /usr/bin/perl ./disk_do_many_ises -c production -b $base_dir -d ${DSC_ID} -s {$SKIP_ISE}
else
  echo "Executing /usr/bin/perl ./disk_do_many_ises -c production -b $base_dir -d ${DSC_ID} -p <custom_password>  -s {$SKIP_ISE}"
  /usr/bin/perl ./disk_do_many_ises -c production -b $base_dir -d ${DSC_ID} -p ${SW_PASSWORD} -s {$SKIP_ISE}
fi

popd

