(Search via: 'yum search multipath')
To install multipath on redhat:
    redhat> yum install device-mapper-multipath
    here> scp multipath.conf root@10.0.11.36:/etc/multipath.conf
    redhat> service multipathd restart

To install iscsiadm on redhat:
    redhat> yum install iscsi-initiator-utils


test FC:
    multipath -ll
    287b48b604ef97bd86c9ce9009399e675 dm-3 Nimble,Server
    size=200G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
    |-+- policy='round-robin 0' prio=50 status=active
    | |- 13:0:1:0 sdf 8:80 active ready running
    | `- 12:0:1:0 sdc 8:32 failed faulty running
    `-+- policy='round-robin 0' prio=1 status=enabled
      |- 13:0:0:0 sde 8:64 active ghost running
      `- 12:0:0:0 sdd 8:48 failed faulty running

    dmesg | grep blocks
    ...
    sd 13:0:0:0: [sde] 419430400 512-byte logical blocks: (214 GB/200 GiB)
    sd 13:0:1:0: [sdf] 419430400 512-byte logical blocks: (214 GB/200 GiB)
    sd 12:0:1:0: [sdc] 419430400 512-byte logical blocks: (214 GB/200 GiB)
    sd 12:0:0:0: [sdd] 419430400 512-byte logical blocks: (214 GB/200 GiB)

    cat /sys/class/fc_host/host*/port_state


