#!/bin/bash -ex

# Create FC 14G migration from 25eb8ab90056482af6c9ce9009399e675 to 21ab345f355a8287b6c9ce9009399e675
# Create 10G migration from 2642126ca1625f8b16c9ce9009399e675 to 13g 3624a93708a2d08dc5cfe441e0001103b

# Create Storage System
SSSCSI=`./m4.py --brief storage systems create 'FC storage system name' | awk '{print $1}'`

# Create Storage Protocol ID.  Choose WWN 0x56c9ce907fc86f03 -- strange, not used WWN.
SPSCSI=`./m4.py --brief storage protocols create ${SSSCSI} SCSI 'SomethingSCSI' | awk '{print $1}'`

# Create Project.
PNSCSI="Scripted SCSI project for two FC to two FC migrations"
JNSCSI1="job to copy FC 14g to FC 14g"
JNSCSI2="job to copy FC 10g to FC 13g"
./m4.py p c "${PNSCSI}"

# Create Job.
./m4.py j c "${PNSCSI}" block://25eb8ab90056482af6c9ce9009399e675 block://21ab345f355a8287b6c9ce9009399e675 "${JNSCSI1}"
./m4.py j c "${PNSCSI}" block://2642126ca1625f8b16c9ce9009399e675 block://3624a93708a2d08dc5cfe441e0001103b "${JNSCSI2}"

# Run the jobs.
./m4.py jobs run "${JNSCSI1}" "${JNSCSI2}"

exit 0
#-----------------------------------------------------------------------------
