#!/bin/bash -ex
# Get all jobs, stop them, then delete them.
J=`./m4.py --brief jobs list`
./m4.py jobs stop $J

set +x
# Poll for all jobs stopped, before deleting jobs.
while true; do
    R=`./m4.py -o jobs list $J | awk '{print $3}' | sed -e 's/STOPPED//' -e "s/[ ']//g"`
    if [ "$R" == '' ]; then
        break
    fi
    sleep 3
done
echo 'JOBs stopped!'
set -x

./m4.py jobs delete $J

# Get all projects, then delete them.
P=`./m4.py --brief projects list`
./m4.py proj delete ${P}

# Get all storage files, then delete them.
SF=`./m4.py --brief storage files | awk '{print $1}'`
./m4.py storage files delete ${SF}

# Get all storage protocols, then delete them.
SP=`./m4.py --brief storage protocols | awk '{print $1}'`
./m4.py storage protocols delete ${SP}

# Get all storage systems, then delete them.
SS=`./m4.py --brief storage systems | awk '{print $1}'`
./m4.py storage systems delete ${SS}

# Make sure nothing present -- other than automatic devices.
./m4.py jobs list
./m4.py projects list
./m4.py --brief storage devices list
./m4.py --brief storage files list
./m4.py --brief storage protocols list
./m4.py --brief storage systems list

exit 0
#-----------------------------------------------------------------------------
