#!/bin/bash -x
#-- make rm_files_w2008_m4-v1
#-- make rm_files_w2012_m4-v1
#-- make rm_files_w2016_m4-v1
#-- make rm_files_w2019_m4-v1
#-- make rm_files_na116_cifs_v1
#-- make rm_files_is100_m4_v1
#-- make rm_files_cdot113_m4_cdot_01

make rm_files_w2008_m4-v2
make rm_files_w2012_m4-v2
make rm_files_w2016_m4-v2
make rm_files_w2019_m4-v2
make rm_files_na116_cifs_v2
make rm_files_is100_m4_v2
make rm_files_cdot113_m4_cdot_02
