#!/bin/bash -ex

# Create Storage System
SSNFS=`./m4.py --brief storage systems create 'NFS storage system name' | awk '{print $1}'`

# Create Storage Protocol ID.
SPNFS=`./m4.py --brief storage protocols create ${SSNFS} NFS 172.22.14.103 'SomethingNFS' | awk '{print $1}'`

# Create Project.
PNNFS="Scripted NFS project for 10g to 10g migration"
JNNFS1="job to copy NFS v1 10g to NFS v2 10g"
JNNFS2="job to copy NFS v3 10g to NFS v4 10g"
./m4.py p c "${PNNFS}"

# Create Job.
./m4.py j c "${PNNFS}" nfs://172.22.14.103/vol/m4_1G_nfs_v1 nfs://172.22.14.103/vol/m4_1G_nfs_v3 "${JNNFS1}"
./m4.py j c "${PNNFS}" nfs://172.22.14.103/vol/m4_1G_nfs_v2 nfs://172.22.14.103/vol/m4_1G_nfs_v4 "${JNNFS2}"

# Run the jobs.
./m4.py jobs run "${JNNFS1}" "${JNNFS2}"

exit 0
#-----------------------------------------------------------------------------
# Add Storage Systems
./m4.py storage systems create SMB_stuff
#      Storage System Created 50 - "SMB_stuff"
./m4.py storage protocols create 50 SMB 172.22.14.116 "AD/LoginName" "BlueSnake" "SomethingSMB"
#      Storage Protocol Created 22 - "SomethingSMB"
./m4.py storage systems create NFS_stuff
#      Storage System Created 51 - "NFS_stuff"
./m4.py storage protocols create 51 NFS 172.22.13.103 "SomethingNFS"
#      Storage Protocol Created 23 - "SomethingNFS"
# Create projects and jobs.
PN="Scripted SMB project for na116 v1 to na116 v2"
JN="job to copy na116 v1 to na116 v1"
# Create the project - note SMB version 2.0 source and destination.
./m4.py p c "${PN}" 2.0 2.0
#     Project Created 512
# Create a job for doing the migration.
./m4.py jobs create "${PN}" cifs://172.22.14.116/v1 cifs://172.22.14.116/v2 "${JN}"
#     Job ID: 596
# Run the job for doing the migration.
./m4.py jobs run "${JN}"
#-----------------------------------------------------------------------------
