#!/bin/bash -ex

# Do 7 CIFS/SMB migrations.

# Create Storage System
SSSMB=`./m4.py --brief storage systems create 'SMB storage system name' | awk '{print $1}'`

# Create Storage Protocol IDs.
SPSMB1=`./m4.py --brief storage protocols create ${SSSMB} SMB 172.22.12.140 "AD/Parsec.Backup" "Cobra!Indigo" 'Something-172.22.12.140' | awk '{print $1}'`
SPSMB2=`./m4.py --brief storage protocols create ${SSSMB} SMB 172.22.12.143 "AD/Parsec.Backup" "Cobra!Indigo" 'Something-172.22.12.143' | awk '{print $1}'`
SPSMB3=`./m4.py --brief storage protocols create ${SSSMB} SMB 172.22.12.144 "AD/Parsec.Backup" "Cobra!Indigo" 'Something-172.22.12.144' | awk '{print $1}'`
SPSMB4=`./m4.py --brief storage protocols create ${SSSMB} SMB 172.22.12.112 "AD/Parsec.Backup" "Cobra!Indigo" 'Something-172.22.12.112' | awk '{print $1}'`
SPSMB5=`./m4.py --brief storage protocols create ${SSSMB} SMB 172.22.14.116 "AD/Parsec.Backup" "Cobra!Indigo" 'Something-172.22.14.116' | awk '{print $1}'`
SPSMB6=`./m4.py --brief storage protocols create ${SSSMB} SMB 172.22.13.100 "AD/Parsec.Backup" "Cobra!Indigo" 'Something-172.22.13.100' | awk '{print $1}'`
SPSMB7=`./m4.py --brief storage protocols create ${SSSMB} SMB 172.22.15.113 "AD/Parsec.Backup" "Cobra!Indigo" 'Something-172.22.15.113' | awk '{print $1}'`

# Create Project.
PNSMB1="Scripted SMB project 1."
./m4.py p c "${PNSMB1}" default 2.0
JNSMB1="job to copy SMB 172.22.12.112 v1 to 172.22.14.116 v2"
./m4.py j c "${PNSMB1}" cifs://172.22.12.112/m4-v1 cifs://172.22.14.116/cifs_v2 "${JNSMB1}"

PNSMB2="Scripted SMB project 2."
./m4.py p c "${PNSMB2}" default default
JNSMB2="job to copy SMB 172.22.12.144 v1 to 172.22.12.112 v2"
./m4.py j c "${PNSMB2}" cifs://172.22.12.144/m4-v1 cifs://172.22.12.112/m4-v2 "${JNSMB2}"

PNSMB3="Scripted SMB project 3."
./m4.py p c "${PNSMB3}" default default
JNSMB3="job to copy SMB 172.22.12.143 v1 to 172.22.12.144 v2"
./m4.py j c "${PNSMB3}" cifs://172.22.12.143/m4-v1 cifs://172.22.12.144/m4-v2 "${JNSMB3}"

PNSMB4="Scripted SMB project 4."
./m4.py p c "${PNSMB4}" default default
JNSMB4="job to copy SMB 172.22.12.140 v1 to 172.22.12.143 v2"
./m4.py j c "${PNSMB4}" cifs://172.22.12.140/m4-v1 cifs://172.22.12.143/m4-v2 "${JNSMB4}"

PNSMB5="Scripted SMB project 5."
./m4.py p c "${PNSMB5}" 2.0 default
JNSMB5="job to copy SMB 172.22.14.116 v1 to 172.22.15.113 v2"
./m4.py j c "${PNSMB5}" cifs://172.22.14.116/cifs_v1 cifs://172.22.15.113/m4_cdot_02 "${JNSMB5}"

PNSMB6="Scripted SMB project 6."
./m4.py p c "${PNSMB6}" default default
JNSMB6="job to copy SMB 172.22.15.113 v1 to 172.22.13.100 v2"
./m4.py j c "${PNSMB6}" cifs://172.22.15.113/m4_cdot_01 cifs://172.22.13.100/m4_v2 "${JNSMB6}"

PNSMB7="Scripted SMB project 7."
./m4.py p c "${PNSMB7}" default default
JNSMB7="job to copy SMB 172.22.13.100 v1 to 172.22.12.140 v2"
./m4.py j c "${PNSMB7}" cifs://172.22.13.100/m4_v1 cifs://172.22.12.140/m4-v2 "${JNSMB7}"

# Run the jobs.
./m4.py jobs run "${JNSMB1}" "${JNSMB2}" "${JNSMB3}" "${JNSMB4}" "${JNSMB5}" "${JNSMB6}" "${JNSMB7}"

exit 0
#-----------------------------------------------------------------------------
