#!/bin/bash -ex

dd if=/dev/zero bs=1M of=/dev/mapper/21ab345f355a8287b6c9ce9009399e675 | true
dd if=/dev/zero bs=1M of=/dev/mapper/3624a93708a2d08dc5cfe441e0001103b | true

dd if=/dev/urandom bs=1M of=/dev/mapper/25eb8ab90056482af6c9ce9009399e675 | true
dd if=/dev/urandom bs=1M of=/dev/mapper/2642126ca1625f8b16c9ce9009399e675 | true

exit 0
#-----------------------------------------------------------------------------
