#!/bin/bash -ex
#   iscsiadm -m discovery ; iscsiadm -m node ; iscsiadm -m session
# 192.168.14.103 & 172.22.14.103
# 192.168.14.180
# 192.168.14.186

# Create Storage System
SSiSCSI=`./m4.py --brief storage systems create 'iSCSI storage system name' | awk '{print $1}'`

# Create Storage Protocol ID.
SPiSCSI1=`./m4.py --brief storage protocols create ${SSiSCSI} iSCSI 192.168.14.180 '180-iSCSI' | awk '{print $1}'`
SPiSCSI2=`./m4.py --brief storage protocols create ${SSiSCSI} iSCSI 192.168.14.186 '186-iSCSI' | awk '{print $1}'`

# Create Project.
PNiSCSI="Scripted iSCSI project for two migrations"
JNiSCSI1="job to copy iSCSI 4g 360a9800044307a63352b4d4878544e61 to iSCSI 360a9800044307a63352b4d4878544e63"
JNiSCSI2="job to copy iSCSI 15g 360a9800044307a63352b4d4878544e58 to iSCSI 360a9800044307a63352b4d4878544e5a"
./m4.py p c "${PNiSCSI}"

# Create Job.
./m4.py j c "${PNiSCSI}" block://360a9800044307a63352b4d4878544e61 block://360a9800044307a63352b4d4878544e63 "${JNiSCSI1}"
./m4.py j c "${PNiSCSI}" block://360a9800044307a63352b4d4878544e58 block://360a9800044307a63352b4d4878544e5a "${JNiSCSI2}"

# Run the jobs.
./m4.py jobs run "${JNiSCSI1}" "${JNiSCSI2}"

exit 0
#-----------------------------------------------------------------------------


{
  "protocols": [
    {
      "definition": {
        "host": "192.168.14.180",
        "type": "SCSI"
      },
      "id": 72,
      "message": "discovery successful",
      "name": "some iSCSI 14.180",
      "scaninprogress": false,
      "systemid": 83
    },
    {
      "definition": {
        "host": "192.168.14.186",
        "type": "SCSI"
      },
      "id": 73,
      "message": "discovery successful",
      "name": "some iSCSI 14.186",
      "scaninprogress": false,
      "systemid": 83
    }
  ]
}

{
  "jobs": [
    {
      "destination": {
        "serialnumber": "360a9800044307a63352b4d4878544e61",
        "type": "BLOCK"
      },
      "encrypt": false,
      "end": null,
      "errors": 0,
      "id": 661,
      "message": null,
      "name": "4g iSCSI migration",
      "projectid": 585,
      "source": {
        "serialnumber": "360a9800044307a63352b4d4878544e63",
        "type": "BLOCK"
      },
      "start": null,
      "state": "STOPPED",
      "status": "NOTRUN",
      "warnings": 0
    }
  ]
}
------------------------------------------------------------------------------

2020-12-16_15-45-05
pxrest created:
	
Response body
Download

{
  "systems": [
    {
      "id": 90,
      "name": "iSCSI storage system name"
    }
  ]
}
