#!/bin/bash -ex
# Update creationtime and utimes on a directory and sublevels.
#-----------------------------------------------------------------------------
TIMEFORMAT='real %R sec  user %U sec  system %S sec - %%%P CPU usage'
#-----------------------------------------------------------------------------
W=`pwd`
P=${W}/`dirname $0`
#-----------------------------------------------------------------------------
S="$1"
D="$2"
if [ "${S}" == '' -o "${D}" == '' ]; then
    echo 'Usage: Source_Directory Destination_directory'
    exit 1
fi
#-----------------------------------------------------------------------------
# Get a list of files, in reverse order -- so directory is after files in directory.
rm -f /tmp/AAA.POST_LHR
( cd "${D}" && find . | tac | sed -e "s/^\(.*\)$/abc '\1'/" > /tmp/AAA.POST_LHR )
#-----------------------------------------------------------------------------
abc()
{
    f="$1"
    if [ "${f}" != '.' -a "${f}" != '..' ]; then
        # NTFS creationtime value.
        CT=`getfattr -n user.cifs.creationtime -e hex -- "${S}/${f}" | tail -n +2 | sed -e 's/^.*=//' || true`
        setfattr -n user.cifs.creationtime -v "${CT}" -- "${D}/${f}" || true

        # Set dates to reference file. (Assumes reference filesystem is read-only.)
        touch --reference="${S}/${f}" "${D}/${f}" || true
    fi
}
#-----------------------------------------------------------------------------
directory_attr_plus()
{
    SRC="$1"
    DST="$2"
    CT=`getfattr -n user.cifs.creationtime -e hex -- ${SRC} | tail -n +2 | sed -e 's/^.*=//' || true`
    setfattr -n user.cifs.creationtime -v ${CT} -- ${DST} || true
    touch --reference=${SRC} ${DST} || true
}
#-----------------------------------------------------------------------------
source /tmp/AAA.POST_LHR
#-----------------------------------------------------------------------------
directory_attr_plus "${S}" "${D}"
#-----------------------------------------------------------------------------
echo "Done with $0"
exit 0
#-----------------------------------------------------------------------------
