#!/bin/bash -epx
#-----------------------------------------------------------------------------
source 172.22.14.10/ENV
#-----------------------------------------------------------------------------
NJOBS=2
JOBS='1055 1056'
#-----------------------------------------------------------------------------
# a) loop ...
#    b) delete all files on destination.
#    c) Run the 4 jobs till they are finished.
# d) end loop.
#-----------------------------------------------------------------------------
systemctl unmask smb
systemctl enable smb
systemctl start smb
#-----------------------------------------------------------------------------
DOMAIN='AD'
USER='Parsec.Backup'
PW='Cobra!Indigo'
FIRST='mount -t cifs '
SECOND='//172.22.13.100/'
THIRD='/mnt/netapp/'
FOURTH="-o rw,username=${USER},password=${PW},domain=${DOMAIN},nosuid,nodev,noexec,vers=3.1.1,cache=none,uid=0,noforceuid,gid=0,noforcegid,file_mode=0755,dir_mode=0755,soft,nounix,noperm,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1"
#-- mount -t cifs //172.22.13.100/m4_v1 /mnt/172.22.13.100/m4_v1 -o username=Parsec.Backup,password=Cobra!Indigo,domain=AD,vers=default,noperm,nosetuids,nodev,noexec,cache=none,user_xattr,cifsacl,nomapchars,serverino,soft,nounix,acl,nodfs
#-----------------------------------------------------------------------------
wait_for_jobs () {
    while [ 0 ]; do
	N=`./m4.py --one-line jobs list | grep -c "'STOPPED'"` || true
	if [ $N -eq ${NJOBS} ]; then
	    break
	fi
	sleep 1
    done
}
#-----------------------------------------------------------------------------
delete_lhr_files () {
    A="$1"
    while [ \! -z "$A" ]; do
        echo "A=$A"
        (cd /media/parsecdata/lhr/ && rm -rf ${A}/* ) || true
        shift
        A="$1"
    done
}
#-----------------------------------------------------------------------------
delete_all_files () {
    A="$1"
    while [ \! -z "$A" ]; do
        echo "A=$A"
	mkdir -p ${THIRD}${A}
        ${FIRST} ${SECOND}${A} ${THIRD}${A} ${FOURTH}
        (cd ${THIRD}${A} && rm -rf *) || true
	umount ${THIRD}${A}
        shift
        A="$1"
    done
}
#-----------------------------------------------------------------------------
set +x
while [ 0 ] ; do
    delete_all_files m4_v1 m4_v2
    delete_lhr_files ${JOBS}
    ./m4.py jobs run ${JOBS}
    ./m4.py jobs list --one-line
    sleep 1
    wait_for_jobs
    sleep 60
done
echo done
#-----------------------------------------------------------------------------
