#!/bin/bash -epu
#-----------------------------------------------------------------------------
source 172.22.14.10/ENV
#-----------------------------------------------------------------------------
#-- NJOBS=2
#-- JOBS='1055 1056'
NJOBS=8
JOBS='1057 1058 1059 1060 1061 1062 1063 1064'
#-----------------------------------------------------------------------------
WHERE=172.22.205.65
#-----------------------------------------------------------------------------
# a) loop ...
#    b) delete all files on destination.
#    c) Run the 8 jobs till they are finished.
# d) end loop.
#-----------------------------------------------------------------------------
systemctl unmask smb
systemctl enable smb
systemctl start smb
#-----------------------------------------------------------------------------
delete_all_lhr_files () {
    (cd /media/parsecdata/lhr/ && rm -rf */* ) || true
}
#-----------------------------------------------------------------------------
delete_all_files_PURE_lhr () {
    A="$1"
    B="$2"
    python3 /px/libexec/sched_mntfs.py dst ${A}
    (cd /mfs/${A}/dst__${WHERE}__${B} && rm -rf *) || true
   umount /mfs/${A}/dst__${WHERE}__${B}
}
#-----------------------------------------------------------------------------
wait_for_jobs () {
    while [ 0 ]; do
	N=`./m4.py --one-line jobs list | grep -c "'STOPPED'"` || true
	if [ $N -eq ${NJOBS} ]; then
	    break
	fi
	echo "$N != ${NJOBS}"
	sleep 30
    done
}
#-----------------------------------------------------------------------------
while [ 0 ] ; do
    echo "Delete LHR database files..."
    delete_all_lhr_files

    echo "Delete files on Pure FA..."
    delete_all_files_PURE_lhr 1057 m4_src01
    delete_all_files_PURE_lhr 1058 m4_src02
    delete_all_files_PURE_lhr 1059 m4_src03
    delete_all_files_PURE_lhr 1060 m4_src04
    delete_all_files_PURE_lhr 1061 m4_dest01
    delete_all_files_PURE_lhr 1062 m4_dest02
    delete_all_files_PURE_lhr 1063 m4_dest03
    delete_all_files_PURE_lhr 1064 m4_dest04

    echo "Start jobs running..."
    date
    ./m4.py jobs run ${JOBS}
    ./m4.py jobs list --one-line
    sleep 3
    wait_for_jobs
    echo 'Jobs finished'
    date
    echo ""
    sleep 60
done
echo done
#-----------------------------------------------------------------------------
exit 0
#-----------------------------------------------------------------------------
