#!/bin/bash -epx
#-----------------------------------------------------------------------------
source 172.22.14.10/ENV
#-----------------------------------------------------------------------------
NJOBS=2
JOBS='1055 1056'
#-----------------------------------------------------------------------------
# a) loop ...
#    b) delete all files on destination.
#    c) Run the 4 jobs till they are finished.
# d) end loop.

#-----------------------------------------------------------------------------
DOMAIN='AD'
USER='Parsec.Backup'
PW='Cobra!Indigo'
FIRST='mount -t cifs '
SECOND='//172.22.13.100/'
THIRD='/mnt/netapp/'
FOURTH="rw,nosuid,nodev,noexec,vers=3.1.1,cache=none,password=${PW},username=${USER},uid=0,noforceuid,gid=0,noforcegid,file_mode=0755,dir_mode=0755,soft,nounix,noperm,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1,domain=${DOMAIN}"
#-----------------------------------------------------------------------------
wait_for_jobs () {
    set +x
    while [ 0 ]; do
	N=`./m4.py --one-line jobs list | grep -c "'STOPPED'"`
	if [ $N -eq ${NJOBS} ]; then
	    break
	fi
    done
    set -x
}
#-----------------------------------------------------------------------------
delete_all_files () {
    set +x
    A=$1
    while [ \! -z "$A" ]; do
        echo A=$A
        ${FIRST} ${SECOND}${A} ${THIRD}${A} ${FOURTH}
        (cd ${THIRD}${A} && rm -rf *)
        shift
        A=$1
    done
    set -x
}
#-----------------------------------------------------------------------------
#-- while [ 0 ] ; do
#+    delete_all_files m4_v1 m4_v2
    ./m4.py jobs run ${JOBS}
    sleep 10
    wait_for_jobs
#-- done
echo done
#-----------------------------------------------------------------------------
