#!/bin/bash -ex
# Get all jobs, stop them, then delete them.
J=`./m4.py --brief jobs list`
./m4.py jobs stop $J

# NOTDONEYET - poll for jobs stopped, before deleting jobs.

./m4.py jobs delete $J

# Get all projects, then delete them.
P=`./m4.py --brief projects list`
./m4.py proj delete ${P}

# Get all storage files, then delete them.
SF=`./m4.py --brief storage files | awk '{print $1}'`
./m4.py storage files delete ${SF}

# Get all storage protocols, then delete them.
SP=`./m4.py --brief storage protocols | awk '{print $1}'`
./m4.py storage protocols delete ${SP}

# Get all storage systems, then delete them.
SS=`./m4.py --brief storage systems | awk '{print $1}'`
./m4.py storage systems delete ${SS}

# Make sure nothing present -- other than automatic devices.
./m4.py jobs list
./m4.py projects list
./m4.py --brief storage devices list
./m4.py --brief storage files list
./m4.py --brief storage protocols list
./m4.py --brief storage systems list

# Start creating FC 14G migration from:
#     25eb8ab90056482af6c9ce9009399e675
# to:
#     21ab345f355a8287b6c9ce9009399e675

# Create Storage System
SSSCSI=`./m4.py --brief storage systems create 'FC storage system name' | awk '{print $1}'`

# Create Storage Protocol ID.  Choose WWN 0x56c9ce907fc86f03
SPSCSI=`./m4.py --brief storage protocols create ${SSSCSI} SCSI 'SomethingSCSI' | awk '{print $1}'`

# Create Project.
PNSCSI="Scripted SCSI project for 14g to 14g migration"
JNSCSI="job to copy FC 14g to FC 14g"
./m4.py p c "${PNSCSI}"

# Create Job.
./m4.py j c "${PNSCSI}" block://25eb8ab90056482af6c9ce9009399e675 block://21ab345f355a8287b6c9ce9009399e675 "${JNSCSI}"

# Run the job.
./m4.py jobs run "${JNSCSI}"

exit 0
#-----------------------------------------------------------------------------
# Add Storage Systems
./m4.py storage systems create SMB_stuff
#      Storage System Created 50 - "SMB_stuff"
./m4.py storage protocols create 50 SMB 172.22.14.116 "AD/LoginName" "BlueSnake" "SomethingSMB"
#      Storage Protocol Created 22 - "SomethingSMB"
./m4.py storage systems create NFS_stuff
#      Storage System Created 51 - "NFS_stuff"
./m4.py storage protocols create 51 NFS 172.22.13.103 "SomethingNFS"
#      Storage Protocol Created 23 - "SomethingNFS"
# Create projects and jobs.
PN="Scripted SMB project for na116 v1 to na116 v2"
JN="job to copy na116 v1 to na116 v1"
# Create the project - note SMB version 2.0 source and destination.
./m4.py p c "${PN}" 2.0 2.0
#     Project Created 512
# Create a job for doing the migration.
./m4.py jobs create "${PN}" cifs://172.22.14.116/v1 cifs://172.22.14.116/v2 "${JN}"
#     Job ID: 596
# Run the job for doing the migration.
./m4.py jobs run "${JN}"
#-----------------------------------------------------------------------------
