#!/bin/bash -x
IP=ad.parsec.lab
# IP=172.22.1.207
smbclient --workgroup=AD --user=Parsec.Admin --list=${IP}
#  smbclient --workgroup=AD --user=Parsec.Backup --list=172.22.13.100 -m NT1

rpcclient -U Parsec.Backup ${IP} srvinfo
rpcclient -U Parsec.Backup ${IP} enumdomusers
rpcclient -U Parsec.Backup ${IP} enumalsgroups domain
rpcclient -U Parsec.Backup ${IP} enumalsgroups builtin
rpcclient -U Parsec.Backup ${IP} enumdomains
rpcclient -U Parsec.Backup ${IP} enumprivs
rpcclient -U Parsec.Backup ${IP} lookupnames Parsec.Backup
rpcclient -U Parsec.Backup ${IP} queryuser 0x1f4
rpcclient -U Parsec.Backup ${IP} netshareenumall
rpcclient -U Parsec.Backup ${IP} netsharegetinfo m4-v2
rpcclient -U Parsec.Backup ${IP} netname: m4-v2
# 	remark:
# 	path:	C:\m4-v2
# 	password:	(null)
# 	type:	0x0
# 	perms:	0
# 	max_uses:	-1
# 	num_uses:	0
# revision: 1
# type: 0x8004: SEC_DESC_DACL_PRESENT SEC_DESC_SELF_RELATIVE
# DACL
# 	ACL	Num ACEs:	1	revision:	2
# 	---
# 	ACE
# 		type: ACCESS ALLOWED (0) flags: 0x03 SEC_ACE_FLAG_OBJECT_INHERIT  SEC_ACE_FLAG_CONTAINER_INHERIT
# 		Specific bits: 0x1ff
# 		Permissions: 0x1f01ff: SYNCHRONIZE_ACCESS WRITE_OWNER_ACCESS WRITE_DAC_ACCESS READ_CONTROL_ACCESS DELETE_ACCESS
# 		SID: S-1-1-0
# 
# 	Owner SID:	S-1-5-32-544

