#!/bin/bash -x
#-----------------------------------------------------------------------------
uname -a
#-----------------------------------------------------------------------------
# IP=172.22.14.116
# VOL=cifs_v2
#-----------------------------------------------------------------------------
try_mount()
{
    IP=$1
    VOL=$2
    echo "Try mounting ${VOL} from ${IP}"
    mkdir -p /mnt/${IP}/${VOL} || true
    umount /mnt/${IP}/${VOL} || true
    mount -t cifs //${IP}/${VOL} /mnt/${IP}/${VOL} -o 'username=Parsec.Backup,vers=1.0,domain=AD' || true
    umount /mnt/${IP}/${VOL} || true
    mount -t cifs //${IP}/${VOL} /mnt/${IP}/${VOL} -o 'username=Parsec.Backup,vers=2.0,domain=AD' || true
    umount /mnt/${IP}/${VOL} || true
    mount -t cifs //${IP}/${VOL} /mnt/${IP}/${VOL} -o 'username=Parsec.Backup,vers=2.1,domain=AD' || true
    umount /mnt/${IP}/${VOL} || true
    mount -t cifs //${IP}/${VOL} /mnt/${IP}/${VOL} -o 'username=Parsec.Backup,vers=3,domain=AD' || true
    umount /mnt/${IP}/${VOL} || true
    mount -t cifs //${IP}/${VOL} /mnt/${IP}/${VOL} -o 'username=Parsec.Backup,vers=3.0,domain=AD' || true
    umount /mnt/${IP}/${VOL} || true
    mount -t cifs //${IP}/${VOL} /mnt/${IP}/${VOL} -o 'username=Parsec.Backup,vers=3.0.2,domain=AD' || true
    umount /mnt/${IP}/${VOL} || true
    mount -t cifs //${IP}/${VOL} /mnt/${IP}/${VOL} -o 'username=Parsec.Backup,vers=3.1.1,domain=AD' || true
    umount /mnt/${IP}/${VOL} || true
}
#-----------------------------------------------------------------------------
try_mount 172.22.12.140 m4-v1
try_mount 172.22.12.143 m4-v1
try_mount 172.22.12.144 m4-v1
try_mount 172.22.12.112 m4-v1
try_mount 172.22.14.116 cifs_v2
try_mount 172.22.13.100 m4_v1
try_mount 172.22.15.113 m4_cdot_01

#-----------------------------------------------------------------------------
exit 0
#-----------------------------------------------------------------------------
Possible:
    vers=1 works.
        1.0
        2.0
        2.1
        3   One of the below... negotations.
            3.0
            3.0.2
            3.1.1
#-----------------------------------------------------------------------------
