#!/bin/bash
doit()
{
    /usr/bin/echo "pid $$ md-run-timer doit entered" > /dev/kmsg
    /usr/bin/echo "pid $$ md-run-timer starting sleep 1" > /dev/kmsg
    /usr/bin/sleep 1
    /usr/bin/echo "pid $$ md-run-timer starting sleep 32" > /dev/kmsg
    /usr/bin/sleep 32
    /usr/bin/echo "pid $$ md-run-timer after sleep 32" > /dev/kmsg
    F=`builtin cd /sys/devices/virtual/block/; echo md*`
    /usr/bin/echo "pid $$ md-run-timer raids=$F" > /dev/kmsg
    for RAID in $F; do
        if [ -e "/sys/devices/virtual/block/$RAID/md/array_state" ]; then
            read v < /sys/devices/virtual/block/$RAID/md/array_state
            if [ "$v" == "inactive" ]; then
                /usr/bin/echo "pid $$ md-run-timer $RAID is inactive, attempting to start" > /dev/kmsg
                /usr/sbin/mdadm -R /dev/$RAID > /dev/kmsg || true
                sleep 1
	    else
                /usr/bin/echo "pid $$ md-run-timer $RAID is '$v' NOT starting" > /dev/kmsg
            fi
        fi
    done
    /usr/bin/echo "pid $$ md-run-timer done checking" > /dev/kmsg
    unset F
    unset RAID
    unset v
}
(doit || true ) >/dev/null 2>&1 &
disown -a
exit 0
