#!/bin/bash -ex

# abcm2ps -l -M -j 1 -b 0 v1-1.abc -i 

#-- -l = landscape abcm2ps -l -M -j 1 -b 0 v1-1.abc -i 
#-- abcm2ps -M -j 1 -b 0 v1-1.abc -i 

#-- abcm2ps -l -M -j 1 -b 0 v1-1.abc -i 
abcm2ps -l -M -b 0 v1-1.abc -i 
