#!/bin/bash -ex
#-----------------------------------------------------------------------------
# ./diff.w2019.m4-v1.and.na116.cifs_v2
#NEW1	INS='SMB-Server-2019.ad.parsec.lab' IPS='172.22.12.112' NAMES='w2019' SS="m4-v1" \
#NEW1	IND='172.22.14.116'                 IPD='172.22.14.116' NAMED='na116' DS="cifs_v2" \
#NEW1		./POST-lhr
#-----------------------------------------------------------------------------
# ./diff.na116.cifs_v1.and.na103.m4_smb_v2
#NEW2	INS='172.22.14.116'                 IPS='172.22.14.116' NAMES='na116' SS="cifs_v1" \
#NEW2	IND='172.22.15.103'                 IPD='172.22.15.103' NAMED='na103' DS="m4_smb_v2" \
#NEW2		./POST-lhr
#-----------------------------------------------------------------------------
# ./diff.na103.m4_smb_v1.and.is100.m4_v2
#NEW3	INS='172.22.15.103'                 IPS='172.22.15.103' NAMES='na103' SS="m4_smb_v1" \
#NEW3	IND='172.22.13.100'                 IPD='172.22.13.100' NAMED='is100' DS="m4_v2" \
#NEW3		./POST-lhr
#-----------------------------------------------------------------------------
# ./diff.is100.m4_v1.and.w2008.m4-v2
INS='172.22.13.100'                 IPS='172.22.13.100' NAMES='is100' SS="m4_v1" \
IND='SMB-Server-2008.ad.parsec.lab' IPD='172.22.12.140' NAMED='w2008' DS="m4-v2" \
	./POST-lhr
exit 1
#-----------------------------------------------------------------------------
# ./diff.w2008.m4-v1.and.w2012.m4-v2
INS='SMB-Server-2008.ad.parsec.lab' IPS='172.22.12.140' NAMES='w2008' SS="m4-v1" \
IND='SMB-Server-2012.ad.parsec.lab' IPD='172.22.12.143' NAMED='w2012' DS="m4-v2" \
	./POST-lhr
#-----------------------------------------------------------------------------
# ./diff.w2012.m4-v1.and.w2016.m4-v2
INS='SMB-Server-2012.ad.parsec.lab' IPS='172.22.12.143' NAMES='w2012' SS="m4-v1" \
IND='SMB-Server-2016.ad.parsec.lab' IPD='172.22.12.144' NAMED='w2016' DS="m4-v2" \
	./POST-lhr
#-----------------------------------------------------------------------------
# ./diff.w2016.m4-v1.and.w2019.m4-v2
INS='SMB-Server-2016.ad.parsec.lab' IPS='172.22.12.144' NAMES='w2016' SS="m4-v1" \
IND='SMB-Server-2019.ad.parsec.lab' IPD='172.22.12.112' NAMED='w2019' DS="m4-v2" \
	./POST-lhr
