#!/bin/bash -x
O=OLD2
N=NEW2
diff -u {${O},${N}}/f1-[S1]*v1 | sed -e '/^ /d'
diff -u {${O},${N}}/f1-linux-[S1]*v1 | sed -e '/^ /d'
diff -u {${O},${N}}/f1-[Sl]*v2 | sed -e '/^ /d'
diff -u {${O},${N}}/f1-linux-[S1]*v2 | sed -e '/^ /d'
diff -u {${O},${N}}/ZZZ.* | sed -e '/^ /d'
diff -u {${O},${N}}/YYY.* | sed -e '/^ /d'
diff -u {${O},${N}}/XXX.* | sed -e '/^ /d'
