#!/bin/bash -ex
#-----------------------------------------------------------------------------
CDOT_NFS='172.22.15.121'
CDOT_1='RACK5CDOT_NFS_data/m4_cdot_nfs1'
CDOT_2='RACK5CDOT_NFS_data/m4_cdot_nfs2'
CDOT_3='RACK5CDOT_NFS_data/m4_cdot_nfs3'
CDOT_4='RACK5CDOT_NFS_data/m4_cdot_nfs4'
#-----------------------------------------------------------------------------
W=`pwd`                 # Where script is being run from (i.e. home directory?).
D=`dirname $0`          # Where this script is located and being run.
f=${D:0:1}
if [ "$f" = '/' ]; then
    W=''
    D=${D:1}
    D=`echo "${D}" | sed -e 's;/\.$;;'`
fi
M=`realpath -m ${W}/${D}/..`
R=`realpath -m --relative-to ${M} ${W}/${D}`
#-----------------------------------------------------------------------------
M4_PY="${M}/m4.py"
#-----------------------------------------------------------------------------
# Create Storage System
SSNFS=`${M4_PY} --brief storage systems create 'NFS storage system name' | awk '{print $1}'`

# Create Storage Protocol ID.
SPNFS=`${M4_PY} --brief storage protocols create ${SSNFS} NFS ${CDOT_NFS} 'SomethingNFS' | awk '{print $1}'`

# Create Project.
PNNFS="Scripted NFS project for 1g to 1g migration"
JNNFS1="job to copy NFS nfs1 1g to NFS nfs3 1g"
JNNFS2="job to copy NFS nfs2 1g to NFS nfs4 1g"
${M4_PY} p c "${PNNFS}"

# Create Job.
${M4_PY} j c "${PNNFS}" nfs://${CDOT_NFS}/${CDOT_1} nfs://${CDOT_NFS}/${CDOT_3} "${JNNFS1}"
${M4_PY} j c "${PNNFS}" nfs://${CDOT_NFS}/${CDOT_2} nfs://${CDOT_NFS}/${CDOT_4} "${JNNFS2}"

# Run the jobs.
${M4_PY} jobs run "${JNNFS1}" "${JNNFS2}"

exit 0
#-----------------------------------------------------------------------------
#-- # Add Storage Systems
#-- ${M4_PY} storage systems create SMB_stuff
#-- #      Storage System Created 50 - "SMB_stuff"
#-- ${M4_PY} storage protocols create 50 SMB 172.22.14.116 "AD/LoginName" "BlueSnake" "SomethingSMB"
#-- #      Storage Protocol Created 22 - "SomethingSMB"
#-- ${M4_PY} storage systems create NFS_stuff
#-- #      Storage System Created 51 - "NFS_stuff"
#-- ${M4_PY} storage protocols create 51 NFS 172.22.13.103 "SomethingNFS"
#-- #      Storage Protocol Created 23 - "SomethingNFS"
#-- # Create projects and jobs.
#-- PN="Scripted SMB project for na116 v1 to na116 v2"
#-- JN="job to copy na116 v1 to na116 v1"
#-- # Create the project - note SMB version 2.0 source and destination.
#-- ${M4_PY} p c "${PN}" 2.0 2.0
#-- #     Project Created 512
#-- # Create a job for doing the migration.
#-- ${M4_PY} jobs create "${PN}" cifs://172.22.14.116/v1 cifs://172.22.14.116/v2 "${JN}"
#-- #     Job ID: 596
#-- # Run the job for doing the migration.
#-- ${M4_PY} jobs run "${JN}"
#-- #-----------------------------------------------------------------------------
