#!/bin/bash -exup
#-----------------------------------------------------------------------------
CDOT_NFS='172.22.15.121'
CDOT_1='RACK5CDOT_NFS_data/m4_cdot_nfs1'
CDOT_2='RACK5CDOT_NFS_data/m4_cdot_nfs2'
CDOT_3='RACK5CDOT_NFS_data/m4_cdot_nfs3'
CDOT_4='RACK5CDOT_NFS_data/m4_cdot_nfs4'
#-----------------------------------------------------------------------------
# mkdir -p /mnt/nfs{1,2}
#-- # mount -t nfs ${CDOT_NFS}:/${CDOT_1} /mnt/nfs1
#-- # mount -t nfs ${CDOT_NFS}:/${CDOT_2} /mnt/nfs2
#-----------------------------------------------------------------------------
mkdir -p /mnt/nfs3
mount -t nfs ${CDOT_NFS}:/${CDOT_3} /mnt/nfs3
cd /mnt/nfs3
rm -rf * .[0-~]* || true
cd
umount /mnt/nfs3

#-----------------------------------------------------------------------------
mount -t nfs ${CDOT_NFS}:/${CDOT_4} /mnt/nfs4
mkdir -p /mnt/nfs4
cd /mnt/nfs4
rm -rf * .[0-~]* || true
cd
umount /mnt/nfs4
#-----------------------------------------------------------------------------
exit 0
#-----------------------------------------------------------------------------
