#!/bin/bash -ex

# mkdir -p /mnt/nfs{1,2}
# mount -t nfs 172.22.14.103:/vol/m4_1G_nfs_v1 /mnt/nfs1
# mount -t nfs 172.22.14.103:/vol/m4_1G_nfs_v2 /mnt/nfs2

mkdir -p /mnt/nfs{3,4}

mount -t nfs 172.22.14.103:/vol/m4_1G_nfs_v3 /mnt/nfs3
cd /mnt/nfs3
rm -rf * .[0-~]* || true
cd
umount /mnt/nfs3

mount -t nfs 172.22.14.103:/vol/m4_1G_nfs_v4 /mnt/nfs4
cd /mnt/nfs4
rm -rf * .[0-~]* || true
cd
umount /mnt/nfs4

exit 0
#-----------------------------------------------------------------------------
