#!/bin/bash -ex
#-----------------------------------------------------------------------------
W=`pwd`                 # Where script is being run from (i.e. home directory?).
D=`dirname $0`          # Where this script is located and being run.
f=${D:0:1}
if [ "$f" = '/' ]; then
    W=''
    D=${D:1}
    D=`echo "${D}" | sed -e 's;/\.$;;'`
fi
M=`realpath -m ${W}/${D}/..`
R=`realpath -m --relative-to ${M} ${W}/${D}`
#-----------------------------------------------------------------------------
M4_PY="${M}/m4.py"
#-----------------------------------------------------------------------------
# Create FC 14G migration from 25eb8ab90056482af6c9ce9009399e675 to 21ab345f355a8287b6c9ce9009399e675
# Create 10G migration from 2642126ca1625f8b16c9ce9009399e675 to 13g 3624a93708a2d08dc5cfe441e0001103b
#-----------------------------------------------------------------------------
FROM1=25eb8ab90056482af6c9ce9009399e675		# 14G Nimble
TO1=21ab345f355a8287b6c9ce9009399e675		# 14G Nimble

FROM2=2642126ca1625f8b16c9ce9009399e675		# 10G Nimble
TO2=3624a93708a2d08dc5cfe441e0001103b		# 13G Nimble
#-----------------------------------------------------------------------------
# Create Storage System
SSFC=`${M4_PY} --brief storage systems create 'FC storage system name' | awk '{print $1}'`
#-----------------------------------------------------------------------------
# Create Storage Protocol ID.  Choose WWN 0x56c9ce907fc86f03 -- strange, not used WWN.
SPFC=`${M4_PY} --brief storage protocols create ${SSFC} FC 'SomethingFC' | awk '{print $1}'`
#-----------------------------------------------------------------------------
# Create Project.
PNFC="Scripted FC project for two FC to two FC migrations"
${M4_PY} p c "${PNFC}"
#-----------------------------------------------------------------------------
# Create Job.
JNFC1="job to copy FC 14g to FC 14g"
${M4_PY} j c "${PNFC}" block://${FROM1} block://${TO1} "${JNFC1}"

JNFC2="job to copy FC 10g to FC 13g"
${M4_PY} j c "${PNFC}" block://${FROM2} block://${TO2} "${JNFC2}"
#-----------------------------------------------------------------------------
# Run the jobs.
${M4_PY} jobs run "${JNFC1}" "${JNFC2}"
#-----------------------------------------------------------------------------
exit 0
#-----------------------------------------------------------------------------
