#!/bin/bash -ex
#-----------------------------------------------------------------------------
W=`pwd`                 # Where script is being run from (i.e. home directory?).
D=`dirname $0`          # Where this script is located and being run.
f=${D:0:1}
if [ "$f" = '/' ]; then
    W=''
    D=${D:1}
    D=`echo "${D}" | sed -e 's;/\.$;;'`
fi
M=`realpath -m ${W}/${D}/..`
R=`realpath -m --relative-to ${M} ${W}/${D}`
#-----------------------------------------------------------------------------
M4_PY="${M}/m4.py"
#-----------------------------------------------------------------------------
# Get all jobs, stop them, then delete them.
J=`${M4_PY} --brief jobs list`
${M4_PY} jobs stop $J

set +x
# Poll for all jobs stopped, before deleting jobs.
while true; do
    R=`${M4_PY} -o jobs list $J | awk '{print $3}' | sed -e 's/STOPPED//' -e "s/[ ']//g"`
    if [ "$R" == '' ]; then
        break
    fi
    sleep 3
done
echo 'JOBs stopped!'
set -x

${M4_PY} jobs delete $J

# Get all projects, then delete them.
P=`${M4_PY} --brief projects list`
${M4_PY} proj delete ${P}

# Get all storage files, then delete them.
SF=`${M4_PY} --brief storage files | awk '{print $1}'`
${M4_PY} storage files delete ${SF}

# Get all storage protocols, then delete them.
SP=`${M4_PY} --brief storage protocols | awk '{print $1}'`
${M4_PY} storage protocols delete ${SP}

# Get all storage systems, then delete them.
SS=`${M4_PY} --brief storage systems | awk '{print $1}'`
${M4_PY} storage systems delete ${SS}

# Make sure nothing present -- other than automatic devices.
${M4_PY} jobs list
${M4_PY} projects list
#-- ${M4_PY} --brief storage devices list
${M4_PY} --brief storage files list
${M4_PY} --brief storage protocols list
${M4_PY} --brief storage systems list

exit 0
#-----------------------------------------------------------------------------
