#!/bin/bash -ex
#-----------------------------------------------------------------------------
W=`pwd`                 # Where script is being run from (i.e. home directory?).
D=`dirname $0`          # Where this script is located and being run.
f=${D:0:1}
if [ "$f" = '/' ]; then
    W=''
    D=${D:1}
    D=`echo "${D}" | sed -e 's;/\.$;;'`
fi
M=`realpath -m ${W}/${D}/..`
R=`realpath -m --relative-to ${M} ${W}/${D}`
#-----------------------------------------------------------------------------
M4_PY="${M}/m4.py"
#-----------------------------------------------------------------------------
#   iscsiadm -m discovery ; iscsiadm -m node ; iscsiadm -m session
# 192.168.14.103 & 172.22.14.103
#-----------------------------------------------------------------------------
IP1=192.168.14.180
IP2=192.168.14.186
#-----------------------------------------------------------------------------
FROM1=360a9800044307a63352b4d4878544e61		# 4.0g NETAPP
TO1=360a9800044307a63352b4d4878544e63		# 4.0g NETAPP

FROM2=360a9800044307a63352b4d4878544e5a		# 15g NETAPP
TO2=360a9800044307a63352b4d4878544e58		# 15g NETAPP
#-----------------------------------------------------------------------------
# Create Storage System.
SSiSCSI=`${M4_PY} --brief storage systems create 'iSCSI storage system name' | awk '{print $1}'`
#-----------------------------------------------------------------------------
# Create Storage Protocol IDs.
SPiSCSI1=`${M4_PY} --brief storage protocols create ${SSiSCSI} iSCSI ${IP1} "${IP1}-iSCSI" | awk '{print $1}'`
SPiSCSI2=`${M4_PY} --brief storage protocols create ${SSiSCSI} iSCSI ${IP1} "${IP2}-iSCSI" | awk '{print $1}'`
#-----------------------------------------------------------------------------
# Create Project.
PNiSCSI="Scripted iSCSI project for two migrations"
${M4_PY} p c "${PNiSCSI}"
#-----------------------------------------------------------------------------
# Create Jobs.
JNiSCSI1="job to copy iSCSI 4g ${FROM1} to iSCSI ${TO1}"
${M4_PY} j c "${PNiSCSI}" SCSI://${FROM1} SCSI://${TO1} "${JNiSCSI1}"

JNiSCSI2="job to copy iSCSI 15g ${FROM2} to iSCSI ${TO2}"
${M4_PY} j c "${PNiSCSI}" SCSI://${FROM2} SCSI://${TO2} "${JNiSCSI2}"
#-----------------------------------------------------------------------------
# Run the jobs.
${M4_PY} jobs run "${JNiSCSI1}" "${JNiSCSI2}"
#-----------------------------------------------------------------------------
exit 0
#-----------------------------------------------------------------------------
