#!/bin/bash -e
#-----------------------------------------------------------------------------
/bin/date '+%Y-%m-%d_%H-%M-%S'
#-----------------------------------------------------------------------------
W=`pwd`                 # Where script is being run from (i.e. home directory?).
D=`dirname $0`          # Where this script is located and being run.
f=${D:0:1}
if [ "$f" = '/' ]; then
    W=''
    D=${D:1}
    D=`echo "${D}" | sed -e 's;/\.$;;'`
fi
M=`realpath -m ${W}/${D}/..`
R=`realpath -m --relative-to ${M} ${W}/${D}`
#-----------------------------------------------------------------------------
cd "${M}"
#-----------------------------------------------------------------------------
#-- # Get username, password, parsec_IPADDRESS.
#-- source ENV
#-----------------------------------------------------------------------------
# Command that handles projects/jobs through the REST interface.
M4_PY="${M}/m4.py"
#-----------------------------------------------------------------------------
DELETEJOBS=yes
DELETEPROJ=yes
#=============================================================================
# Abbreviated name for each source storage.
#-- w2016
SOURCEABR=(w2019 \
	   w2012 \
	   w2008 \
	   cdot113 \
	   is100)
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Source IP addresses.
#--   172.22.12.144
SOURCEIPS=(172.22.12.112 \
	   172.22.12.143 \
	   172.22.12.140 \
	   172.22.15.113 \
	   172.22.13.100)
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Source share names.
#--	   m4-v1
SOURCESHR=(m4-v1 \
	   m4-v1 \
	   m4-v1 \
	   m4_cdot_01 \
	   m4_v1)
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Source SMB version.
#--	   default
SOURCEVER=(default \
	   default \
	   default \
	   default \
	   default)
#----------------------------------------------------------------------------
# Abbreviated name for each destination storage.
#--	   w2016
DESTINABR=(w2019 \
	   w2012 \
	   cdot113 \
	   is100 \
	   w2008)
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Destination IP addresses.
#--	   172.22.12.144
DESTINIPS=(172.22.12.112 \
	   172.22.12.143 \
	   172.22.15.113 \
	   172.22.13.100 \
	   172.22.12.140)
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Destination share names.
#--	   m4-v2
DESTINSHR=(m4-v2 \
	   m4-v2 \
	   m4_cdot_02 \
	   m4_v2 \
	   m4-v2)
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Destination SMB version.
#--	   default
DESTINVER=(default \
	   default \
	   default \
	   default \
	   default)
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#+ for i in {0..6}; do
#+     echo "${SOURCEABR[$i]} ${SOURCEIPS[$i]} ${SOURCESHR[$i]} ${SOURCEVER[$i]}  -> ${DESTINABR[$i]} ${DESTINIPS[$i]} ${DESTINSHR[$i]} ${DESTINVER[$i]}"
#+ done
let i=${#SOURCEABR[@]} || true
if [ "${#SOURCEIPS[@]}" != $i -o "${#SOURCESHR[@]}" != $i -o	\
     "${#SOURCEVER[@]}" != $i -o				\
     "${#DESTINABR[@]}" != $i -o "${#DESTINIPS[@]}" != $i -o	\
     "${#DESTINSHR[@]}" != $i -o "${#DESTINVER[@]}" != $i ]; then
    echo "ERROR - arrays are not of the same length, please fix."
    echo SOURCEABR="${#SOURCEABR[@]}" SOURCEIPS="${#SOURCEIPS[@]}" SOURCESHR="${#SOURCESHR[@]}" SOURCEVER="${#SOURCEVER[@]}"
    echo DESTINABR="${#DESTINABR[@]}" DESTINIPS="${#DESTINIPS[@]}" DESTINSHR="${#DESTINSHR[@]}" DESTINVER="${#DESTINVER[@]}"
    exit 1
fi

#=============================================================================
# 1 
echo 'Delete any existing jobs'
# Get the job id's.
J=`${M4_PY} --brief job list`
if [ "$J" != '' ]; then
    # Make sure they are stopped.
    STOP=`${M4_PY} job stop ${J}`
    echo "${STOP}"
    # Disable the jobs.
    DISABLE=`${M4_PY} job disable ${J}`
    echo "${DISABLE}"
    # Delete the jobs.
    DELE=`${M4_PY} job dele ${J}`
    echo "${DELE}"
fi
#-----------------------------------------------------------------------------
# 2
echo 'Delete any existing projects'
# Get the project id's.
P=`${M4_PY} --brief proj list`
if [ "$P" != '' ]; then
    echo "P='${P}'"
    P_DELE=`${M4_PY} proj delete ${P}`
    echo ${P_DELE}
fi
#-----------------------------------------------------------------------------
# 3
echo 'Remove / empty source and destination shares.'
for ((i=0; i < ${#SOURCEABR[*]}; i++)); do
    make rm_files_${SOURCEABR[$i]}_${SOURCESHR[$i]} rm_files_${DESTINABR[$i]}_${DESTINSHR[$i]}
done
#-----------------------------------------------------------------------------
# 4
echo 'Setup all sources.'
for ((i=0; i < ${#SOURCEABR[*]}; i++)); do
    make setup_${SOURCEABR[$i]} 2>&1 | tee AAA.${SOURCEABR[$i]}
done
#-----------------------------------------------------------------------------
# 5
echo 'Get lots of information for each source.'
for ((i=0; i < ${#SOURCEABR[*]}; i++)); do
    make info_${SOURCEABR[$i]}_${SOURCESHR[$i]} 2>&1 | tee AAA.info_${SOURCEABR[$i]}_${SOURCESHR[$i]}
done
#-----------------------------------------------------------------------------
# 6
echo 'Create projects and jobs.'
for ((i=0; i < ${#SOURCEABR[*]}; i++)); do
    PN="Scripted SMB project&job for ${SOURCEABR[$i]} ${SOURCESHR[$i]} to ${DESTINABR[$i]} ${DESTINSHR[$i]}"
    JN="${SOURCEABR[$i]} ${SOURCESHR[$i]} to ${DESTINABR[$i]} ${DESTINSHR[$i]}"
    #-------------------------------------------------------------------------
    # Create the project via REST interface.
    echo 'Create the project.'
    PC=`${M4_PY} p c "${PN}" "${SOURCEVER[$i]}" "${DESTINVER[$i]}"`
    echo "${PN}"
    #-------------------------------------------------------------------------
    # Create the job connected to above project, via REST interface.
    echo 'Create the new job for migration'
    JC1=`${M4_PY} j c "${PN}" cifs://${SOURCEIPS[$i]}/${SOURCESHR[$i]} cifs://${DESTINIPS[$i]}/${DESTINSHR[$i]} "${JN}"`
    echo "${JC1}"
done
#-----------------------------------------------------------------------------
# 7
echo "Sleep five seconds to let scheduler do its business."
sleep 5
date
echo 'Run the jobs'
# Get the new job id's.
J=`${M4_PY} --brief job list`
if [ "$J" != '' ]; then
    echo "J=${J}"
    #-- # Enable the job.
    #-- ENABLE=`${M4_PY} job enable ${J}`
    #-- echo "ENABLE=${ENABLE}"
    # Run the jobs.
    START=`${M4_PY} job run ${J}`
    echo "START=${START}"
fi
echo 'Started all jobs.'
#-----------------------------------------------------------------------------
# 8
echo "Sleep five seconds to let scheduler do its business."
sleep 5
date
echo 'Wait til all jobs finished.'
set +e					# No longer have exit status exit script.
c=0
while [ "$c" != '' ]; do
    sleep 0.25
    c=`ps -C pxlhr -o pid=`
done
echo 'pxlhr appears to be done.'
#-----------------------------------------------------------------------------
# 9
echo "Sleep five seconds to let things settle down."
sleep 5
date
echo 'Get lots of information for each destination.'
for ((i=0; i < ${#SOURCEABR[*]}; i++)); do
    make info_${DESTINABR[$i]}_${DESTINSHR[$i]} 2>&1 | tee AAA.info_${DESTINABR[$i]}_${DESTINSHR[$i]} 
done
#-----------------------------------------------------------------------------
echo "Done with $0"
/bin/date '+%Y-%m-%d_%H-%M-%S'
#-----------------------------------------------------------------------------
exit 0
#-----------------------------------------------------------------------------
