#!/bin/bash -e
#-----------------------------------------------------------------------------
W=`pwd`                 # Where script is being run from (i.e. home directory?).
D=`dirname $0`          # Where this script is located and being run.
f=${D:0:1}
if [ "$f" = '/' ]; then
    W=''
    D=${D:1}
    D=`echo "${D}" | sed -e 's;/\.$;;'`
fi
M=`realpath -m ${W}/${D}/..`
R=`realpath -m --relative-to ${M} ${W}/${D}`
#-----------------------------------------------------------------------------
cd "${M}"
#-----------------------------------------------------------------------------
# Print out every command executed.
set -x
#-----------------------------------------------------------------------------
make setup_w2008
make setup_w2012
#-- make setup_w2016
make setup_w2019
#-- make setup_na116
make setup_is100
make setup_cdot113
#-----------------------------------------------------------------------------
exit 0
