#!/bin/bash -e
#-----------------------------------------------------------------------------
/bin/date '+%Y-%m-%d_%H-%M-%S'
#-----------------------------------------------------------------------------
# Get username, password, parsec_IPADDRESS.
source ENV
#-----------------------------------------------------------------------------
# Command that handles projects/jobs through the REST interface.
M4_PY="../m4.py"
#=============================================================================
# Abbreviated name for each source storage.
#--	   w2016
SOURCEABR=(w2019 \
	   w2012 \
	   w2008 \
	   na116 \
	   cdot113 \
	   is100)
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Source IP addresses.
#--	   172.22.12.144
SOURCEIPS=(172.22.12.112 \
	   172.22.12.143 \
	   172.22.12.140 \
	   172.22.14.116 \
	   172.22.15.113 \
	   172.22.13.100)
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Source share names.
#--	   m4-v1
SOURCESHR=(m4-v1 \
	   m4-v1 \
	   m4-v1 \
	   cifs_v1 \
	   m4_cdot_01 \
	   m4_v1)
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Source SMB version.
#--	   default
SOURCEVER=(default \
	   default \
	   default \
	   2.0 \
	   default \
	   default)
#----------------------------------------------------------------------------
# Abbreviated name for each destination storage.
#--	   w2016
DESTINABR=(na116 \
	   w2019 \
	   w2012 \
	   cdot113 \
	   is100 \
	   w2008)
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Destination IP addresses.
#--	   172.22.12.144
DESTINIPS=(172.22.14.116 \
	   172.22.12.112 \
	   172.22.12.143 \
	   172.22.15.113 \
	   172.22.13.100 \
	   172.22.12.140)
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Destination share names.
#--	   m4-v2
DESTINSHR=(cifs_v2 \
	   m4-v2 \
	   m4-v2 \
	   m4_cdot_02 \
	   m4_v2 \
	   m4-v2)
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Destination SMB version.
#--	   default
DESTINVER=(2.0 \
	   default \
	   default \
	   default \
	   default \
	   default)
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#+ for i in {0..6}; do
#+     echo "${SOURCEABR[$i]} ${SOURCEIPS[$i]} ${SOURCESHR[$i]} ${SOURCEVER[$i]}  -> ${DESTINABR[$i]} ${DESTINIPS[$i]} ${DESTINSHR[$i]} ${DESTINVER[$i]}"
#+ done
let i=${#SOURCEABR[@]} || true
if [ "${#SOURCEIPS[@]}" != $i -o "${#SOURCESHR[@]}" != $i -o	\
     "${#SOURCEVER[@]}" != $i -o				\
     "${#DESTINABR[@]}" != $i -o "${#DESTINIPS[@]}" != $i -o	\
     "${#DESTINSHR[@]}" != $i -o "${#DESTINVER[@]}" != $i ]; then
    echo "ERROR - arrays are not of the same length, please fix."
    echo SOURCEABR="${#SOURCEABR[@]}" SOURCEIPS="${#SOURCEIPS[@]}" SOURCESHR="${#SOURCESHR[@]}" SOURCEVER="${#SOURCEVER[@]}"
    echo DESTINABR="${#DESTINABR[@]}" DESTINIPS="${#DESTINIPS[@]}" DESTINSHR="${#DESTINSHR[@]}" DESTINVER="${#DESTINVER[@]}"
    exit 1
fi

#=============================================================================
echo 'Start Verify for the jobs.'
# Get the job id's.
J=`${M4_PY} --brief job list`
if [ "$J" != '' ]; then
    echo "J=${J}"
    # Start the verify for the jobs.
    VERIFY=`${M4_PY} job verify ${J}`
    echo "VERIFY=${VERIFY}"
fi
echo 'Started verify for the jobs.'
#-----------------------------------------------------------------------------
# 8
echo "Sleep five seconds to let scheduler do its business."
sleep 5
date
echo 'Wait til all jobs finished.'
set +e					# No longer have exit status exit script.
c=0
while [ "$c" != '' ]; do
    sleep 0.25
    c=`ps -C pxlhr -o pid=`
done
echo 'pxlhr appears to be done.'
#-----------------------------------------------------------------------------
# 9
echo "Sleep five seconds to let things settle down."
sleep 5
#-----------------------------------------------------------------------------
echo "Done with $0"
/bin/date '+%Y-%m-%d_%H-%M-%S'
#-----------------------------------------------------------------------------
exit 0
#-----------------------------------------------------------------------------
