#!/bin/bash -e
#-----------------------------------------------------------------------------
DISK=/dev/`multipath -ll | awk '/Nimble  ,Server/ {print $2}' | head -1`
#-----------------------------------------------------------------------------
# 2694 - bottom port (cabled)
LOCAL_WWPN=21:00:00:24:ff:83:04:cf
#-----------------------------------------------------------------------------
# 2562 - top port cabled (left-most)
# REMOTE_WWPN=21:00:00:1b:32:86:c9:8b
REMOTE_WWPN=21:00:00:24:ff:0f:b0:47
#-----------------------------------------------------------------------------
FILE_NAME=export_to_125
LUN=5
#-----------------------------------------------------------------------------
logger 'before creating target'
sleep 1
#-----------------------------------------------------------------------------
targetcli <<EOF_TARGETCLI
set global auto_cd_after_create=false
/backstores/fileio create ${FILE_NAME} ${DISK}
/qla2xxx create ${LOCAL_WWPN}
/qla2xxx/${LOCAL_WWPN}/luns create /backstores/fileio/${FILE_NAME} ${LUN}
/qla2xxx/${LOCAL_WWPN}/acls create ${REMOTE_WWPN}
cd /
# ls
EOF_TARGETCLI
#-----------------------------------------------------------------------------
logger 'after creating target'
sleep 1
/px/bin/targetcli_probe
exit 0
#=============================================================================
