#!/usr/bin/perl -w
# Arguments are two numbers in hex to be added.
# If there is a third argument, round up to the mask length.
$one = hex($ARGV[0]);
$two = hex($ARGV[1]);
$output = $one + $two;
if ($#ARGV == 2) {
  $three = hex($ARGV[2]) - 1;
  $output = ($output + $three) & ~$three;
}
printf STDOUT "0x%x\n",$output;
# print STDERR "one=($one),two=($two),output=($output)\n";
exit(0)
