#!/bin/bash -ex
echo "In $0 $* <------------------------------------------------------------"
declare -a A=(first second third fourth)
#-----------------------------------------------------------------------------
echo "A=${A}"
echo "{A[2]}=${A[2]}"
echo "{A}[2]=${A}[2]"
echo "A[2]=$A[2]"
echo "{A[*]}=${A[*]}"
echo "{A[@]}=${A[@]}"
# Note: @ puts ' after first entry, * after last.
echo "elements in #A[@]=${#A[@]}"
echo "elements in #A[1]=${#A[1]}"	# number of chars in A[1]
echo "elements in #A[2]=${#A[2]}"	# number of chars in A[2]
echo "Middle two entries in A[@]:1:2=${A[@]:1:2}"
echo "Middle two entries in A[*]:1:2=${A[*]:1:2}"
echo "Replace entry ${A[@]/fourth/Last One/}"
# NOTE: search is a pattern, *=wildcard.  If replacement is missing, then delete.
A=("${A[@]}" "Fifth ONE")
echo "Add element A[@]=${A[@]}"
unset A[2]
echo "Remove third A[@]=${A[@]}"

# Go through array:
for f in "${A[@]}" ; do
    echo "  Entry='$f'"
done

echo "Array indexes !A[@]=${!A[@]}"
echo "Array indexes !A[*]=${!A[*]}"

A+="NEWEND"
echo "[@]=${A[@]}     -- Array indexes !A[@]=${!A[@]}"
A+=("NEWEND")
echo "[@]=${A[@]}     -- Array indexes !A[@]=${!A[@]}"

echo "{A[-1]}=${A[-1]}"
#-----------------------------------------------------------------------------
echo "Done with $0"
exit 0
#-----------------------------------------------------------------------------
# End of arrays
