#!/bin/bash -e
# NOTE: list in 'for' verses array.  I hate bash. Well ... this part anyway.
echo "In $0 $* <------------------------------------------------------------"
declare -a A=(`echo {A..J}`)
echo "A=${A}"
echo "{A[*]}=${A[*]}"
for a in $A; do
  echo "a=$a"
done
echo '-----------------------------------------------------------------------------'
unset A
A=(`echo {A..J}`)
echo "A=${A}"
echo "{A[*]}=${A[*]}"
for a in $A; do
  echo "a=$a"
done
echo '-----------------------------------------------------------------------------'
unset A
A=`echo {A..J}`
echo "A=${A}"
echo "{A[*]}=${A[*]}"
for a in $A; do
  echo "a=$a"
done
echo '-----------------------------------------------------------------------------'
unset A
A=`echo a*`
echo "A=${A}"
echo "{A[*]}=${A[*]}"
for a in $A; do
  echo "a=$a"
done
echo '-----------------------------------------------------------------------------'
echo "Done with $0"
exit 0
#-----------------------------------------------------------------------------
# End of arrays1
