#!/bin/bash -ex
echo "In $0 $* <------------------------------------------------------------"
echo 'To get current directory executing script it (W),'
echo 'where the script directory is located ($W/$D),'
echo 'the name of the script being run ($B),'
echo 'and the first character in the directory name (check for /) ($f).'
echo
#-----------------------------------------------------------------------------
W=`pwd`
D=`dirname $0`
B=`basename $0`
f=${D:0:1}
if [ "$f" = '/' ]; then
    W=''
    D=${D:1}
    D=`echo "${D}" | sed -e 's;/\.$;;'`
fi
#-----------------------------------------------------------------------------
echo "W=${W}"
echo "D=${D}"
echo "B=${B}"
echo "f=${f}"
echo "W/D/nameinsamedirectoryas-${B} ${W}/${D}/nameinsamedirectoryas-${B}"
#-----------------------------------------------------------------------------
echo "Done with $0"
exit 0
#-----------------------------------------------------------------------------
# End of programname
