#!/bin/bash -x
trap "echo trap" {1..64}

#-- (echo 'before sleep 30'; sleep 30; echo 'after sleep 30')&
(echo 'before sleep 10'; sleep 10; echo 'after sleep 10')&
J=$!
(echo 'before sleep 15'; sleep 15; echo 'after sleep 15'; kill -1 ${J}; echo "after kill -1 ${J}"; sleep 5;echo "sleep 15 timed out" )&
X=$!

echo "before wait ${J}"
wait ${J}
echo "after wait ${J}"

kill -1 ${X}
echo "after kill -1 ${X}, before wait ${X}"
wait ${X}
echo "after wait ${X}"
echo "$0 - Done"
exit 0
