#!/bin/bash -ex
cd /mnt/md4/home/m4

mkdir -p rsync-from-mac-2 rsync-from-mac-3 rsync-from-mac-4 rsync-from-mac-5
mkdir -p rsync-from-mac-6 rsync-from-mac-7 rsync-from-mac-8 rsync-from-mac-9 rsync-from-mac-10

tar cf - -C rsync-from-mac . | tar xf - -C rsync-from-mac-2
tar cf - -C rsync-from-mac . | tar xf - -C rsync-from-mac-3
tar cf - -C rsync-from-mac . | tar xf - -C rsync-from-mac-4
tar cf - -C rsync-from-mac . | tar xf - -C rsync-from-mac-5
tar cf - -C rsync-from-mac . | tar xf - -C rsync-from-mac-6
tar cf - -C rsync-from-mac . | tar xf - -C rsync-from-mac-7
tar cf - -C rsync-from-mac . | tar xf - -C rsync-from-mac-8
tar cf - -C rsync-from-mac . | tar xf - -C rsync-from-mac-9
tar cf - -C rsync-from-mac . | tar xf - -C rsync-from-mac-10

exit 0
