#!/bin/bash -ex
# -r	recurse into subdirectories
# -l	copy symlinks as symlinks
# -p	preserve permissions
# -A	preserve ACLs (implies --perms)
# -t	preserve modification times
# -g	preserve group
# -o	preserve owner (super-user only)
# -D	same as --devices - preserve device files (super-user only) and --specials preserve special files

# -E	preserve executability
# --sparse, -S	turn sequences of nulls into sparse blocks
# --one-file-system, -x    don't cross filesystem boundaries
# --rsh=COMMAND, -e ssh    specify the remote shell to use
# --prune-empty-dirs, -m   prune empty directory chains from file-list
# --compress, -z           compress file data during the transfer

# -X	preserve extended attributes
# -i	output a change-summary for all updates.
# -v	verbose

# --quiet, -q              suppress non-error messages
# --hard-links, -H         preserve hard links

# Only run one at a time - try for 2 seconds.
(
    # Wait for lock on /var/lock/.myscript.exclusivelock (fd 200) for 2 seconds
    /opt/homebrew/bin/flock -x -w 2 200 || exit 1
    /opt/homebrew/bin/rsync -rlpAtgoD -E --fake-super --progress --delete-after -S --one-file-system \
    	-e ssh --delete --prune-empty-dirs --compress \
    	/Users/m4/    root@172.22.14.10:/mnt/md4/home/m4/rsync-from-mac-6/
) 200>/Users/m4/CRONTAB/crontab-lock

