#!/bin/sh

if [ $# -ne 2 ]; then
  echo "usage ctojgr.sh file fontsize " >&2
  exit 1
fi

if [ ! -f $1 ]; then
  echo "$1 does not exist" >&2
  exit 1
fi


maxwid=`maxwid < $1 | awk '{ print $1+3}'`
wid=`echo "$maxwid $2" | awk '{ print .583/70*$1*$2 }'`
lines=`wc $1 | awk '{ print $1 }'`
maxhei=`wc $1 | awk '{ print $1+2+$1+1 }'`
hei=`echo "$maxhei $2" | awk '{ print .16/19.0*$1*$2 }'`
 
echo newgraph
echo xaxis min 0 max $maxwid size $wid nodraw

nawk 'BEGIN	{ fs = '$2'; bl = 0; isline = 0; nlines = 0; s ="" } 
     /^[ 	]*$/	{ bl++; next }
        { if (isline) { s = s"\\\n"; nlines ++ }
          for (i = 0; i < bl; i++) { s = s"\\\n"; nlines++ } 
          bl = 0
          s = s""$0
          isline = 1 }
      END { nlines++
            maxhei = nlines*2+3
            hei = .16/19.0*maxhei*fs
            print "yaxis min 0 max 2 size", hei, "nodraw"
            print "border"
            print "newstring font Courier fontsize", fs, "x 1 y 1 hjl vjc :"
            printf "%s\n", s }' < $1
