#!/bin/bash
#
# gzshm - Compress shared memory files
#
# Mark D. Rustad, 2009/06/30
#
# Copyright 2009 Xiotech Corporation. All rights reserved.

apps_dir=/opt/xiotech/apps
core_dir=/var/log/dump

# Process all huge files

for h in /huge/*; do
	(${apps_dir}/shmdump ${h} | gzip -9c > ${core_dir}/${h##*/}.shm.gz) &
done

wait

# vi:sw=8 ts=8 noexpandtab
