#!/usr/bin/perl -w
#
# $Header$
##############################################################################
# Xiotech
# Copyright (c) 2006  Xiotech
# ======================================================================
# $RCSfile$
# Author: Bryan Holty
#
# Purpose:
#   Remotely reset a machine, while maintaining control of the console
##############################################################################
$SIG{CHLD} = "IGNORE";

close STDOUT;
close STDIN;
close STDERR;

if ( fork() == 0 )
{
    sleep(5);
    system ("/sbin/reboot -n");
}
exit 0;
