#!/bin/bash -e
# $Id: patch 11794 2006-07-17 20:39:06Z RustadM $
# Script to patch the Linux kernel
#
# This script is invoked by the Makefile in the containing directory
# and is invoked in this directory.
#
# The first argument to the script is the revision of the kernel being
# patched for convenience.
#
# The second argument to the script is the model the patch applies to.

KERNVER="$1"
KERNSRC=/usr/src/linux-${KERNVER}
MODSRC=$PWD
shift
KMODEL="$1"
shift

PATCHES=$@

source ../patch_funcs.sh	# Get patch assist functions

mkdir -p obj-${KMODEL}/drivers/char
ln -sf ../../../../xio3d.{c,h} obj-${KMODEL}/drivers/char

objpatch ${PATCHES}

echo Patching complete.
