#!/bin/bash -e
# $Id: prepatch 11794 2006-07-17 20:39:06Z RustadM $
# Script to prepatch Linux kernel
#
# This script is invoked by the Makefile in the containing directory
# and is invoked from this directory.
#
# The first argument to the script is the revision of the kernel being
# patched for convenience.
#
# The second argument to the script is the path to the kernel tarball.
#
# All remaining arguments are the prepatches to apply.

KERNVER="$1"
shift
KERNSRC=${KERNPATH:=/usr/src}/linux-${KERNVER}
TARDIR="$1"
shift
TARFILE=${TARDIR}/linux-${KERNVER}.tar.bz2

test -d ${TARDIR} || { echo ${TARDIR} not found!; exit 1; }

root rm -rf ${KERNSRC}
root tar -xjf ${TARFILE} -C ${KERNPATH}
root rm -f ${KERNPATH}/pax_global_header
root chmod -R o-w ${KERNSRC}

root rm -f ${KERNSRC}/rpm-release

for p in "$@"; do
	echo Applying prepatch "$p"
	root patch -d ${KERNSRC} -p1 <"$p"
	echo Applied prepatch "$p"
done

echo Prepatching complete.
