#!/bin/bash -x
# --fs
# --platochars
# --lines
#
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
#
CPP='gcc -E -x c -nostdinc -C -CC -Wno-error -Wno-extra -traditional-cpp -Wno-invalid-pp-token'
IMS='../../imscomp --fs --platochars --lines'
#
unalias doit 2>>/dev/null >>/dev/null
doit()
{
    FILE="$1"
    BASE="`basename ${FILE} .gcs`"
    CPPE="${BASE}.E"
    FS="${BASE}.fs"
    ${CPP} "${FILE}" -o "${CPPE}"
    ${IMS} "${CPPE}" "${FS}" 2>&1
}
#-----------------------------------------------------------------------------
doit G21clar.gcs                            > AAA.00 2>&1
doit G21flugel.gcs                          > AAA.01 2>&1
doit G22bassn.gcs                           > AAA.02 2>&1
doit G22clar.gcs                            > AAA.03 2>&1
doit G22flugel.gcs                          > AAA.04 2>&1
doit G22flute.gcs                           > AAA.05 2>&1
doit G22horn.gcs                            > AAA.06 2>&1
doit G22oboe.gcs                            > AAA.07 2>&1
doit G22perc.gcs                            > AAA.08 2>&1
doit G22strng.gcs                           > AAA.09 2>&1
doit Gershwin_Concerto_move_2.1.gcs         > AAA.10 2>&1
doit Gershwin_Concerto_move_2.1_.gcs        > AAA.11 2>&1
doit Gershwin_Concerto_move_2.2.gcs         > AAA.12 2>&1
doit Gershwin_Concerto_move_2.2_.gcs        > AAA.13 2>&1
doit Gershwin_Concerto_move_3.gcs           > AAA.14 2>&1
#-----------------------------------------------------------------------------
