#!/bin/bash -epux
# File m2
#-- export MC_ARGS='--voices=Piccolo,Flute,Oboe12,EnglishHorn,ClarinetinB12,BassClarinet,Bassoon12'
export MC_ARGS='--voices=HorninF12,HorninF34,TrumpetinB12,TrumpetinB3,Trombone12,BassTrombone,Tuba,Timpani'
# export MC_ARGS='--voices=Snaredrum,Suspendedcymbal,Bassdrum,Xylophone,Woodblocks,Crashcymbal,Triangle,Glockenspiel'
# export MC_ARGS='--voices=Violin1,Violin2,Viola,Cello,Contrabass'
# export MC_ARGS='--voices=Piano_upper,Piano_lower'

make clean ; make new-g3.pdf ; open gershwin-pdfs/*mvt* new-g3.pdf
