#!/bin/bash -epux
# File m3
export MC_ARGS='--platochars --voices=Snaredrum,Suspendedcymbal,Bassdrum,Xylophone,Woodblocks,Crashcymbal,Triangle,Glockenspiel'

make clean ; make new-g3.pdf ; open gershwin-pdfs/*mvt* new-g3.pdf
