#!/bin/bash -e
. 0.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Create directory new_root.
install -dv ${CLFS_NEW_ROOT}/

echo "Make directory usr on ${CLFS_NEW_ROOT} -- where new image will be built."
mkdir -pv ${CLFS_NEW_ROOT}/usr

# The following makes a symbolic link so that --sysroot and --prefix work for stand-alone and current running of tools.
AAA=`dirname "${CLFS_NEW_ROOT}/${CLFS_NEW_ROOT}"`
mkdir -p ${AAA}
rm -f ${CLFS_NEW_ROOT}/${CLFS_NEW_ROOT}

howdeep=`echo ${CLFS_NEW_ROOT} | sed -r -e 's;/new_root/*;/;' -e 's;[^/]+;..;g' -e 's;^/;;'`
#-- echo howdeep=${howdeep}

ln -sf ${howdeep} ${CLFS_NEW_ROOT}/${CLFS_NEW_ROOT}
#=============================================================================
exit 0
#=============================================================================
