#!/bin/bash -e
. 0.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Create clf-cross-tools directory.
install -dv ${CLFSCROSSTOOLS}
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
