#!/bin/bash -e
. 0.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
export NOMAKEDISTCLEAN=nope
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.kernel.org/pub/linux/kernel/v4.x/linux-4.9.1.tar.xz' \
    'linux-4.9.1' \
    '' \
    '' \
    '' \
    "make mrproper 1>&2" \
    "make ARCH=${MACHINE} headers_check 1>&2" \
    "make ARCH=${MACHINE} INSTALL_HDR_PATH=${CLFS_NEW_ROOT}/usr headers_install 1>&2"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
ls -l ${CLFS_NEW_ROOT}/usr/include/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
	usr/include -- for the linux kernel header files.
