#!/bin/bash -e
. 0.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/m4/m4-1.4.17.tar.xz' \
    'm4-1.4.17' \
    '' \
    '' \
    '' \
    "./configure --prefix=${CLFSCROSSTOOLS} 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for m4-1.4.17 any longer."
    rm -rf m4-1.4.17
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (clfs-cross-tools):
    lib/charset.alias
    bin/m4
    share/info/m4.info
    share/man/man1/m4.1
