#!/bin/bash -e
. 0.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cp ${WHERE_I_AM}/diff.M4.ncurses.patch ${CLFSTARS}/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/ncurses/ncurses-6.0.tar.gz' \
    'ncurses-6.0' \
    'wget -N http://patches.clfs.org/sysvinit/ncurses-6.0-bash_fix-1.patch' \
    'patch -Np1 -i ${TARSAT}/${PATCHNAME} 1>&2 && patch -Np1 -i ${TARSAT}/diff.M4.ncurses.patch 1>&2' \
    '' \
    "AWK=gawk ./configure \
	  --datadir=${CLFSCROSSTOOLS}/usr/share --exec-prefix=${CLFSCROSSTOOLS}/usr \
	  --prefix=${CLFSCROSSTOOLS} --bindir=${CLFSCROSSTOOLS}/bin \
	  --sbindir=${CLFSCROSSTOOLS}/sbin --libexecdir=${CLFSCROSSTOOLS}/libexec \
	  --sysconfdir=${CLFSCROSSTOOLS}/etc --localstatedir=${CLFSCROSSTOOLS}/var \
	  --libdir=${CLFSCROSSTOOLS}/lib --includedir=${CLFSCROSSTOOLS}/usr/include \
	  --infodir=${CLFSCROSSTOOLS}/usr/share/info --mandir=${CLFSCROSSTOOLS}/usr/share/man \
	  --without-debug \
	  --without-shared 1>&2" \
    'make -C include 1>&2 && make -C progs tic 1>&2' \
    "install -v -m755 progs/tic ${CLFSCROSSTOOLS}/bin 1>&2"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (clfs-cross-tools):
    bin/tic
