#!/bin/bash -e
. 0.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#    'make -j 20 1>&2' \
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://sourceforge.net/projects/pkgconfiglite/files/0.28-1/pkg-config-lite-0.28-1.tar.gz' \
    'pkg-config-lite-0.28-1' \
    '' \
    '' \
    '' \
    "./configure \
	  --prefix=${CLFSCROSSTOOLS} --host=${CLFS_TARGET} \
	    --with-pc-path=${CLFS_NEW_ROOT}/lib/pkgconfig:${CLFS_NEW_ROOT}/usr/share/pkgconfig:${CLFS_NEW_ROOT}/usr/lib/pkgconfig:${CLFS_NEW_ROOT}/usr/share/pkgconfig 1>&2" \
    'make -j 1 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for pkg-config-lite-0.28-1 any longer."
    rm -rf pkg-config-lite-0.28-1
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (clfs-cross-tools):
    bin/pkg-config
    bin/x86_64-ise4z-linux-gnu-pkg-config
    share/doc/pkg-config/pkg-config-guide.html
    share/aclocal/pkg.m4
    share/man/man1/pkg-config.1
