#!/bin/bash -e
. 0.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/gmp/gmp-6.0.0a.tar.xz' \
    'gmp-6.0.0' \
    '' \
    '' \
    '' \
    "./configure \
	  --prefix=${CLFSCROSSTOOLS} \
	  --enable-cxx \
	  --disable-static 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (clfs-cross-tools):
    share/info/gmp.info
    share/info/gmp.info-1
    share/info/gmp.info-2
    lib/libgmp.la
    lib/libgmpxx.la
    lib/libgmp.so.10.2.0
    lib/libgmp.so.10
    lib/libgmp.so
    lib/libgmp.la
    lib/libgmpxx.so.4.4.0
    lib/libgmpxx.so.4
    lib/libgmpxx.so
    lib/libgmpxx.la
    include/gmp.h
    include/gmpxx.h
