#!/bin/bash -e
. 0.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.mpfr.org/mpfr-3.1.3/mpfr-3.1.3.tar.xz' \
    'mpfr-3.1.3' \
    'wget -N http://patches.clfs.org/sysvinit/mpfr-3.1.3-fixes-1.patch' \
    'patch -Np1 -i ${TARSAT}/${PATCHNAME} 1>&2' \
    '' \
    "LDFLAGS='-Wl,-rpath,${CLFSCROSSTOOLS}/lib' \
	  ./configure \
	  --prefix=${CLFSCROSSTOOLS} \
	  --disable-static \
	  --with-gmp=${CLFSCROSSTOOLS} 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (clfs-cross-tools):
    share/doc/mpfr/FAQ.html
    share/info/mpfr.info
    lib/libmpfr.la
    lib/libmpfr.so.4.1.2
    lib/libmpfr.so.4
    lib/libmpfr.so
    lib/libmpfr.la
    include/mpfr.h
    include/mpf2mpfr.h
    share/doc/mpfr/*
