#!/bin/bash -e
. 0.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.multiprecision.org/mpc/download/mpc-1.0.3.tar.gz' \
    'mpc-1.0.3' \
    '' \
    '' \
    '' \
    "LDFLAGS='-Wl,-rpath,${CLFSCROSSTOOLS}/lib' \
	  ./configure \
	  --prefix=${CLFSCROSSTOOLS} \
	  --disable-static \
	  --with-gmp=${CLFSCROSSTOOLS} \
	  --with-mpfr=${CLFSCROSSTOOLS} 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (clfs-cross-tools):
    lib/libmpc.so.3.0.0
    lib/libmpc.so.3
    lib/libmpc.so
    lib/libmpc.la
    share/info/mpc.info
    include/mpc.h
