#!/bin/bash -e
. 0.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://isl.gforge.inria.fr/isl-0.15.tar.xz' \
    'isl-0.15' \
    '' \
    '' \
    '' \
    "LDFLAGS='-Wl,-rpath,${CLFSCROSSTOOLS}/lib' \
	  ./configure \
	  --prefix=${CLFSCROSSTOOLS} \
	  --disable-static \
	  --with-gmp=${CLFSCROSSTOOLS} \
	  --with-mpfr=${CLFSCROSSTOOLS} 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (clfs-cross-tools):
    lib/libisl.so.13.1.1
    lib/libisl.so.13
    lib/libisl.so
    lib/libisl.la
    lib/libisl.so.13.1.1-gdb.py
    include/isl/*
    lib/pkgconfig/isl.pc
