#!/bin/bash -e
. 0.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#? cp ${WHERE_I_AM}/binutils-2.25-2014-04-20.patch ${CLFSTARS}/
#?    'patch -Np1 -i ${TARSAT}/binutils-2.25-2014-04-20.patch 1>&2' \
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/binutils/binutils-2.25.1.tar.bz2' \
    'binutils-2.25.1' \
    '' \
    '' \
    'binutils-build' \
    "AR=ar AS=as \
	  ../binutils-2.25.1/configure \
	  --prefix=${CLFSCROSSTOOLS} --host=${CLFS_HOST} --target=${CLFS_TARGET} \
	  --with-sysroot=${CLFS_NEW_ROOT} \
	  --with-lib-path='${CLFS_NEW_ROOT}/lib:${CLFS_NEW_ROOT}/usr/lib' \
	  --disable-nls \
	  --disable-static \
	  --enable-64-bit-bfd \
	  --disable-multilib \
	  --disable-werror 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need build directory for binutils-2.25 any longer."
    rm -rf binutils-build
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (clfs-cross-tools):
    share/info/bfd.info
    share/info/binutils.info
    share/man/man1/x86_64-ise4z-linux-gnu-addr2line.1
    share/man/man1/x86_64-ise4z-linux-gnu-ar.1
    share/man/man1/x86_64-ise4z-linux-gnu-dlltool.1
    share/man/man1/x86_64-ise4z-linux-gnu-nlmconv.1
    share/man/man1/x86_64-ise4z-linux-gnu-nm.1
    share/man/man1/x86_64-ise4z-linux-gnu-objcopy.1
    share/man/man1/x86_64-ise4z-linux-gnu-ranlib.1
    share/man/man1/x86_64-ise4z-linux-gnu-readelf.1
    share/man/man1/x86_64-ise4z-linux-gnu-size.1
    share/man/man1/x86_64-ise4z-linux-gnu-strings.1
    share/man/man1/x86_64-ise4z-linux-gnu-strip.1
    share/man/man1/x86_64-ise4z-linux-gnu-elfedit.1
    share/man/man1/x86_64-ise4z-linux-gnu-windres.1
    share/man/man1/x86_64-ise4z-linux-gnu-windmc.1
    share/man/man1/x86_64-ise4z-linux-gnu-c++filt.1
    bin/x86_64-ise4z-linux-gnu-size
    bin/x86_64-ise4z-linux-gnu-objdump
    bin/x86_64-ise4z-linux-gnu-ar
    bin/x86_64-ise4z-linux-gnu-strings
    bin/x86_64-ise4z-linux-gnu-ranlib
    bin/x86_64-ise4z-linux-gnu-objcopy
    bin/x86_64-ise4z-linux-gnu-addr2line
    bin/x86_64-ise4z-linux-gnu-readelf
    bin/x86_64-ise4z-linux-gnu-elfedit
    bin/x86_64-ise4z-linux-gnu-strip
    bin/x86_64-ise4z-linux-gnu-c++filt
    x86_64-ise4z-linux-gnu/bin/nm
    x86_64-ise4z-linux-gnu/bin/strip
    x86_64-ise4z-linux-gnu/bin/ar
    x86_64-ise4z-linux-gnu/bin/ranlib
    x86_64-ise4z-linux-gnu/bin/dlltool
    x86_64-ise4z-linux-gnu/bin/objdump
    x86_64-ise4z-linux-gnu/bin/objcopy
    share/info/as.info
    share/man/man1/x86_64-ise4z-linux-gnu-as.1
    bin/x86_64-ise4z-linux-gnu-as
    x86_64-ise4z-linux-gnu/bin/as
    bin/x86_64-ise4z-linux-gnu-gprof
    share/info/gprof.info
    share/man/man1/x86_64-ise4z-linux-gnu-gprof.1
    bin/x86_64-ise4z-linux-gnu-ld.bfd
    x86_64-ise4z-linux-gnu/bin/ld.bfd
    bin/x86_64-ise4z-linux-gnu-ld
    x86_64-ise4z-linux-gnu/bin/ld
    x86_64-ise4z-linux-gnu/lib/ldscripts/*
    share/info/ld.info
    share/man/man1/x86_64-ise4z-linux-gnu-ld.1
    dozens of files related to libiberty
