#!/bin/bash -e
. 0.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cp ${WHERE_I_AM}/patches/gcc-5.3.0-pure64_specs-1.patch ${CLFSTARS}/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N ftp://gcc.gnu.org/pub/gcc/releases/gcc-5.3.0/gcc-5.3.0.tar.bz2' \
    'gcc-5.3.0' \
    '' \
    'cd ../gcc-5.3.0 && patch -Np1 -i ${TARSAT}/gcc-5.3.0-pure64_specs-1.patch 1>&2' \
    'gcc-build-static' \
    'true' \
    'true' \
    'true'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
(cd gcc-5.3.0 && echo -en "\n#undef STANDARD_STARTFILE_PREFIX_1\n#define STANDARD_STARTFILE_PREFIX_1 \"${CLFS_NEW_ROOT}/lib/\"\n" >> gcc/config/linux.h)
(cd gcc-5.3.0 && echo -en "\n#undef STANDARD_STARTFILE_PREFIX_2\n#define STANDARD_STARTFILE_PREFIX_2 \"${CLFS_NEW_ROOT}/usr/lib/\"\n" >> gcc/config/linux.h)

touch ${CLFS_NEW_ROOT}/usr/include/limits.h
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N ftp://gcc.gnu.org/pub/gcc/releases/gcc-5.3.0/gcc-5.3.0.tar.bz2' \
    'gcc-5.3.0' \
    '' \
    'cd ../gcc-5.3.0 && patch -Np1 -i ${TARSAT}/gcc-5.3.0-pure64_specs-1.patch 1>&2' \
    'gcc-build-static' \
    "AR=ar LDFLAGS='-Wl,-rpath,${CLFSCROSSTOOLS}/lib' \
	  ../gcc-5.3.0/configure \
	  --prefix=${CLFSCROSSTOOLS} --build=${CLFS_HOST} --host=${CLFS_HOST} \
	  --target=${CLFS_TARGET} \
	  --with-sysroot=${CLFS_NEW_ROOT} \
	  --with-local-prefix=${CLFS_NEW_ROOT} \
	  --with-native-system-header-dir=${CLFS_NEW_ROOT}/usr/include \
	  --disable-nls \
	  --disable-shared \
	  --with-mpfr=${CLFSCROSSTOOLS} \
	  --with-gmp=${CLFSCROSSTOOLS} \
	  --with-isl=${CLFSCROSSTOOLS} \
	  --with-cloog=${CLFSCROSSTOOLS} \
	  --with-mpc=${CLFSCROSSTOOLS} \
	  --without-headers \
	  --with-newlib \
	  --disable-decimal-float \
	  --disable-libgomp \
	  --disable-libmudflap \
	  --disable-libssp \
	  --disable-libatomic \
	  --disable-libitm \
	  --disable-libsanitizer \
	  --disable-libquadmath \
	  --disable-libvtv \
	  --disable-libcilkrts \
	  --disable-libstdc++-v3 \
	  --disable-threads \
	  --disable-multilib \
	  --with-system-zlib \
	  --enable-languages=c \
	  --with-glibc-version=2.22 1>&2" \
    'make all-gcc all-target-libgcc -j 20 1>&2' \
    'make install-gcc install-target-libgcc 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need the build directory for static gcc any longer."
    rm -rf gcc-build-static
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs:
    gcc compiler, libgcc, libgcov, crtbegin.o, crtend.o, etc.
    header files for gcc -- clfs-cross-tools/lib/gcc/x86_64-ise4z-linux-gnu/5.1.0/plugin/include/*
    header files for gcc -- clfs-cross-tools/lib/gcc/x86_64-ise4z-linux-gnu/5.1.0/include/*
