#!/bin/bash -e
. 0.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/glibc/glibc-2.22.tar.xz' \
    'glibc-2.22' \
    '' \
    "cp -v timezone/Makefile timezone/Makefile.orig 1>&2 && sed -e 's:...pwd.:${CLFSSOURCES}/glibc-2.22/timezone:' timezone/Makefile.orig > timezone/Makefile" \
    'glibc-build' \
    "echo libc_cv_ssp=no > config.cache && \
	  BUILD_CC=gcc CC='${CLFS_TARGET}-gcc ${BUILD64}' \
	  AR=${CLFS_TARGET}-ar RANLIB=${CLFS_TARGET}-ranlib \
	  ../glibc-2.22/configure --prefix=${CLFS_NEW_ROOT} --bindir=${CLFS_NEW_ROOT}/bin \
	  --datarootdir=${CLFS_NEW_ROOT}/usr/share --includedir=${CLFS_NEW_ROOT}/usr/include \
	  --libdir=${CLFS_NEW_ROOT}/lib --libexecdir=${CLFS_NEW_ROOT}/usr/libexec \
	  --sbindir=${CLFS_NEW_ROOT}/usr/sbin --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var \
	  --host=${CLFS_TARGET} --build=${CLFS_HOST} \
	  --disable-profile \
	  --enable-kernel=4.1 \
	  --with-binutils=${CLFSCROSSTOOLS}/bin \
	  --with-headers=${CLFS_NEW_ROOT}/usr/include \
	  --enable-obsolete-rpc \
	  --enable-shared \
	  --cache-file=config.cache 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Need following for dynamic loader (ld.so era) to work.
ln -sfv ld-2.22.so ${CLFS_NEW_ROOT}/lib/ld-linux.so.2
root mkdir -p ${CLFS_NEW_ROOT}/tools
root ln -sf ../sbin ${CLFS_NEW_ROOT}/tools/bin
root ln -sf ../etc ${CLFS_NEW_ROOT}/tools/etc
root ln -sf ../lib ${CLFS_NEW_ROOT}/tools/lib
root ln -sf ../lib ${CLFS_NEW_ROOT}/tools/libexec
root ln -sf ../sbin ${CLFS_NEW_ROOT}/tools/sbin
root ln -sf ../sbin ${CLFS_NEW_ROOT}/tools/tmp
root ln -sf ../sbin ${CLFS_NEW_ROOT}/tools/usr
root ln -sf ../sbin ${CLFS_NEW_ROOT}/tools/var
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for glibc-2.22 any longer."
    rm -rf glibc-2.22
    echo "Do not need compile directory for glibc-2.22 any longer."
    rm -rf glibc-build
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    lib/ld-2.21.so
    lib/ld-linux-x86-64.so.2
    usr/include/*
    lib/crt1.o
    lib/gcrt1.o
    lib/Mcrt1.o
    lib/Scrt1.o
    lib/crti.o
    lib/crtn.o
    sbin/iconvconfig.new
    bin/iconv
    bin/localedef
    usr/share/i18n/*
    lib/gconv/*
    bin/gencat
    lib/libieee.a
    bin/tzselect
    sbin/zic
    sbin/zdump
    bin/getconf
    usr/libexec/getconf/*
    lib/libSegFault.so
    lib/libpcprofile.so
    bin/pcprofiledump
    bin/xtrace
    bin/catchsegv
    bin/getent
    bin/makedb
    bin/rpcgen
    sbin/nscd
    lib/audit/*
    bin/sprof
    bin/pldd
    bin/ldd
    bin/sotruss
    sbin/sln
    sbin/ldconfig
------------------------------------------------------------------------------
Libraries (new_root):
    libBrokenLocale, libm, libdl, libg, libc, libcrypt, libpthread, librt,
    libcidn, libthread_db, libresolv, libnss_dns, libanl, libnss_files,
    libnss_db, libnss_hesiod, librpcsvc, libnsl, libnss_nis, libnss_nisplus, 
    libnss_compat, libnsl, libutil
