#!/bin/bash -e
. 0.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cp ${WHERE_I_AM}/patches/gcc-5.3.0-pure64_specs-1.patch ${CLFSTARS}/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N ftp://gcc.gnu.org/pub/gcc/releases/gcc-5.3.0/gcc-5.3.0.tar.bz2' \
    'gcc-5.3.0' \
    '' \
    'cd ../gcc-5.3.0 && patch -Np1 -i ${TARSAT}/gcc-5.3.0-pure64_specs-1.patch 1>&2' \
    'gcc-build-final' \
    'true' \
    'true' \
    'true'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
(cd gcc-5.3.0 && echo -en "\n#undef STANDARD_STARTFILE_PREFIX_1\n#define STANDARD_STARTFILE_PREFIX_1 \"${CLFS_NEW_ROOT}/lib/\"\n" >> gcc/config/linux.h)
(cd gcc-5.3.0 && echo -en "\n#undef STANDARD_STARTFILE_PREFIX_2\n#define STANDARD_STARTFILE_PREFIX_2 \"${CLFS_NEW_ROOT}/usr/lib/\"\n" >> gcc/config/linux.h)

touch ${CLFS_NEW_ROOT}/usr/include/limits.h
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N ftp://gcc.gnu.org/pub/gcc/releases/gcc-5.3.0/gcc-5.3.0.tar.bz2' \
    'gcc-5.3.0' \
    '' \
    'cd ../gcc-5.3.0 && patch -Np1 -i ${TARSAT}/gcc-5.3.0-pure64_specs-1.patch 1>&2' \
    'gcc-build-final' \
    "AR=ar LDFLAGS='-Wl,-rpath,${CLFSCROSSTOOLS}/lib' \
	  ../gcc-5.3.0/configure --prefix=${CLFSCROSSTOOLS} --build=${CLFS_HOST} \
	  --target=${CLFS_TARGET} --host=${CLFS_HOST} --with-sysroot=${CLFS_NEW_ROOT} \
	  --with-local-prefix=${CLFS_NEW_ROOT} \
	  --with-native-system-header-dir=${CLFS_NEW_ROOT}/usr/include \
	  --disable-nls --disable-static --disable-libmudflap --disable-libssp \
	  --disable-multilib --enable-languages=c,c++ \
	  --enable-__cxa_atexit --enable-threads=posix \
	  --with-mpc=${CLFSCROSSTOOLS} --with-mpfr=${CLFSCROSSTOOLS} \
	  --with-gmp=${CLFSCROSSTOOLS} --with-cloog=${CLFSCROSSTOOLS} \
	  --with-isl=${CLFSCROSSTOOLS} \
	  --with-system-zlib --enable-checking=release --enable-libstdcxx-time 1>&2" \
	"make AS_FOR_TARGET=${CLFS_TARGET}-as LD_FOR_TARGET=${CLFS_TARGET}-ld -j 20 1>&2" \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need build directory for final cross-gcc any longer."
    rm -rf gcc-build-final
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (clfs-cross-tools):
    relocatable gcc compiler using new libraries just previously created.
    libgcc, libgcov, crtbegin.o, crtend.o, etc.
    header files for gcc -- clfs-cross-tools/lib/gcc/x86_64-ise4z-linux-gnu/5.3.0/plugin/include/*
    header files for gcc -- clfs-cross-tools/lib/gcc/x86_64-ise4z-linux-gnu/5.3.0/include/*
    gcc, g++
