#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/gmp/gmp-6.0.0a.tar.xz' \
    'gmp-6.0.0' \
    '' \
    '' \
    '' \
    "CC_FOR_BUILD=gcc \
	  ./configure \
	  --prefix=${CLFS_NEW_ROOT} --exec-prefix=${CLFS_NEW_ROOT}/usr \
	  --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --enable-cxx 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for gmp-6.0.0 any longer."
    rm -rf gmp-6.0.0
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/info/gmp.info
    usr/share/info/gmp.info-1
    usr/share/info/gmp.info-2
    lib/libgmp.la
    lib/libgmpxx.la
    lib/libgmp.so.10.2.0
    lib/libgmp.so.10
    lib/libgmp.so
    lib/libgmp.la
    lib/libgmpxx.so.4.4.0
    lib/libgmpxx.so.4
    lib/libgmpxx.so
    lib/libgmpxx.la
    usr/include/gmp.h
    usr/include/gmpxx.h
