#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.mpfr.org/mpfr-3.1.3/mpfr-3.1.3.tar.xz' \
    'mpfr-3.1.3' \
    'wget -N http://patches.clfs.org/sysvinit/mpfr-3.1.3-fixes-1.patch' \
    'patch -Np1 -i ${TARSAT}/${PATCHNAME} 1>&2' \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT} \
	  --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for mpfr-3.1.3 any longer."
    rm -rf mpfr-3.1.3
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/doc/mpfr/FAQ.html
    usr/share/info/mpfr.info
    lib/libmpfr.la
    lib/libmpfr.so.4.1.2
    lib/libmpfr.so.4
    lib/libmpfr.so
    lib/libmpfr.la
    usr/include/mpfr.h
    usr/include/mpf2mpfr.h
    usr/share/doc/mpfr/*
