#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.multiprecision.org/mpc/download/mpc-1.0.3.tar.gz' \
    'mpc-1.0.3' \
    '' \
    '' \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for mpc-1.0.3 any longer."
    rm -rf mpc-1.0.3
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    lib/libmpc.so.3.0.0
    lib/libmpc.so.3
    lib/libmpc.so
    lib/libmpc.la
    usr/share/info/mpc.info
    usr/include/mpc.h
