#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Need /usr/lib.
mkdir -p ${CLFS_NEW_ROOT}/usr/lib
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# http://zlib.net/zlib-1.2.10.tar.gz
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://zlib.net/zlib-1.2.10.tar.gz' \
    'zlib-1.2.10' \
    '' \
    '' \
    '' \
    "mandir=${CLFS_NEW_ROOT}/usr/share \
	  ./configure \
	  --eprefix=${CLFS_NEW_ROOT}/usr --prefix=${CLFS_NEW_ROOT} \
	  --libdir=${CLFS_NEW_ROOT}/lib --sharedlibdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
ln -sfv ../../lib/$(readlink ${CLFS_NEW_ROOT}/lib/libz.so) ${CLFS_NEW_ROOT}/usr/lib/libz.so
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for zlib-1.2.10 any longer."
    rm -rf zlib-1.2.10
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    lib/libz.a
    lib/libz.so.1.2.8
    lib/libz.so
    usr/share/man3/libz.3
    lib/pkgconfig/lib.pc
    zlib.h, zconf.h -- /usr/include/
