#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#? cp ${WHERE_I_AM}/binutils-2.25-2014-04-20.patch ${CLFSTARS}/
#?    'patch -Np1 -i ${TARSAT}/binutils-2.25-2014-04-20.patch 1>&2' \
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/binutils/binutils-2.25.1.tar.bz2' \
    'binutils-2.25.1' \
    '' \
    '' \
    'binutils-build' \
    "../binutils-2.25.1/configure \
	  --exec-prefix=${CLFS_NEW_ROOT}/usr --prefix=${CLFS_NEW_ROOT} \
	  --build=${CLFS_HOST} --host=${CLFS_TARGET} --target=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --localedir=${CLFS_NEW_ROOT}/usr/share/locale \
	  --with-lib-path='${CLFS_NEW_ROOT}/lib:${CLFS_NEW_ROOT}/usr/lib' \
	  --enable-nls \
	  --enable-shared \
	  --enable-64-bit-bfd \
	  --disable-multilib 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
mkdir -pv ${CLFS_NEW_ROOT}/usr/share/gdb/auto-load/usr/lib/
mv -v ${CLFS_NEW_ROOT}/lib/libstdc++.so.*-gdb.py ${CLFS_NEW_ROOT}/usr/share/gdb/auto-load/usr/lib/ || true
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source nor patch for binutils-2.25.1 any longer."
    rm -rf binutils-2.25.1
#?    rm -f ${CLFSTARS}/binutils-2.25-2014-04-20.patch
    echo "Do not need build directory for binutils-2.25.1 any longer."
    rm -rf binutils-build
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/info/bfd.info
    usr/share/locale/*
    usr/share/gettext/po/*
    usr/include/*
    lib/libbfd-2.25.so
    lib/libbfd.so
    lib/libbfd.la
    lib/libbfd.a
    lib/libopcodes-2.25.so
    lib/libopcodes.so
    lib/libopcodes.la
    lib/libopcodes.a
    usr/share/info/binutils.info
    usr/share/man/man1/addr2line.1
    usr/share/man/man1/ar.1
    usr/share/man/man1/dlltool.1
    usr/share/man/man1/nlmconv.1
    usr/share/man/man1/nm.1
    usr/share/man/man1/objcopy.1
    usr/share/man/man1/ranlib.1
    usr/share/man/man1/readelf.1
    usr/share/man/man1/size.1
    usr/share/man/man1/strings.1
    usr/share/man/man1/strip.1
    usr/share/man/man1/elfedit.1
    usr/share/man/man1/windres.1
    usr/share/man/man1/windmc.1
    usr/share/man/man1/c++filt.1
    bin/size
    bin/objdump
    bin/ar
    bin/strings
    bin/ranlib
    bin/objcopy
    bin/addr2line
    bin/readelf
    bin/elfedit
    bin/nm
    bin/strip
    bin/c++filt
    usr/x86_64-ise4z-linux-gnu/bin/ar
    usr/x86_64-ise4z-linux-gnu/bin/as
    usr/x86_64-ise4z-linux-gnu/bin/ld
    usr/x86_64-ise4z-linux-gnu/bin/ld.bfd
    usr/x86_64-ise4z-linux-gnu/bin/nm
    usr/x86_64-ise4z-linux-gnu/bin/objcopy
    usr/x86_64-ise4z-linux-gnu/bin/objdump
    usr/x86_64-ise4z-linux-gnu/bin/ranlib
    usr/x86_64-ise4z-linux-gnu/bin/strip
    usr/share/info/as.info
    bin/as
    usr/share/man/man1/as.1
    usr/x86_64-ise4z-linux-gnu/bin/as
    bin/gprof
    usr/share/info/gprof.info
    usr/share/man/man1/gprof.1
    bin/ld.bfd
    usr/x86_64-ise4z-linux-gnu/bin/ld.bfd
    bin/ld
    usr/x86_64-ise4z-linux-gnu/bin/ld
    usr/x86_64-ise4z-linux-gnu/lib/ldscripts/*
    usr/share/info/ld.info
    usr/share/man/man1/ld.1
    dozens of files related to libiberty
