#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cp ${WHERE_I_AM}/patches/gcc-5.3.0-pure64-1.patch ${CLFSTARS}/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N ftp://gcc.gnu.org/pub/gcc/releases/gcc-5.3.0/gcc-5.3.0.tar.bz2' \
    'gcc-5.3.0' \
    '' \
    'cd ../gcc-5.3.0 && patch -Np1 -i ${TARSAT}/gcc-5.3.0-pure64-1.patch 1>&2' \
    'gcc-build-055' \
    'true' \
    'true' \
    'true'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# This configures the location(s) of the shared libary files.
(cd gcc-5.3.0 && echo -en "\n#undef STANDARD_STARTFILE_PREFIX_1\n#define STANDARD_STARTFILE_PREFIX_1 \"${CLFS_NEW_ROOT}/lib/\"\n" >> gcc/config/linux.h)
(cd gcc-5.3.0 && echo -en "\n#undef STANDARD_STARTFILE_PREFIX_2\n#define STANDARD_STARTFILE_PREFIX_2 \"${CLFS_NEW_ROOT}/usr/lib/\"\n" >> gcc/config/linux.h)

# This makes sure that it's date is newer than things in the configuration directory -- else the auto programs are executed.
touch ${CLFS_NEW_ROOT}/usr/include/limits.h
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N ftp://gcc.gnu.org/pub/gcc/releases/gcc-5.3.0/gcc-5.3.0.tar.bz2' \
    'gcc-5.3.0' \
    '' \
    'cd ../gcc-5.3.0 && patch -Np1 -i ${TARSAT}/gcc-5.3.0-pure64-1.patch 1>&2' \
    'gcc-build-055' \
    "../gcc-5.3.0/configure \
	  --enable-threads \
	  --exec-prefix=${CLFS_NEW_ROOT}/usr --with-local-prefix=${CLFS_NEW_ROOT}/usr/local \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --target=${CLFS_TARGET} --with-local-prefix=${CLFS_NEW_ROOT} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --disable-multilib \
	  --disable-nls \
	  --enable-languages=c,c++ \
	  --disable-libstdcxx-pch \
	  --with-system-zlib \
	  --with-native-system-header-dir=${CLFS_NEW_ROOT}/usr/include \
	  --enable-checking=release \
	  --enable-libstdcxx-time 1>&2 && \
	  cp -v Makefile Makefile.orig 1>&2 && \
	  sed '/^HOST_\(GMP\|ISL\|CLOOG\)\(LIBS\|INC\)/s:${CLFS_NEW_ROOT}:/${CROSSTOOLS}:g' Makefile.orig > Makefile" \
    'make AS_FOR_TARGET="'"${AS}"'" LD_FOR_TARGET="'"${LD}"'" -j 20 1>&2' \
    "make install 1>&2 && cp -v ../gcc-5.3.0/include/libiberty.h ${CLFS_NEW_ROOT}/usr/include 1>&2"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Need "cc" for make to work right.
ln -sf gcc ${CLFS_NEW_ROOT}/bin/cc
ln -sf ../bin/cpp ${CLFS_NEW_ROOT}/lib/cpp
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source nor patch for gcc-5.3.0 any longer."
    rm -rf gcc-5.3.0
    rm -f ${CLFSTARS}/gcc-5.3.0-pure64-1.patch
    echo "Do not need build directory for package's gcc-5.3.0 any longer."
    rm -rf gcc-build-055
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    lib/gcc/x86_64-ise4z-linux-gnu/5.1.0/*
    libexec/gcc/x86_64-ise4z-linux-gnu/5.1.0/*
    bin/g++
    bin/c++
    bin/gcov
    bin/gcov-tool
    bin/cpp
    usr/share/man/man1/g++.1
    usr/share/man/man1/gcc.1
    usr/share/man/man1/cpp.1
    usr/share/man/man1/gcov.1
    usr/share/man/man7/fsf-funding.7
    usr/share/man/man7/gfdl.7
    usr/share/man/man7/gpl.7
    usr/share/info/cpp.info*
    usr/share/info/gcc.info*
    usr/share/info/cppinternals.info*
    usr/share/info/gccinstall.info*
    usr/share/info/gccint.info*
    bin/gcc
    bin/x86_64-ise4z-linux-gnu-gcc
    bin/x86_64-ise4z-linux-gnu-gcc-5.1.0
    bin/x86_64-ise4z-linux-gnu-gcc-ar
    bin/x86_64-ise4z-linux-gnu-gcc-nm
    bin/x86_64-ise4z-linux-gnu-gcc-ranlib
    usr/include/*
    lib/libgcc_s.so.1
    lib/libgcc_s.so
    usr/include/c++/*
    lib/libsupc++.la
    lib/libsupc++.a
    lib/libstdc++.la
    lib/libstdc++.a
    lib/libstdc++.so.6.0.21
    lib/libstdc++.so.6
    lib/libstdc++.so
    lib/libstdc++.so.6.0.21-gdb.py
    usr/share/gcc-5.1.0/*
    lib/liblsan.so.0.0.0
    lib/liblsan.so.0
    lib/liblsan.so
    lib/liblsan.la
    lib/liblsan.a
    lib/libasan.a
    lib/libasan.la
    lib/libasan.so
    lib/libasan.so.2
    lib/libasan.so.2.0.0
    lib/libasan_preinit.o
    lib/libubsan.a
    lib/libubsan.la
    lib/libubsan.so
    lib/libubsan.so.0
    lib/libubsan.so.0.0.0
    lib/libtsan.a
    lib/libtsan.la
    lib/libtsan.so
    lib/libtsan.so.0
    lib/libtsan.so.0.0.0
    lib/libsanitizer.spec
    lib/libvtv.a
    lib/libvtv.la
    lib/libvtv.so
    lib/libvtv.so.0
    lib/libvtv.so.0.0.0
    lib/libcilkrts.spec
    lib/libcilkrts.a
    lib/libcilkrts.la
    lib/libcilkrts.so
    lib/libcilkrts.so.5
    lib/libcilkrts.so.5.0.0
    lib/libssp.a
    lib/libssp.la
    lib/libssp.so
    lib/libssp.so.0
    lib/libssp.so.0.0.0
    lib/libssp_nonshared.a
    lib/libssp_nonshared.la
    lib/libquadmath.a
    lib/libquadmath.la
    lib/libquadmath.so
    lib/libquadmath.so.0
    lib/libquadmath.so.0.0.0
    usr/share/info/libquadmath.info
    lib/libgomp.a
    lib/libgomp.la
    lib/libgomp.so
    lib/libgomp.so.1
    lib/libgomp.so.1.0.0
    lib/libgomp.spec
    usr/share/info/libgomp.info
    lib/libitm.a
    lib/libitm.la
    lib/libitm.so
    lib/libitm.so.1
    lib/libitm.so.1.0.0
    lib/libitm.spec
    usr/share/info/libitm.info
    lib/libatomic.a
    lib/libatomic.la
    lib/libatomic.so
    lib/libatomic.so.1
    lib/libatomic.so.1.1.0
    usr/include/libiberty.h
    crtbegin.o crtbeginS.o crtbeginT.o crtend.o crtendS.o crtprec32.o crtprec64.o crtprec80.o crtfastmath.o
    unwind.h
