#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cp ${WHERE_I_AM}/diff.M4.ncurses.patch ${CLFSTARS}/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/ncurses/ncurses-6.0.tar.gz' \
    'ncurses-6.0' \
    'wget -N http://patches.clfs.org/sysvinit/ncurses-6.0-bash_fix-1.patch' \
    'patch -Np1 -i ${TARSAT}/${PATCHNAME} 1>&2 && patch -Np1 -i ${TARSAT}/diff.M4.ncurses.patch 1>&2' \
    '' \
    "./configure \
	  --datadir=${CLFS_NEW_ROOT}/usr/share --exec-prefix=${CLFS_NEW_ROOT}/usr \
	  --prefix=${CLFS_NEW_ROOT} \
	  --with-shared \
	  --build=${CLFS_HOST} --host=${CLFS_TARGET} --bindir=${CLFS_NEW_ROOT}/bin \
	  --sbindir=${CLFS_NEW_ROOT}/sbin --libexecdir=${CLFS_NEW_ROOT}/libexec \
	  --sysconfdir=${CLFS_NEW_ROOT}/etc --localstatedir=${CLFS_NEW_ROOT}/var \
	  --libdir=${CLFS_NEW_ROOT}/lib --includedir=${CLFS_NEW_ROOT}/usr/include \
	  --infodir=${CLFS_NEW_ROOT}/usr/share/info --mandir=${CLFS_NEW_ROOT}/usr/share/man \
	  --without-debug \
	  --enable-widec \
	  --enable-pc-files \
	  --without-ada \
	  --enable-overwrite \
	  --with-build-cc=gcc 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Create non-wide curses.
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/ncurses/ncurses-6.0.tar.gz' \
    'ncurses-6.0' \
    'wget -N http://patches.clfs.org/sysvinit/ncurses-6.0-bash_fix-1.patch' \
    'patch -Np1 -i ${TARSAT}/${PATCHNAME} 1>&2' \
    '' \
    "./configure --datadir=${CLFS_NEW_ROOT}/usr/share --exec-prefix=${CLFS_NEW_ROOT}/usr --prefix=${CLFS_NEW_ROOT} --with-shared --build=${CLFS_HOST} --host=${CLFS_TARGET} --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib --includedir=${CLFS_NEW_ROOT}/usr/include --infodir=${CLFS_NEW_ROOT}/usr/share/info --mandir=${CLFS_NEW_ROOT}/usr/share/man --without-debug --enable-pc-files --without-ada --enable-overwrite --with-build-cc=gcc 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for ncurses-6.0 any longer."
    rm -rf ncurses-6.0
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/man/*
    lib/libncurses++.a
    lib/libncurses++w.a
    lib/libncurses.a
    lib/libncurses.so
    lib/libncurses.so.5
    lib/libncurses.so.5.9
    lib/libncursesw.a
    lib/libncursesw.so
    lib/libncursesw.so.5
    lib/libncursesw.so.5.9
    bin/tic
    bin/toe
    bin/infotocap
    bin/captoinfo
    bin/infocmp
    bin/clear
    bin/tabs
    bin/tput
    bin/tset
    bin/reset
    lib/libpanel.a
    lib/libpanel.so
    lib/libpanel.so.5
    lib/libpanel.so.5.9
    lib/libpanelw.a
    lib/libpanelw.so
    lib/libpanelw.so.5
    lib/libpanelw.so.5.9
    lib/libmenu.a
    lib/libmenu.so
    lib/libmenu.so.5
    lib/libmenu.so.5.9
    lib/libmenuw.a
    lib/libmenuw.so
    lib/libmenuw.so.5
    lib/libmenuw.so.5.9
    lib/libform.a
    lib/libform.so
    lib/libform.so.5
    lib/libform.so.5.9
    lib/libformw.a
    lib/libformw.so
    lib/libformw.so.5
    lib/libformw.so.5.9
    bin/ncursesw5-config
    lib/pkgconfig/*	-- Bunch of gen-pkgconfig for above (*.pc).
    usr/include/curs*.h
    usr/include/etip.h
    lib/libcurses.a
    lib/libcurses.so
