#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cp ${WHERE_I_AM}/diff.M4.bzip2.patch ${CLFSTARS}/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz' \
    'bzip2-1.0.6' \
    '' \
    'patch -Np1 -i ${TARSAT}/diff.M4.bzip2.patch 1>&2' \
    '' \
    "true" \
    'make CC="'"${CC}"'" AR="'"${AR}"'" RANLIB="'"${RANLIB}"'" -j 20 1>&2' \
    "make DATADIR=${CLFS_NEW_ROOT}/usr PREFIX=${CLFS_NEW_ROOT} install 1>&2"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# FIX bin/{bzegrep,bzfgrep,bzcmp,bzless} that gets full CLFS_NEW_ROOT tacked in from of symbolic links.
ln -sf bzgrep ${CLFS_NEW_ROOT}/bin/bzegrep
ln -sf bzgrep ${CLFS_NEW_ROOT}/bin/bzfgrep
ln -sf bzdiff ${CLFS_NEW_ROOT}/bin/bzcmp
ln -sf bzmore ${CLFS_NEW_ROOT}/bin/bzless
# Do libbz2_so from 139-bzip2
cd bzip2-1.0.6
  make CC="${CC}" AR="${AR}" RANLIB="${RANLIB}" clean
  make CC="${CC} -fPIC" AR="${AR}" RANLIB="${RANLIB}" -f Makefile-libbz2_so
  make CC="${CC}" AR="${AR}" RANLIB="${RANLIB}" clean
  make CC="${CC}" AR="${AR}" RANLIB="${RANLIB}"
  make DATADIR=${CLFS_NEW_ROOT}/usr PREFIX=${CLFS_NEW_ROOT} install

  cp -v bzip2-shared ${CLFS_NEW_ROOT}/bin/bzip2
  cp -av libbz2.so* ${CLFS_NEW_ROOT}/lib
  ln -sfv ../../lib/libbz2.so.1.0 ${CLFS_NEW_ROOT}/usr/lib/libbz2.so
  ln -sfv libbz2.so.1.0.6 ${CLFS_NEW_ROOT}/lib/libbz2.so
  rm -fv ${CLFS_NEW_ROOT}/usr/bin/{bunzip2,bzcat,bzip2}
  ln -sfv bzip2 ${CLFS_NEW_ROOT}/bin/bunzip2
  ln -sfv bzip2 ${CLFS_NEW_ROOT}/bin/bzcat
cd ..
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source nor patch for bzip2-1.0.6 any longer."
    rm -rf bzip2-1.0.6
    rm -f ${CLFSTARS}/diff.M4.bzip2.patch
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    bin/bzip2
    bin/bunzip2
    bin/bzcat
    bin/bzip2recover
    usr/share/man/man1/bzip2.1
    usr/include/bzlib.h
    lib/libbz2.a
    lib/libbz2.so.1.0
    lib/libbz2.so.1.0.6
    usr/lib/libbz2.so
    bin/bzgrep
    bin/bzegrep
    bin/bzfgrep
    bin/bzmore
    bin/bzless
    bin/bzdiff
    bin/bzcmp
    usr/share/man/man1/bzgrep.1
    usr/share/man/man1/bzmore.1
    usr/share/man/man1/bzdiff.1
    usr/share/man/man1/bzegrep.1
    usr/share/man/man1/bzfgrep.1
    usr/share/man/man1/bzless.1
    usr/share/man/man1/bzcmp.1
    bin/bzegrep
    bin/bzfgrep
    bin/bzcmp
    bin/bzless
