#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N ftp://ftp.astron.com/pub/file/file-5.25.tar.gz' \
    'file-5.25' \
    '' \
    '' \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for file-5.25 any longer."
    rm -rf file-5.25
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    lib/libmagic.la
    lib/libmagic.so
    lib/libmagic.so.1
    lib/libmagic.so.1.0.0
    bin/file
    usr/include/magic.h
    usr/share/misc/magic.mgc
    usr/share/man/man1/file.1
    usr/share/man/man3/libmagic.3
    usr/share/man/man4/magic.4
