#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/findutils/findutils-4.4.2.tar.gz' \
    'findutils-4.4.2' \
    '' \
    'echo "gl_cv_func_wcwidth_works=yes" > config.cache && echo "ac_cv_func_fnmatch_gnu=yes" >> config.cache' \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --cache-file=config.cache 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for findutils-4.4.2 any longer."
    rm -rf findutils-4.4.2
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    bin/find
    bin/oldfind
    usr/share/man/man1/find.1
    bin/xargs
    usr/share/man/man1/xargs.1
    bin/locate
    bin/updatedb
    libexec/frcode
    libexec/code
    libexec/bigram
    usr/share/man/man1/locate.1
    usr/share/man/man1/updatedb.1
    usr/share/man/man5/locatedb.5
    usr/share/info/find.info
    usr/share/info/find-maint.info
    usr/share/locale/*
    usr/share/gettext/po/*
