#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/gettext/gettext-0.19.6.tar.xz' \
    'gettext-0.19.6/gettext-tools' \
    '' \
    '' \
    '' \
    "EMACS=no ./configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --disable-shared 1>&2" \
    'make -j 20 1>&2 && make -C gnulib-lib && make -C intl pluralx.c && make -C src msgfmt' \
    "make install 1>&2 && cp -v src/msgfmt ${CLFS_NEW_ROOT}/bin"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for gettext-0.19.6 any longer."
    rm -rf gettext-0.19.6
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
cd gettext-tools

EMACS="no" \
./configure \
    --prefix=/tools \
    --build=${CLFS_HOST} \
    --host=${CLFS_TARGET} \
    --disable-shared

make -C gnulib-lib
make -C intl pluralx.c
make -C src msgfmt

cp -v src/msgfmt /tools/bin
