#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/grep/grep-2.22.tar.xz' \
    'grep-2.22' \
    '' \
    '' \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --runstatedir=${CLFS_NEW_ROOT}/var/run \
	  --libdir=${CLFS_NEW_ROOT}/lib --includedir=${CLFS_NEW_ROOT}/usr/include \
	  --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --without-included-regex 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for grep-2.22 any longer."
    rm -rf grep-2.22
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/locale/*
    usr/share/gettext/po/*
    usr/share/info/grep.info
    usr/share/man/man1/grep.1
    usr/share/man/man1/fgrep.1
    usr/share/man/man1/egrep.1
    bin/grep
    bin/fgrep
    bin/egrep
