#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/gzip/gzip-1.6.tar.xz' \
    'gzip-1.6' \
    '' \
    '' \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for gzip-1.6 any longer."
    rm -rf gzip-1.6
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/info/gzip.info
    bin/gzip
    bin/gunzip
    bin/gzexe
    bin/zcat
    bin/zcmp
    bin/zdiff
    bin/zegrep
    bin/zfgrep
    bin/zforce
    bin/zgrep
    bin/zless
    bin/zmore
    bin/znew
    bin/uncompress
  usr/share/man/man1:
    gunzip.1, gzexe.1, gzip.1, zcat.1, zcmp.1, zdiff.1, zforce.1, zgrep.1,
    zless.1, zmore.1, znew.1
