#!/bin/bash  -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/make/make-4.1.tar.bz2' \
    'make-4.1' \
    '' \
    '' \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for make-4.1 any longer."
    rm -rf make-4.1
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/locale/*
    usr/share/gettext/po/*
    usr/share/info/make.info
    bin/make
    usr/include/gnumake.h
    usr/share/man/man1/make.1
