#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/tar/tar-1.28.tar.xz' \
    'tar-1.28' \
    '' \
    '' \
    '' \
    "echo 'gl_cv_func_wcwidth_works=yes' > config.cache && \
	 echo 'gl_cv_func_btowc_eof=yes' >> config.cache && \
	 echo 'ac_cv_func_malloc_0_nonnull=yes' >> config.cache && \
	 echo 'gl_cv_func_mbrtowc_incomplete_state=yes' >> config.cache && \
	 echo 'gl_cv_func_mbrtowc_nul_retval=yes' >> config.cache && \
	 echo 'gl_cv_func_mbrtowc_null_arg1=yes' >> config.cache && \
	 echo 'gl_cv_func_mbrtowc_null_arg2=yes' >> config.cache && \
	 echo 'gl_cv_func_mbrtowc_retval=yes' >> config.cache && \
	 echo 'gl_cv_func_wcrtomb_retval=yes' >> config.cache && \
	 ./configure \
	 --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	 --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	 --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	 --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	 --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	 --cache-file=config.cache 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for tar-1.28 any longer."
    rm -rf tar-1.28
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/info/tar.info
    usr/share/man/man1/tar.1
    usr/share/man/man8/rmt.8
    libexec/rmt
    bin/tar
    usr/share/locale/*
    usr/share/gettext/po/*
