#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#	  --enable-static-programs=losetup,mount,umount,fdisk,sfdisk,blkid,nsenter \
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.kernel.org/pub/linux/utils/util-linux/v2.26/util-linux-2.26.1.tar.xz' \
    'util-linux-2.26.1' \
    '' \
    '' \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --disable-makeinstall-chown \
	  --disable-makeinstall-setuid \
	  --without-python 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
mkdir -pv ${CLFS_NEW_ROOT}/var/lib/hwclock/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for util-linux-2.26.1 any longer."
    rm -rf util-linux-2.26.1
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/locale/*
    usr/share/gettext/po/*
    bin/more
    bin/dmesg
    bin/mount
    bin/umount
    bin/wdctl
    bin/mountpoint
    bin/lsblk
    bin/findmnt
    bin/kill
    bin/dmesg
    lib/libmount.a
    lib/libmount.la
    lib/libmount.so
    lib/libmount.so.1
    lib/libmount.so.1.1.0
    lib/libblkid.a
    lib/libblkid.la
    lib/libblkid.so
    lib/libblkid.so.1
    lib/libblkid.so.1.1.0
    lib/libuuid.a
    lib/libuuid.la
    lib/libuuid.so
    lib/libuuid.so.1
    lib/libuuid.so.1.3.0
    lib/libsmartcols.a
    lib/libsmartcols.la
    lib/libsmartcols.so
    lib/libsmartcols.so.1
    lib/libsmartcols.so.1.1.0
    lib/libfdisk.a
    lib/libfdisk.la
    lib/libfdisk.so
    lib/libfdisk.so.1
    lib/libfdisk.so.1.1.0
    usr/share/bash-completion/*
    usr/share/doc/util-linux/*
    usr/share/man/*
    usr/include/*
    var/lib/hwclock/

  sbin:
    agetty, sulogin, nologin, fstrim, ctrlaltdel, fsfreeze, blkdiscard, losetup,
    zramctl, swapon, swapoff, chcpu, pivot_root, switch_root, hwclock, blkid,
    findfs, wipefs, fsck.minix, mkfs.minix, mkfs, mkfs.bfs, mkswap, swaplabel,
    fsck, raw, fsck.cramfs, mkfs.cramfs, blockdev, fdisk, sfdisk, cfdisk,
    readprofile, ldattach, rtcwake, uuidd, fdformat, partx, addpart, delpart,
    resizepart
  bin:
    chrt, ionice, taskset, col, colcrt, colrm, column, hexdump, rev, tailf, pg,
    ul, script, scriptreplay, setterm, mesg, wall, last, utmpdump, lslogins,
    flock, ipcmk, ipcrm, ipcs, renice, setsid, setarch, eject, prlimit, lscpu,
    fallocate, unshare, nsenter, cal, logger, look, mcookie, namei, whereis,
    lslocks, uuidgen, rename, getopt, isosize,
    uname, uname26, linux32, linux64, i386, x86_64
