#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
export NOMAKEDISTCLEAN=nope

${WHERE_I_AM}/INSTALL.parameters \
    'wget -N ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2' \
    'vim74' \
    'wget -N http://patches.clfs.org/sysvinit/vim-7.4-branch_update-7.patch' \
    'patch -Np1 -i ${TARSAT}/${PATCHNAME} 1>&2' \
    '' \
    "echo 'vim_cv_getcwd_broken=no' > src/auto/config.cache && \
	 echo 'vim_cv_memmove_handles_overlap=yes' >> src/auto/config.cache && \
	 echo 'vim_cv_stat_ignores_slash=no' >> src/auto/config.cache && 
	 echo 'vim_cv_terminfo=yes' >> src/auto/config.cache && 
	 echo 'vim_cv_toupper_broken=no' >> src/auto/config.cache && 
	 echo 'vim_cv_tty_group=world' >> src/auto/config.cache && 
	 echo '#define SYS_VIMRC_FILE \"/etc/vimrc\"' >> src/feature.h && 
	 ./configure \
	 --build=${CLFS_HOST} --host=${CLFS_TARGET} --prefix=${CLFS_NEW_ROOT} \
	 --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	 --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	 --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	 --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	 --enable-gui=no \
	 --disable-gtktest \
	 --disable-xim \
	 --disable-gpm \
	 --without-x \
	 --disable-netbeans \
	 --with-tlib=ncurses 1>&2" \
    'make -j 20 1>&2' \
    'cd src && make installvimbin 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
ln -sfv vim ${CLFS_NEW_ROOT}/bin/vi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cat > ${CLFS_NEW_ROOT}/etc/vimrc << "EOF"
" Begin /etc/vimrc

set nocompatible
set backspace=2
set ruler
syntax on

" End /etc/vimrc
EOF
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Need syntax file -- do nothing in it.
mkdir -pv ${CLFS_NEW_ROOT}/usr/share/vim/vim74/syntax
cat > ${CLFS_NEW_ROOT}/usr/share/vim/vim74/syntax/syntax.vim << "EOF"
finish
EOF
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for vim74 any longer."
    rm -rf vim74
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    bin/vim
    bin/vi
    usr/share/vim/vim74/syntax/*
