#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://tukaani.org/xz/xz-5.2.2.tar.xz' \
    'xz-5.2.2' \
    '' \
    '' \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for xz-5.2.2 any longer."
    rm -rf xz-5.2.2
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/include/lzma/*
    usr/include/lzma.h
    lib/liblzma.a
    lib/liblzma.la
    lib/liblzma.so
    lib/liblzma.so.5
    lib/liblzma.so.5.2.1
    lib/pkgconfig/liblzma.pc
    usr/share/man/man1/xzdec.1
    usr/share/man/man1/lzmadec.1
    usr/share/locale/*
    usr/share/gettext/po/*
    usr/share/doc/xz/*
  bin:
    xzdec, lzmadec, xz, unxz, xzcat, lzma, unlzma, lzcat, lzmainfo, xzdiff,
    xzgrep, xzmore, xzless,
    xzdiff-xzcmp, xzgrep-xzegrep, xzgrep-xzfgrep, xzdiff-lzdiff, xzdiff-lzcmp,
    xzgrep-lzgrep, xzgrep-lzegrep, xzgrep-lzfgrep, xzmore-lzmore, xzless-lzless
  usr/share/man/man1:
    xzdec.1, lzmadec.1, xz.1, unxz.1, xzcat.1, lzma.1, unlzma.1, lzcat.1,
    lzmainfo.1, xzdiff.1, xzgrep.1, xzmore.1, xzless.1,
    xzdiff-xzcmp.1, xzgrep-xzegrep.1, xzgrep-xzfgrep.1, xzdiff-lzdiff.1,
    xzdiff-lzcmp.1, xzgrep-lzgrep.1, xzgrep-lzegrep.1, xzgrep-lzfgrep.1,
    xzmore-lzmore.1, xzless-lzless.1
