#!/bin/bash -e
. 1.clfs.set.variables
#=============================================================================
echo 'If either command below fails, you must boot the new system and continue making programs.'
echo 'Next is Chapter 7 if failure occurs -- 078-bc'

${CLFS_NEW_ROOT}/lib/libc.so.6 || exit 1
${CLFS_NEW_ROOT}/bin/gcc -v || exit 1

echo 'You may chroot and continue compiling: Chapter 8 -- 098-kernfs'
exit 0
#=============================================================================
