#!/bin/bash  -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N ftp://alpha.gnu.org/gnu/bc/bc-1.06.95.tar.bz2' \
    'bc-1.06.95' \
    '' \
    '' \
    '' \
    "./configure \
	  --host=${MACHINE} --prefix=${CLFSCROSSTOOLS} --bindir=${CLFS_NEW_ROOT}/bin \
	  --sbindir=${CLFS_NEW_ROOT}/sbin --libexecdir=${CLFS_NEW_ROOT}/libexec \
	  --datadir=${CLFS_NEW_ROOT}/usr/share --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --infodir=${CLFS_NEW_ROOT}/usr/share/info \
	  --mandir=${CLFS_NEW_ROOT}/usr/share/man 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for bc-1.06.95 any longer."
    rm -rf bc-1.06.95
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    bin/bc
    bin/dc
    usr/share/info/bc.info
    usr/share/info/dc.info
    usr/share/man/man1/bc.1
    usr/share/man/man1/dc.1
