#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.42.13/e2fsprogs-1.42.13.tar.xz' \
    'e2fsprogs-1.42.13' \
    '' \
    '' \
    'e2fsprogs-1.42.13/build' \
    "../configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --enable-elf-shlibs \
	  --disable-libblkid \
	  --disable-libuuid \
	  --disable-fsck \
	  --disable-uuidd 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for e2fsprogs-1.42.13 any longer."
    rm -rf e2fsprogs-1.42.13
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    sbin/e2fsck
    sbin/fsck.ext2
    sbin/fsck.ext3
    sbin/fsck.ext4
    sbin/fsck.ext4dev
    usr/share/man/man8/e2fsck.8
    usr/share/man/man8/fsck.ext2.8
    usr/share/man/man8/fsck.ext3.8
    usr/share/man/man8/fsck.ext4.8
    usr/share/man/man8/fsck.ext4dev.8
    sbin/debugfs
    usr/share/man/man8/debugfs.8
    sbin/mke2fs
    sbin/badblocks
    sbin/mke2fs
    sbin/badblocks
    sbin/tune2fs
    sbin/dumpe2fs
    sbin/logsave
    sbin/e2image
    sbin/e2undo
    sbin/mklost+found
    sbin/filefrag
    sbin/e2freefrag
    sbin/e4defrag
    sbin/mkfs.ext2
    sbin/mkfs.ext3
    sbin/mkfs.ext4
    sbin/mkfs.ext4dev
    bin/chattr
    bin/lsattr
    lib/e2initrd_helper
    usr/share/man/man8/tune2fs.8
    usr/share/man/man8/mklost+found.8
    usr/share/man/man8/mke2fs.8
    usr/share/man/man8/dumpe2fs.8
    usr/share/man/man8/badblocks.8
    usr/share/man/man8/e2label.8
    usr/share/man/man8/e2image.8
    usr/share/man/man8/logsave.8
    usr/share/man/man8/filefrag.8
    usr/share/man/man8/e2freefrag.8
    usr/share/man/man8/e2undo.8
    usr/share/man/man8/e4defrag.8
    usr/share/man/man1/chattr.1
    usr/share/man/man1/lsattr.1
    usr/share/man/man5/mke2fs.conf.5
    usr/share/man/man5/ext4.5
    etc/mke2fs.conf
    sbin/resize2fs
    usr/share/man/man8/resize2fs.8
    usr/share/locale/*
    usr/share/gettext/po/*
    lib/libcom_err.so
    lib/libcom_err.so.2
    lib/libcom_err.so.2.1
    lib/libss.so
    lib/libss.so.2
    lib/libss.so.2.0
    lib/libe2p.so
    lib/libe2p.so.2
    lib/libe2p.so.2.3
    lib/libext2fs.so
    lib/libext2fs.so.2
    lib/libext2fs.so.2.4
    usr/share/info/libext2fs.info
