#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-21.tar.xz' \
    'kmod-21' \
    '' \
    "cp -v libkmod/libkmod.c libkmod/libkmod.c.orig 1>&2 && sed '/dirname_default_prefix /s@/lib/modules@${CLFS_NEW_ROOT}&@' libkmod/libkmod.c.orig > libkmod/libkmod.c" \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --with-xz \
	  --with-zlib 1>&2" \
    'make -j 21 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
ln -sfv kmod ${CLFS_NEW_ROOT}/bin/lsmod
for tool in depmod insmod modprobe modinfo rmmod; do
    ln -sfv ../bin/kmod ${CLFS_NEW_ROOT}/sbin/${tool}
done
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for kmod-21 any longer."
    rm -rf kmod-21
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    lib/libkmod.la
    lib/libkmod.so
    lib/libkmod.so.2
    lib/libkmod.so.2.2.10
    bin/kmod
    usr/share/bash-completion/*
    usr/include/libkmod.h
    lib/pkgconfig/libkmod.pc
    usr/share/man/man5/depmod.d.5
    usr/share/man/man5/modprobe.d.5
    usr/share/man/man5/modules.dep.5
    usr/share/man/man5/modules.dep.bin.5
    bin/modprobe
    bin/lsmod
    bin/depmod
    bin/insmod
    bin/rmmod
    bin/modinfo
  usr/share/man/man8:
    kmod.8, depmod.8, insmod.8, lsmod.8, rmmod.8, modprobe.8, modinfo.8
