#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://download.savannah.gnu.org/releases/sysvinit/sysvinit-2.88dsf.tar.bz2' \
    'sysvinit-2.88dsf' \
    'wget -N http://patches.clfs.org/sysvinit/sysvinit-2.88dsf-tools_updates-1.patch' \
    'patch -Np1 -i ${TARSAT}/${PATCHNAME} 1>&2' \
    '' \
    "make -C src clobber 1>&2" \
    "make -C src CC=\"${CC}\" 1>&2" \
    "make -C src ROOT=${CLFS_NEW_ROOT} install 1>&2"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cat > ${CLFS_NEW_ROOT}/etc/inittab << "EOF"
# Begin /etc/inittab

id:3:initdefault:

si::sysinit:/etc/rc.d/init.d/rc sysinit

l0:0:wait:/etc/rc.d/init.d/rc 0
l1:S1:wait:/etc/rc.d/init.d/rc 1
l2:2:wait:/etc/rc.d/init.d/rc 2
l3:3:wait:/etc/rc.d/init.d/rc 3
l4:4:wait:/etc/rc.d/init.d/rc 4
l5:5:wait:/etc/rc.d/init.d/rc 5
l6:6:wait:/etc/rc.d/init.d/rc 6

ca:12345:ctrlaltdel:/sbin/shutdown -t1 -a -r now

su:S016:once:/sbin/sulogin

# Virtual Terminals

1:2345:respawn:/sbin/agetty --noclear -I '\033(K' tty1 9600
2:2345:respawn:/sbin/agetty --noclear -I '\033(K' tty2 9600
3:2345:respawn:/sbin/agetty --noclear -I '\033(K' tty3 9600
4:2345:respawn:/sbin/agetty --noclear -I '\033(K' tty4 9600
5:2345:respawn:/sbin/agetty --noclear -I '\033(K' tty5 9600
6:2345:respawn:/sbin/agetty --noclear -I '\033(K' tty6 9600

# Serial Port

# c0:12345:respawn:/sbin/agetty --noclear 115200 ttyS0 vt100

# End /etc/inittab
EOF
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for sysvinit-2.88dsf any longer."
    rm -rf sysvinit-2.88dsf
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
  sbin:
    init, halt, shutdown, runlevel, killall5, fstab-decode, bootlogd, reboot,
    poweroff, telinit
  pin:
    pidof, last
  usr/bin:
    lastb
  usr/include:
    initreq.h
  usr/share/man/man5:
    initscript.5, inittab.5
  usr/share/man/man8:
    halt.8, init.8, killall5.8, pidof.8, poweroff.8, reboot.8, runlevel.8,
    shutdown.8, telinit.8, fstab-decode.8, bootlogd.8
