#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cp ${WHERE_I_AM}/diff.M4.eudev.patch ${CLFSTARS}/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://dev.gentoo.org/~blueness/eudev/eudev-3.0.tar.gz' \
    'eudev-3.0' \
    '' \
    'patch -Np1 -i ${TARSAT}/diff.M4.eudev.patch 1>&2' \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --disable-introspection \
	  --disable-gtk-doc-html \
	  --disable-gudev \
	  --disable-keymap \
	  --with-firmware-path=${CLFS_NEW_ROOT}/lib/firmware \
	  --enable-libkmod \
	  --enable-rule_generator 1>&2" \
    'make -j 20 1>&2' \
    "make install 1>&2 && install -dv ${CLFS_NEW_ROOT}/lib/firmware 1>&2"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
echo "# dummy, so that network is once again on eth*" > ${CLFS_NEW_ROOT}/etc/udev/rules.d/80-net-name-slot.rules

# FIX udevadm that gets full CLFS_NEW_ROOT tacked in from of symbolic link.
ln -svf ../bin/udevadm ${CLFS_NEW_ROOT}/sbin/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for eudev-3.0 any longer."
    rm -rf eudev-3.0
    rm -f ${CLFSTARS}/diff.M4.eudev.patch
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    lib/libudev.a
    lib/libudev.la
    lib/libudev.so
    lib/libudev.so.1
    lib/libudev.so.1.6.2
    lib/pkgconfig/libudev.pc
    usr/share/pkgconfig/libudev.pc
    bin/udevadm
    sbin/udevd
    sbin/udevadm
    etc/udev/*
    lib/udev/*
    usr/share/man/man5/udev.conf.5
    usr/share/man/man7/udev.7
    usr/share/man/man8/udevd.8
    usr/share/man/man8/udevadm.8
  usr/include:
    libudev.h, udev.h
