#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if [ "${LINUX_CONFIGURATION}" = "" ]; then
#?  export LINUX_CONFIGURATION=SAVED.CONFIG.linux-4.9.1
  export LINUX_CONFIGURATION=SAVED.CONFIG.linux-4.9.1.nommu
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
export NOMAKEDISTCLEAN=nope
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.kernel.org/pub/linux/kernel/v4.x/linux-4.9.1.tar.xz' \
    'linux-4.9.1' \
    '' \
    '' \
    '' \
    "make mrproper 1>&2 && \
	  sed -e 's/NEW_MACHINE_NAME/${NEW_MACHINE_NAME}/' ${WHERE_I_AM}/${LINUX_CONFIGURATION} > .config && \
	  make ARCH=${MACHINE} CROSS_COMPILE=${CLFS_TARGET}- oldconfig 1>&2" \
    "make ARCH=${MACHINE} INSTALL_HDR_PATH=${CLFS_NEW_ROOT}/usr CROSS_COMPILE=${CLFS_TARGET}- -j 20 1>&2" \
    "make ARCH=${MACHINE} INSTALL_HDR_PATH=${CLFS_NEW_ROOT}/usr CROSS_COMPILE=${CLFS_TARGET}- INSTALL_MOD_PATH=${CLFS_NEW_ROOT} firmware_install 1>&2"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
mkdir -pv ${CLFS_NEW_ROOT}/boot

(cd linux-4.9.1 && \
	cp -v arch/${MACHINE}/boot/bzImage ${CLFS_NEW_ROOT}/boot/vmlinuz-4.9.1 && \
	cp -v System.map ${CLFS_NEW_ROOT}/boot/System.map-4.9.1 && \
	cp -v .config ${CLFS_NEW_ROOT}/boot/config-4.9.1 && \
	cp -v .config ${WHERE_I_AM}/${LINUX_CONFIGURATION}.new)

# Do not need to load firmware into anything.
rm -rf ${CLFS_NEW_ROOT}/lib/firmware
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
#     echo "Do not need source for linux-4.9.1 any longer."
#     rm -rf linux-4.9.1
# fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Manual kernel cross-build:
    . 1.clfs.set.variables
    cd linux-4.9.1
    export ARCH=${MACHINE} CROSS_COMPILE=${CLFS_TARGET}-
    cp ${WHERE_I_AM}/${LINUX_CONFIGURATION} .config
    make oldconfig
    make -j 20
    cp -v arch/${MACHINE}/boot/bzImage ${CLFS_NEW_ROOT}/boot/vmlinuz-4.9.1
    cp -v System.map ${CLFS_NEW_ROOT}/boot/System.map-4.9.1
    cp -v .config ${CLFS_NEW_ROOT}/boot/config-4.9.1
#=============================================================================
Installs (new_root):
    boot/vmlinuz-4.9.1
    boot/System.map-4.9.1
    boot/config-4.9.1
