#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/grub/grub-2.00.tar.xz' \
    'grub-2.00' \
    '' \
    "cp -v grub-core/gnulib/stdio.in.h grub-core/gnulib/stdio.in.h.orig 1>&2 && \
	  sed -e '/gets is a/d' grub-core/gnulib/stdio.in.h.orig > grub-core/gnulib/stdio.in.h" \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --disable-werror \
	  --enable-grub-mkfont=no \
	  --with-bootdir=${CLFS_NEW_ROOT}/boot 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Do not need the grub completion stuff -- and it don't work anyway and gives errors upon bash startup.
rm -f ${CLFS_NEW_ROOT}/etc/bash_completion.d/grub
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for grub-2.00 any longer."
    rm -rf grub-2.00
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    etc/grub.d/*
    usr/share/grub/*
    lib/grub/*
    usr/share/locale/*
    usr/share/gettext/po/*
    etc/bash_completion.d/grub
  bin:
    grub-mkimage, grub-mkrelpath, grub-script-check, grub-editenv,
    grub-mkpasswd-pbkdf2, grub-fstest, grub-mklayout, grub-menulst2cfg,
    grub-mkrescue, grub-mkstandalone, grub-kbdcomp
  sbin:
    grub-probe, grub-bios-setup, grub-sparc64-setup, grub-ofpathname,
    grub-install, grub-mknetdir, grub-mkconfig, grub-set-default, grub-reboot
  usr/share/info:
    grub.info, grub-dev.info
