#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
mkdir -pv ${CLFS_NEW_ROOT}/{bin,boot,dev,{etc/,}opt,home,lib/firmware,mnt}
mkdir -pv ${CLFS_NEW_ROOT}/{proc,media/{floppy,cdrom},run/{,shm},sbin,srv,sys}
mkdir -pv ${CLFS_NEW_ROOT}/var/{lock,log,mail,spool}
mkdir -pv ${CLFS_NEW_ROOT}/var/{opt,cache,lib/{misc,locate},local}
install -dv -m 0750 ${CLFS_NEW_ROOT}/root
install -dv -m 1777 ${CLFS_NEW_ROOT}{/var,}/tmp
ln -sfv ../run ${CLFS_NEW_ROOT}/var/run
mkdir -pv ${CLFS_NEW_ROOT}/usr/{,local/}{bin,include,lib,sbin,src}
mkdir -pv ${CLFS_NEW_ROOT}/usr/{,local/}share/{doc,info,locale,man}
mkdir -pv ${CLFS_NEW_ROOT}/usr/{,local/}share/{misc,terminfo,zoneinfo}
mkdir -pv ${CLFS_NEW_ROOT}/usr/{,local/}share/man/man{1,2,3,4,5,6,7,8}
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
