#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
ln -sfv ../../bin/file ${CLFS_NEW_ROOT}/usr/bin/
ln -sfv bash ${CLFS_NEW_ROOT}/bin/sh

ln -sfv ../../lib/libgcc_s.so{,.1} ${CLFS_NEW_ROOT}/usr/lib
ln -sfv ../../lib/libstdc++.so{.6,} ${CLFS_NEW_ROOT}/usr/lib

#-- libdir='/home/m4/src/LinuxFromScratch/new_root/lib/../lib'
#-- sed -e "s;${CLFS_NEW_ROOT};/usr;" ${CLFS_NEW_ROOT}/lib64/libstdc++.la > /tmp/AAA
#-- mv /tmp/AAA ${CLFS_NEW_ROOT}/usr/lib/libstdc++.la

#-- mkdir -pv ${CLFS_NEW_ROOT}/usr/lib64
#-- ln -sfv ../../lib/libstdc++.so{.6,} ${CLFS_NEW_ROOT}/usr/lib64

ln -sfv /proc/self/mounts ${CLFS_NEW_ROOT}/etc/mtab
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
