#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cat > ${CLFS_NEW_ROOT}/root/.bash_profile << "EOF"
set +h
export PS1='\u:\w\$ '
export LC_ALL=POSIX
export PATH=/bin:/usr/bin:/sbin:/usr/sbin:
alias ls='ls -FC'
EOF
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
