#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cp ${WHERE_I_AM}/diff.M4.tcl.patch ${CLFSTARS}/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://downloads.sourceforge.net/tcl/tcl8.6.4-src.tar.gz' \
    'tcl8.6.4/unix' \
    '' \
	'cd ../ && patch -Np3 -i ${TARSAT}/diff.M4.tcl.patch 1>&2' \
    '' \
    "./configure --prefix=${CLFS_NEW_ROOT} \
	  --build=${CLFS_HOST} --host=${CLFS_TARGET} --target=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --infodir=${CLFS_NEW_ROOT}/usr/share/info \
	  --mandir=${CLFS_NEW_ROOT}/usr/share/man 1>&2" \
    'make -j 20 1>&2' \
    'make install install-private-headers 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
ln -sfv tclsh8.6 ${CLFS_NEW_ROOT}/bin/tclsh
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source nor patch for tcl8.6.4 any longer."
    rm -rf tcl8.6.4
    rm -f ${CLFSTARS}/diff.M4.tcl.patch
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    lib/libtcl8.6.so
    lib/libtclstub8.6.a
    bin/tclsh8.6
    lib/tclConfig.sh
    lib/tclooConfig.sh
    lib/tcl8/*
    lib/tcl8.6/*
    lib/pkgconfig/tcl.pc
    usr/include/*
    lib/itcl4.0.3/*
    usr/share/man/*
    lib/sqlite3.8.8.3/*
    lib/tdbc1.0.3/*
    lib/tdbcmysql1.0.3/*
    lib/tdbcodbc1.0.3/*
    lib/tdbcpostgres1.0.3/*
    lib/thread2.7.2/*
    bin/tclsh
