#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cp ${WHERE_I_AM}/diff.M4.flex.patch ${CLFSTARS}/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://downloads.sourceforge.net/flex/flex-2.5.39.tar.bz2' \
    'flex-2.5.39' \
    '' \
    'patch -Np3 -i ${TARSAT}/diff.M4.flex.patch 1>&2' \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --target=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cat > ${CLFS_NEW_ROOT}/usr/bin/lex << "EOF"
#!/bin/sh
# Begin /usr/bin/lex

exec /bin/flex -l "$@"

# End /usr/bin/lex
EOF
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chmod -v 755 ${CLFS_NEW_ROOT}/usr/bin/lex
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source nor patch for flex-2.5.39 any longer."
    rm -rf flex-2.5.39
	rm -f ${CLFSTARS}/diff.M4.flex.patch
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    lib/libfl.a
    lib/libfl.la
    lib/libfl.so
    lib/libfl.so.2
    lib/libfl.so.2.0.0
    lib/libfl_pic.a
    lib/libfl_pic.la
    lib/libfl_pic.so
    lib/libfl_pic.so.2
    lib/libfl_pic.so.2.0.0
    bin/flex
    usr/include/FlexLexer.h
    usr/share/doc/flex/*
    usr/share/info/flex.info
    usr/share/man/man1/flex.1
    usr/share/locale/*
    usr/share/gettext/po/*
    usr/bin/lex
