#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
echo 'Ignore the generation of bison reference material by executing "bison" to get version.'
echo 'That is what the errors about bison.1.t is about.'
# That is what the two -i's on the makes does.
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.xz' \
    'bison-3.0.4' \
    '' \
    '' \
    '' \
    "./configure --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --target=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share 1>&2" \
    'make -i -j 20 1>&2' \
    'make -i install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for bison-3.0.4 any longer."
    rm -rf bison-3.0.4
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/locale/*
    usr/share/gettext/po/*
    bin/bison
    bin/yacc
    lib/liby.a
    usr/share/aclocal/*
    usr/share/doc/bison/*
    usr/share/info/bison.info
    usr/share/bison/*
    usr/share/man/man1/bison.1
    usr/share/man/man1/yacc.1
