#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.xz' \
    'libtool-2.4.6' \
    '' \
    '' \
    '' \
    "./configure --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --target=${CLFS_TARGET} \
	  --bindir=${CLFS_NEW_ROOT}/bin --sbindir=${CLFS_NEW_ROOT}/sbin \
	  --libexecdir=${CLFS_NEW_ROOT}/libexec --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for libtool-2.4.6 any longer."
    rm -rf libtool-2.4.6
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    lib/libltdl.a
    lib/libltdl.la
    lib/libltdl.so
    lib/libltdl.so.7
    lib/libltdl.so.7.3.1
    bin/libtoolize
    usr/share/libtool/*
    usr/include/ltdl.h
    usr/include/libltdl/*
  usr/share/man/man1:
    libtool.1, libtoolize.1
  usr/share/info:
    libtool.info, libtool.info-1, libtool.info-2
  usr/share/aclocal:
    libtool.m4, ltargz.m4, ltdl.m4, ltoptions.m4, ltsugar.m4, ltversion.m4,
    lt~obsolete.m4
