#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-4.1.1.tar.xz' \
    'iproute2-4.1.1' \
    '' \
    '' \
    '' \
    "sed -i '/^TARGETS/s@arpd@@g' misc/Makefile 1>&2 && sed -i -e '/ARPD/d' -e 's/^CC = gcc/CC ?= gcc/' Makefile 1>&2 && sed -i 's/arpd.8//' man/man8/Makefile 1>&2" \
    "export DESTDIR=${CLFS_NEW_ROOT} 1>&2 && make -j 20 1>&2" \
    "export DESTDIR=${CLFS_NEW_ROOT} 1>&2 && make install 1>&2"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for iproute2-4.1.1 any longer."
    rm -rf iproute2-4.1.1
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    etc/iproute2/*
    usr/share/doc/iproute2/*
    usr/lib/tc/*
    usr/share/man/man3/libnetlink.3
    usr/share/man/man7/tc-hfsc.3
  sbin:
    ip, rtmon, ifcfg, rtpr, routel, routef, tc, bridge, ss, nstat, ifstat,
    rtacct, lnstat, rtstat, ctstat, genl
  usr/share/man/man8:
    ip-address.8, ip-link.8, ip-route.8, ip.8, , lnstat.8, routel.8, rtacct.8,
    rtmon.8, ss.8, tc.8, tc-bfifo.8, tc-cbq.8, tc-cbq-details.8, tc-choke.8,
    tc-codel.8, tc-drr.8, tc-ematch.8, tc-fq_codel.8, tc-hfsc.8, tc-htb.8,
    tc-pie.8, tc-mqprio.8, tc-netem.8, tc-pfifo.8, tc-pfifo_fast.8, tc-prio.8,
    tc-red.8, tc-sfb.8, tc-sfq.8, tc-stab.8, tc-tbf.8, bridge.8, rtstat.8,
    ctstat.8, nstat.8, routef.8, ip-addrlabel.8, ip-fou.8, ip-gue.8, ip-l2tp.8,
    ip-maddress.8, ip-monitor.8, ip-mroute.8, ip-neighbour.8, ip-netns.8,
    ip-ntable.8, ip-rule.8, ip-tunnel.8, ip-xfrm.8, ip-tcp_metrics.8,
    ip-netconf.8, ip-token.8
