#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/gdbm/gdbm-1.11.tar.gz' \
    'gdbm-1.11' \
    '' \
    '' \
    '' \
    './configure \
	  --enable-libgdbm-compat \
	  --prefix=${CLFS_NEW_ROOT}/usr --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --target=${CLFS_TARGET} 1>&2' \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for gdbm-1.11 any longer."
    rm -rf gdbm-1.11
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/locale/*
    usr/share/gettext/po/*
    usr/lib/libgdbm.a
    usr/lib/libgdbm.la
    usr/lib/libgdbm.so
    usr/lib/libgdbm.so.4
    usr/lib/libgdbm.so.4.0.0
    usr/lib/libgdbm_compat.a
    usr/lib/libgdbm_compat.la
    usr/lib/libgdbm_compat.so
    usr/lib/libgdbm_compat.so.4
    usr/lib/libgdbm_compat.so.4.0.0
    usr/include/gdbm.h
    usr/share/info/gdbm.info
    usr/share/man/man3/gdbm.3
  usr/bin:
    gdbmtool, gdbm_load, gdbm_dump
  usr/share/man/man1:
    gdbm_dump.1, gdbm_load.1, gdbmtool.1
