#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Cannot have static on the following.
export LD="${CLFS_TARGET}-ld"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cd ${CLFSSOURCES}
set -x
#=============================================================================
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Cannot have "make -j 20" for perl.
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.cpan.org/src/5.0/perl-5.20.2.tar.bz2' \
    'perl-5.20.2' \
    'wget -N https://raw.github.com/arsv/perl-cross/releases/perl-5.20.2-cross-0.9.6.tar.gz' \
    'tar xf ${TARSAT}/${PATCHNAME} -C .. 1>&2' \
    '' \
    "export CC='${CROSS_CC}' CFLAGS='${CROSS_CFLAGS}' && ./configure --prefix=/usr --target=${CLFS_TARGET} 1>&2" \
    "export CC='${CROSS_CC}' CFLAGS='${CROSS_CFLAGS}' && make 1>&2" \
    "export CC='${CROSS_CC}' CFLAGS='${CROSS_CFLAGS}' && make DESTDIR='${CLFS_NEW_ROOT}' install 1>&2" \
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for perl-5.20.2 any longer."
    rm -rf perl-5.20.2
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/lib/perl5/*
    usr/man/man1/a2p.1
    usr/man/man1/perl.1
    usr/man/man1/perl*.1
    usr/man/man1/pod*.1
    usr/share/man/man3/*
  usr/share/man/man1:
    c2ph.1, pstruct.1, cpan.1, config_data.1, corelist.1, enc2xs.1, h2ph.1,
    h2xs.1, instmodsh.1, json_pp.1, libnetcfg.1, perbug.1, perlthanks.1,
    perlivp.1, piconv.1, pl2pm.1, pod2html.1, prove.1, ptar.1, ptardiff.1,
    ptargrep.1, shasum.1, splain.1, xsubpp.1, zipdetails.1, find2perl.1,
    s2p.1, psed.1
  usr/bin:
    perl5.20.2, perl, a2p, pod2man, pod2text, pod2usage, podchecker, podselect,
    c2ph, cpan, config_data, corelist, enc2xs, h2ph, h2xs, instmodsh, json_pp,
    libnetcfg, perlbug, perldoc, perlivp, piconv, pl2pm, pod2html, prove, ptar,
    ptardiff, ptargrep, shasum, splain, xsubpp, zipdetails, find2perl, s2p,
    pstruct, perlthanks, psed
