#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.xz' \
    'autoconf-2.69' \
    '' \
    '' \
    '' \
    "./configure --prefix=${CLFS_NEW_ROOT}/usr --build=${CLFS_HOST} --host=${CLFS_TARGET} --target=${CLFS_TARGET} 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for autoconf-2.69 any longer."
    rm -rf autoconf-2.69
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/autoconf/*
    usr/share/info/autoconf.info
    usr/share/info/standards.info
  usr/bin:
    autom4te, autoconf, autoheader, autoreconf, ifnames, autoscan, autoupdate
  usr/share/man/man1:
    autoconf.1, autoheader.1, autom4te.1, autoreconf.1, autoscan.1,
    autoupdate.1, ifnames.1, config.guess.1, config.sub.1
