#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/automake/automake-1.15.tar.xz' \
    'automake-1.15' \
    '' \
    '' \
    '' \
    "./configure \
	  --docdir=${CLFS_NEW_ROOT}/usr/share/doc/automake-1.15 \
	  --prefix=${CLFS_NEW_ROOT}/usr --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --target=${CLFS_TARGET} 1>&2" \
    'make -j 20 1>&2' \
    'make -i install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for automake-1.15 any longer."
    rm -rf automake-1.15
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/bin/automake
    usr/bin/aclocal
    usr/bin/automake-1.15
    usr/bin/aclocal-1.15
    usr/share/automake-1.15/*
    usr/share/aclocal-1.15/*
    usr/share/doc/automake-1.15/*
    usr/share/aclocal/*
  usr/share/info:
    automake.info, automake.info-1, automake.info-2, automake-history.info
  usr/share/man/man1:
    aclocal.1, automake.1, aclocal-1.15.1, automake-1.15.1
