#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.greenwoodsoftware.com/less/less-481.tar.gz' \
    'less-481' \
    '' \
    '' \
    '' \
    "./configure \
	  --sysconfdir=${CLFS_NEW_ROOT}/etc \
	  --prefix=${CLFS_NEW_ROOT}/usr --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --target=${CLFS_TARGET} 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
mv -v ${CLFS_NEW_ROOT}/usr/bin/less ${CLFS_NEW_ROOT}/bin
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for less-481 any longer."
    rm -rf less-481
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
  bin/less
  usr/bin:
    less, lesskey, lessecho
  usr/share/man/man1:
    less.1, lesskey.1, lessecho.1
