#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://clfs.org/files/packages/sysvinit/iputils-s20150815.tar.xz' \
    'iputils-s20150815' \
    'wget -N http://patches.clfs.org/sysvinit/iputils-s20150815-build-1.patch' \
    'patch -Np1 -i ${TARSAT}/${PATCHNAME} 1>&2' \
    '' \
    'true' \
    'make '"CC='${CC}'"' USE_CAP=no IPV4_TARGETS="tracepath ping clockdiff" IPV6_TARGETS="tracepath6 traceroute6" -j 20 1>&2' \
    "install -v -m755 ping ${CLFS_NEW_ROOT}/bin/ 1>&2 && install -v -m755 clockdiff ${CLFS_NEW_ROOT}/usr/bin/ 1>&2 && install -v -m755 tracepath ${CLFS_NEW_ROOT}/usr/bin/ 1>&2 && install -v -m755 tracepath6 traceroute6 ${CLFS_NEW_ROOT}/usr/bin/ 1>&2"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for iputils-s20150815 any longer."
    rm -rf iputils-s20150815
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    bin/ping
    usr/bin/clockdiff
    usr/bin/tracepath
    usr/bin/tracepath6
    usr/bin/traceroute6
