#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.kernel.org/pub//linux/utils/kbd/kbd-2.0.3.tar.xz' \
    'kbd-2.0.3' \
    '' \
    '' \
    '' \
    "PKG_CONFIG_PATH='${CLFS_NEW_ROOT}/lib/pkgconfig' \
	  ./configure \
	  --prefix=${CLFS_NEW_ROOT}/usr \
	  --disable-vlock \
	  --enable-optional-progs \
	  --build=${CLFS_HOST} --host=${CLFS_TARGET} --target=${CLFS_TARGET} 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
mv -v ${CLFS_NEW_ROOT}/usr/bin/{dumpkeys,kbd_mode,loadkeys,setfont} ${CLFS_NEW_ROOT}/bin/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for kbd-2.0.3 any longer."
    rm -rf kbd-2.0.3
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/consolefonts/*
    usr/share/consoletrans/*
    usr/share/unimaps/*
    usr/share/keymaps/*
    usr/share/locale/*
    usr/share/gettext/po/*
    usr/share/man/man5/keymaps.5
  bin:
    dumpkeys, kbd_mode, loadkeys, setfont,
  usr/bin:
    mapscrn, loadunimap, showkey, showconsolefont, setleds, setmetamode, 
    psfxtable, fgconsole, kbdrate, chvt, deallocvt, openvt, kbdinfo,
    setvtrgb, getkeycodes, setkeycodes, resizecons, setlogcons, setvesablank,
    getunimap, clrunimap, outpsfheader, setpalette, screendump,
    spawn_console, spawn_login, unicode_start, unicode_stop, psfaddtable,
    psfgettable, psfstriptable
  usr/share/man/man1:
    chvt.1, deallocvt.1, fgconsole.1, kbd_mode.1, openvt.1, psfaddtable.1,
    psfgettable.1, psfstriptable.1, psfxtable.1, setleds.1, setmetamode.1,
    showkey.1, unicode_start.1, unicode_stop.1, dumpkeys.1, loadkeys.1,
    codepage.1, screendump.1, splitfont.1
  usr/share/man/man8:
    getkeycodes.8, kbdrate.8, resizecons.8, setkeycodes.8, showconsolefont.8,
    setvtrgb.8, loadunimap.8, mapscrn.8, setfont.8, clrunimap.8, getunimap.8,
    mk_modmap.8, setlogcons.8, setvesablank.8, vcstime.8
