#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cp ${WHERE_I_AM}/diff.M4.psmisc.patch ${CLFSTARS}/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://downloads.sourceforge.net/psmisc/psmisc-22.21.tar.gz' \
    'psmisc-22.21' \
    '' \
	'patch -Np3 -i ${TARSAT}/diff.M4.psmisc.patch 1>&2' \
    '' \
    "./configure \
	  --disable-harden_flags \
	  --prefix=${CLFS_NEW_ROOT}/usr \
	  --build=${CLFS_HOST} --host=${CLFS_TARGET} --target=${CLFS_TARGET} 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source nor patch for psmisc-22.21 any longer."
    rm -rf psmisc-22.21
    rm -f ${CLFSTARS}/diff.M4.psmisc.patch
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/locale/*
    usr/share/gettext/po/*
  usr/share/man/man1:
    killall.1, peekfd.1, prtstat.1, pstree.1, fuser.1
  usr/bin:
    killall, peekfd, prtstat, pstree, fuser, pstree.x11
