#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cp ${WHERE_I_AM}/diff.M4.libestr.patch ${CLFSTARS}/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://libestr.adiscon.com/files/download/libestr-0.1.10.tar.gz' \
    'libestr-0.1.10' \
    '' \
	'patch -Np3 -i ${TARSAT}/diff.M4.libestr.patch 1>&2' \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT}/usr \
	  --build=${CLFS_HOST} --host=${CLFS_TARGET} --target=${CLFS_TARGET} 1>&2" \
    'make -j 20 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source nor patch for libestr-0.1.10 any longer."
    rm -rf libestr-0.1.10
    rm -f ${CLFSTARS}/diff.M4.libestr.patch
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/include/libestr.h
    usr/lib/libestr.a
    usr/lib/libestr.la
    usr/lib/libestr.so
    usr/lib/libestr.so.0
    usr/lib/libestr.so.0.0.0
    usr/lib/pkgconfig/libestr.pc
