#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# This must not have "make" with "-j" option.
cp ${WHERE_I_AM}/diff.M4.libee.patch ${CLFSTARS}/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.libee.org/download/files/download/libee-0.4.1.tar.gz' \
    'libee-0.4.1' \
    '' \
    'patch -Np3 -i ${TARSAT}/diff.M4.libee.patch 1>&2' \
    '' \
    "PKG_CONFIG_PATH=${CLFS_NEW_ROOT}/usr/lib/pkgconfig ./configure \
	  --prefix=${CLFS_NEW_ROOT}/usr \
	  --build=${CLFS_HOST} --host=${CLFS_TARGET} --target=${CLFS_TARGET} 1>&2" \
    'make 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# NOTE: cannot be make -j 20 -- doesn't work.
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source nor patch for libee-0.4.1 any longer."
    rm -rf libee-0.4.1
    rm -f ${CLFSTARS}/diff.M4.libee.patch
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/include/libee/*
    usr/lib/libee.a
    usr/lib/libee.la
    usr/lib/libee.so
    usr/lib/libee.so.0
    usr/lib/libee.so.0.0.0
    usr/lib/pkgconfig/libee.pc
