#!/bin/bash -e
. 1.clfs.set.variables
#=============================================================================
cp ${WHERE_I_AM}/diff.M4.rsyslog.patch ${CLFSTARS}/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://www.rsyslog.com/files/download/rsyslog/rsyslog-6.4.2.tar.gz' \
    'rsyslog-6.4.2' \
    '' \
	'patch -Np2 -i ${TARSAT}/diff.M4.rsyslog.patch 1>&2' \
    '' \
    "PKG_CONFIG_PATH=${CLFS_NEW_ROOT}/usr/lib/pkgconfig ./configure \
	  --prefix=${CLFS_NEW_ROOT}/usr \
	  --build=${CLFS_HOST} --host=${CLFS_TARGET} --target=${CLFS_TARGET} \
	  --disable-libgcrypt \
	  --without-systemd \
	  --disable-generate-man-pages \
	  --disable-mmjsonparse 1>&2" \
    'make 1>&2' \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
install -dv ${CLFS_NEW_ROOT}/etc/rsyslog.d
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cat > ${CLFS_NEW_ROOT}/etc/rsyslog.conf << "EOF"
# Begin /etc/rsyslog.conf

# CLFS configuration of rsyslog. For more info use man rsyslog.conf

#######################################################################
# Rsyslog Modules

# Support for Local System Logging
$ModLoad imuxsock.so

# Support for Kernel Logging
$ModLoad imklog.so

#######################################################################
# Global Options

# Use traditional timestamp format.
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# Set the default permissions for all log files.
$FileOwner root
$FileGroup root
$FileCreateMode 0640
$DirCreateMode 0755

# Provides UDP reception
$ModLoad imudp
$UDPServerRun 514

# Disable Repeating of Entries
$RepeatedMsgReduction on

#######################################################################
# Include Rsyslog Config Snippets

$IncludeConfig /etc/rsyslog.d/*.conf

#######################################################################
# Standard Log Files

auth,authpriv.*			/var/log/auth.log
*.*;auth,authpriv.none		-/var/log/syslog
daemon.*			-/var/log/daemon.log
kern.*				-/var/log/kern.log
lpr.*				-/var/log/lpr.log
mail.*				-/var/log/mail.log
user.*				-/var/log/user.log

# Catch All Logs
*.=debug;\
	auth,authpriv.none;\
	news.none;mail.none	-/var/log/debug
*.=info;*.=notice;*.=warn;\
	auth,authpriv.none;\
	cron,daemon.none;\
	mail,news.none		-/var/log/messages

# Emergencies are shown to everyone
*.emerg				*

# End /etc/rsyslog.conf
EOF
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source nor patch for rsyslog-8.6.0 any longer."
    rm -rf rsyslog-8.6.0
    rm -f ${CLFSTARS}/diff.M4.rsyslog.patch
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
