#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#-- cp ${WHERE_I_AM}/patches/bootscripts-cross-lfs-3.0-20140710.patch ${CLFSTARS}/
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.clfs.org/pub/clfs/conglomeration/bootscripts-cross-lfs/bootscripts-cross-lfs-3.0-20140710.tar.xz' \
    'bootscripts-cross-lfs-3.0-20140710' \
    'wget -N http://patches.clfs.org/sysvinit/bootscripts-cross-lfs-3.0-20140710-tools_updates-2.patch' \
    'patch -Np1 -i ${TARSAT}/bootscripts-cross-lfs-3.0-20140710-tools_updates-2.patch 1>&2' \
    '' \
    'true ' \
    'true' \
    "make DESTDIR=${CLFS_NEW_ROOT} install-minimal install-bootscripts install-network install-service-dhcpcd install-sshd 1>&2"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
cat > ${CLFS_NEW_ROOT}/etc/sysconfig/clock << "EOF"
# Begin /etc/sysconfig/clock

UTC=1

# End /etc/sysconfig/clock
EOF
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source nor patch for bootscripts-cross-lfs-3.0-20140710 any longer."
    rm -rf bootscripts-cross-lfs-3.0-20140710
    rm -f ${CLFSTARS}/bootscripts-cross-lfs-3.0-20140710.patch
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    etc/rc.d/*
    etc/sysconfig/*
