#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/inetutils/inetutils-1.9.2.tar.xz' \
    'inetutils-1.9.2' \
    '' \
    '' \
    '' \
    "./configure \
	  --prefix=${CLFS_NEW_ROOT} --build=${CLFS_HOST} --host=${CLFS_TARGET} \
	  --target=${CLFS_TARGET} --bindir=${CLFS_NEW_ROOT}/bin \
	  --sbindir=${CLFS_NEW_ROOT}/sbin --libexecdir=${CLFS_NEW_ROOT}/libexec \
	  --sysconfdir=${CLFS_NEW_ROOT}/etc --localstatedir=${CLFS_NEW_ROOT}/var \
	  --libdir=${CLFS_NEW_ROOT}/lib --includedir=${CLFS_NEW_ROOT}/usr/include \
	  --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --disable-logger \
	  --disable-whois \
	  --disable-servers \
	  --disable-dnsdomainname \
	  --disable-hostname \
	  --disable-rcp \
	  --disable-rexec \
	  --disable-rlogin \
	  --disable-rsh \
	  --disable-talk \
	  --disable-tftp \
	  --disable-readline \
	  --with-gnu-ld \
	  --disable-ping 1>&2" \
    "make 'CFLAGS=-DPATH_PROCNET_DEV=\\\"/proc/net/dev\\\"' -j 20 1>&2" \
    'make -i install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for inetutils-1.9.2 any longer."
    rm -rf inetutils-1.9.2
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    bin/traceroute
    bin/telnet
    bin/ftp
    bin/ping6
    bin/ifconfig
    usr/share/info/inetutils.info
  usr/share/man/man1:
    ifconfig.1, ftp.1, ping6.1, telnet.1, traceroute.1
