#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Note: cannot have "make -j 20" for this package.
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N ftp://openssl.org/source/openssl-1.0.2j.tar.gz' \
    'openssl-1.0.2j' \
    '' \
    '' \
    '' \
    "./config --prefix=${CLFS_NEW_ROOT}/usr \
	  --openssldir=${CLFS_NEW_ROOT}/etc/ssl\
	  --libdir=/lib \
	  shared \
	  zlib-dynamic \
	  1>&2" \
    "make -j1 1>&2" \
    "make install 1>&2"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source nor patch for openssl-1.0.2a any longer."
    rm -rf openssl-1.0.2j
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    etc/ssl/*
    usr/lib/engines/*
    usr/include/openssl/*
    usr/lib/libcrypto.so
    usr/lib/libcrypto.so.1.0.0
    usr/lib/libcrypto.a
    usr/lib/libssl.so.1.0.0
    usr/lib/libssl.so
    usr/lib/libssl.a
    usr/lib/pkgconfig/libcrypto.pc
    usr/lib/pkgconfig/libssl.pc
    usr/lib/pkgconfig/openssl.pc
