#!/bin/bash -ex
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
mkdir -pv ${CLFS_NEW_ROOT}/var/lib/sshd

export LD="${CC}"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# 'wget -N https://www.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-7.4.tar.gz' \

${WHERE_I_AM}/INSTALL.parameters \
    'wget -N ftp://ftp3.usa.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-7.4p1.tar.gz' \
    'openssh-7.4p1' \
    '' \
    '' \
    '' \
    "./configure --prefix=${CLFS_NEW_ROOT} \
	  --sysconfdir=${CLFS_NEW_ROOT}/etc/ssh --bindir=${CLFS_NEW_ROOT}/bin \
	  --sbindir=${CLFS_NEW_ROOT}/sbin --libexecdir=${CLFS_NEW_ROOT}/libexec \
	  --localstatedir=${CLFS_NEW_ROOT}/var --libdir=${CLFS_NEW_ROOT}/usr/lib \
	  --includedir=${CLFS_NEW_ROOT}/usr/include --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --build=${CLFS_HOST} --host=${CLFS_TARGET} --target=${CLFS_TARGET} \
	  --with-md5-passwords --with-privsep-path=${CLFS_NEW_ROOT}/var/lib/sshd 1>&2" \
    "make -j 20 1>&2" \
    "make install-nokeys 1>&2"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# NOTE: install tries to make the keys using the keygen just compiled.
cd openssh-7.4p1
install -v -m755 contrib/ssh-copy-id ${CLFS_NEW_ROOT}/bin
cd ..
ln -sf ../../sbin/sshd ${CLFS_NEW_ROOT}/usr/sbin/sshd
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for openssh-7.4p1 any longer."
    rm -rf openssh-7.4p1
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
  bin:
    ssh, scp, ssh-add, ssh-agent, ssh-keygen, ssh-keyscan, sftp, slogin,
    ssh-copy-id
  sbin:
    sshd
  usr/sbin:
    sshd
  libexec:
    ssh-keysign, ssh-pkcs11-helper, sftp-server
  usr/share/man/man1:
    ssh.1, scp.1, ssh-add.1, ssh-agent.1, ssh-keygen.1, ssh-keyscan.1,
    sftp.1, slogin.1
  usr/share/man/man5:
    moduli.6, sshd_config.5, ssh_config.5
  usr/share/man/man8:
    sshd.8, sftp-server.8, ssh-keysign.8, ssh-pkcs11-helper.8
  etc/ssh/*
