#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://ftp.gnu.org/gnu/wget/wget-1.18.tar.xz' \
    'wget-1.18' \
    '' \
    '' \
    '' \
    "PKG_CONFIG_PATH=${CLFS_NEW_ROOT}/usr/lib/pkgconfig \
	  ./configure --prefix=${CLFS_NEW_ROOT} --bindir=${CLFS_NEW_ROOT}/bin \
	  --sbindir=${CLFS_NEW_ROOT}/sbin --libexecdir=${CLFS_NEW_ROOT}/libexec \
	  --sysconfdir=${CLFS_NEW_ROOT}/etc --localstatedir=${CLFS_NEW_ROOT}/var \
	  --libdir=${CLFS_NEW_ROOT}/lib --includedir=${CLFS_NEW_ROOT}/usr/include \
	  --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --build=${CLFS_HOST} --host=${CLFS_TARGET} --target=${CLFS_TARGET} \
	  --with-ssl=openssl 1>&2" \
    "make -j 20 1>&2" \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for wget-1.18 any longer."
    rm -rf wget-1.18
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    bin/wget
    usr/share/man/man1/wget.1
    usr/share/info/wget.info
    usr/share/locale/*
    usr/share/gettext/po/*
