#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N http://curl.haxx.se/download/curl-7.52.1.tar.lzma' \
	'curl-7.52.1' \
    'wget -N http://www.linuxfromscratch.org/patches/blfs/svn/curl-7.52.1-valgrind_filter-1.patch' \
    'patch -Np1 -i ${TARSAT}/curl-7.52.1-valgrind_filter-1.patch' \
    '' \
    "./configure --prefix=${CLFS_NEW_ROOT} --bindir=${CLFS_NEW_ROOT}/bin \
	  --sbindir=${CLFS_NEW_ROOT}/sbin --libexecdir=${CLFS_NEW_ROOT}/libexec \
	  --sysconfdir=${CLFS_NEW_ROOT}/etc --localstatedir=${CLFS_NEW_ROOT}/var \
	  --libdir=${CLFS_NEW_ROOT}/lib --includedir=${CLFS_NEW_ROOT}/usr/include \
	  --datarootdir=${CLFS_NEW_ROOT}/usr/share \
	  --build=${CLFS_HOST} --host=${CLFS_TARGET} --target=${CLFS_TARGET} \
	  --disable-static \
	  --enable-threaded-resolver 1>&2" \
    "make -j 20 1>&2" \
    'make install 1>&2'
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for curl-7.52.1 any longer."
    rm -rf curl-7.52.1
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    lib/libcurl.la
    lib/libcurl.so
    lib/libcurl.so.4
    lib/libcurl.so.4.3.0
    lib/libstdc++.so.6.0.21-gdb.py
    bin/curl
    usr/include/curl/*
    bin/curl-config
    lib/pkgconfig/libcurl.pc
    usr/share/man/man3/*
    usr/share/aclocal/libcurl.m4
    usr/share/man/man1/curl.1
    usr/share/man/man1/curl-config.1
