#!/bin/bash -e
. 1.clfs.set.variables
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
${WHERE_I_AM}/INSTALL.parameters \
    'wget -N ftp://anduin.linuxfromscratch.org/BLFS/net-tools/net-tools-CVS_20101030.tar.gz' \
    'net-tools-CVS_20101030' \
    'wget -N http://www.linuxfromscratch.org/patches/blfs/svn/net-tools-CVS_20101030-remove_dups-1.patch' \
    'patch -Np1 -i ${TARSAT}/${PATCHNAME} 1>&2' \
    '' \
    "make clean && printf 'y\ny\n\ny\n\ny\nn\nn\nn\nn\nn\nn\nn\nn\nn\ny\nn\nn\nn\nn\nn\nn\nn\nn\nn\nn\nn\ny\ny\nn\nn\nn\nn\nn\nn\nn\nn\nn\nn\n' | make config 1>&2 && sed -e 's/HAVE_AFDECnet 1/HAVE_AFDECnet 0/' -e 's/HAVE_HWTR 1/HAVE_HWTR 0/' -e 's/HAVE_HWSTRIP 1/HAVE_HWSTRIP 0/' -i config.h" \
    "make DESTDIR=${CLFS_NEW_ROOT} -j 20 1>&2" \
    "make DESTDIR=${CLFS_NEW_ROOT} install 1>&2"
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
if ${RM_UNPACKED_SOURCES_WHEN_DONE}; then
    echo "Do not need source for net-tools-CVS_20101030 any longer."
    rm -rf net-tools-CVS_20101030
fi
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
Installs (new_root):
    usr/share/locale
  bin:
    netstat, 
  sbin:
    arp, nameif, plipconfig, rarp, route, slattach
