#!/bin/bash -e
# MUST NOT BE CROSS-COMPILED.
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
./INSTALL.on.system \
    'wget -N http://prdownloads.sourceforge.net/expect/expect5.45.tar.gz' \
    'expect5.45' \
    '' \
    '' \
    '' \
    "./configure --prefix=/usr --with-tcl=/lib --with-tclinclude=/include 1>&2" \
    'make -j 20 1>&2' \
    'make SCRIPTS="" install 1>&2' \
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
exit 0
#=============================================================================
./configure --prefix=/tools --with-tcl=/tools/lib --with-tclinclude=/tools/include

make

make SCRIPTS="" install
#=============================================================================
