#!/bin/csh -x
set time = (1 '\
Wall time %E.  System CPU %S sec.  User CPU %U sec.  CPU %P%%\
Memory %M kb.  Shared %X kb.  Unshared data %D kb.  Unused stack %K kb.\
Swaps %W.  Page faults %F.  Input %I blks.  Output %O blks.\
')				# time automatically after 1 seconds.
#
# ./writecnt of=/dev/sdc bs=64k
# ./readcnt if=/dev/sdc bs=64k

root ./writecnt of=/dev/sdc bs=512
root ./readcnt  if=/dev/sdc bs=512
