#!/bin/bash -e
# Script to chroot into different environment

TARGET_ENV="$1"
ENV_DIR="/env/${TARGET_ENV}"
DIR="`pwd`"
THIS_USER="`id -nu`"

shift

if [[ ! -d "${ENV_DIR}" ]]; then
	echo "Environment ${ENV_DIR} not found" >> /dev/stderr
	exit 1
fi

cd "${ENV_DIR}"
root -k chroot "${ENV_DIR}" su "${THIS_USER}" -c "cd \"${DIR}\"; $*"
