#!/bin/bash -e
# Script to chroot into different environment

TARGET_ENV="$1"
ENV_DIR="/env/${TARGET_ENV}"
DIR="`pwd`"
THIS_USER="`id -nu`"

shift

if [[ ! -d "${ENV_DIR}" ]]; then
	echo "Environment ${ENV_DIR} not found" >> /dev/stderr
	exit 1
fi

cd "${ENV_DIR}"
# root -k chroot "${ENV_DIR}" su "${THIS_USER}" -c "cd \"${DIR}\"; \"${SHELL}\" \"+m\""

# root [-k] [-u uid] command
#	-k = keep environment
# root -k chroot "${ENV_DIR}" su "${THIS_USER}" -c "cd \"${DIR}\"; \"${SHELL}\" \"+m\""
# chroot /env/bld03 command
# su -l		make shell a login shell
# su -c	command	pass a command to the shell
# su -f		pass -f to the shell
# su -m		do not reset environment variables
# su -p		same as -m
# su -s	SHELL	run SHELL if /etc/shells allows it

root -k chroot ${ENV_DIR} su -l ${THIS_USER} -s /bin/bash -c "set -m; export TARGET_ENV='${TARGET_ENV}:';
cd ${DIR}; ${SHELL} -li"
