#!/bin/bash -ex

cat loudness.brass.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
cat loudness.triangle.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
cat loudness.snaredrum.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
cat loudness.gunshot.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
cat loudness.cymbal.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
cat loudness.viola.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
cat loudness.tambourine.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read

# cat loudness.bassdrum.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
# cat loudness.bassoon.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
# cat loudness.cello.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
# cat loudness.clarinet.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
# cat loudness.contrabass.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
# cat loudness.englishhorn.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
# cat loudness.flute.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
# cat loudness.frenchhorn.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
# cat loudness.oboe.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
# cat loudness.piccolo.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
# cat loudness.pizz.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
# cat loudness.timpani.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
# cat loudness.trombone.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
# cat loudness.tuba.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
# cat loudness.violin.fs | fluidsynth -a coreaudio -d -n -q -K 128 ; read
